//
//  Aaron.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let aaron = Park(name: "aaron",
                 about: "\u{2022} Conveniently located off of the Trans-Canada Highway, this park is the perfect stopping point for cross-country explorers.\n\u{2022} Two sandy beaches and the clear, shallow waters of Thunder Lake make Aaron ideal for water based activities, such as swimming, boating and fishing.\n\u{2022} The park’s Thunder Lake is a remnant of the ancient glaciers that covered Ontario tens of thousands of years ago.",
                 general: "\u{2022} Phone: (807)938-6534 summer (807)223-7535 winter\n\u{2022} Size: 116.74 ha\n\u{2022} Year established: 1958\n\u{2022} Park Classification: Recreational\n\u{2022} Address:\n\tBox 730, 479 Government Street\n\tDryden ON\n\tP8N 2Z4",
                 camping: [0: (heading: "\(cCar)", detail: "The campground offers almost 100 campsites, one-third of which have electricity.  Campsites can accommodate equipment ranging from tents only to large trailers.  Amenities such as water taps, comfort stations and laundry facilities are close by.  Swimming, boating, great fishing and hiking are only a short distance away."), 1: (heading: "\(cGrp)", detail: "Aaron has one group campsite.  The site accommodates 15 to 50 people.  Water taps and vault toilets are on site. The area is within walking distance of a comfort station, the beach and hiking trails. To reserve, call the park directly: (807) 938-6534.")],
                 activities: [0: (heading: "\(aBik)", detail: "Biking is a popular way to wander through Aaron and view the Eastern White Cedars that line the campground roads. Children are reminded to wear a helmet when biking."), 1: (heading: "\(aBrd)", detail: "Many bird species and migratory waterfall call Aaron home."), 2: (heading: "\(aBtg)", detail: "Boating is permitted on Thunder Lake but please take care when there are high winds; this open lake can get very choppy."), 3: (heading: "\(aCan)", detail: "Aaron is located on the shores of Thunder Lake.  Spend the day exploring by canoe. Canoes are available for rent at the Park Office. Aaron can also be used as a starting point for several major canoe routes."), 4: (heading: "\(aFsh)", detail: "The lakes in and around the park teem with Northern Pike, walleye and Lake Trout. A fish-cleaning station with lights, running water and cutting tables is located by the boat launch"), 5: (heading: "\(aHik)", detail: "\u{2022} Aspen Trail - 2km, moderate\n\tThe Aspen Trail will introduce you to stands of boreal forest consisting of aspen, birch, Jack Pine, Balsam Fir and spruce trees. Walk through the remnants of the terrific wind storm of 1973 and over bare rock surfaces scarred by glaciers which melted 10 to 15 thousand years ago! Look for signs of White-tailed Deer, such as browsed branches, tracks and pellets. All the while you will be entertained by Aaron’s 26 species of warblers, as well as other boreal songbirds.\n\n\u{2022} Eastern White Cedar Trail - 1.2 km loop, easy\n\tA stroll down this trail will help you appreciate the history and ecology of Aaron. You will walk through large, historic stands of trees, hike along the shores and wetlands of Thunder Lake and climb up a slope to a clay plain. See how many species of amphibians, mammals, birds, trees, flowers, lichens, and mosses you can spot along the way."), 6: (heading: "\(aSwm)", detail: "Aaron has two sandy beaches for swimmers that are located on the east and west sides of the park.  Parking, picnic tables and toilet facilities are conveniently located. Please note that there are no lifeguards posted at the beaches.")],
                 facilities: [0: (heading: "\(fBF)", detail: "Barrier-free access is available at the comfort station."), 1: (heading: "\(fBL)", detail: "A boat launch is located by the fish cleaning hut."), 2: (heading: "\(fCS)", detail: "A comfort station with showers and flush toilets is located in the main campground."), 3: (heading: "\(fDU)", detail: "Aaron is a perfect day destination for visitors from the Dryden area.  The day-use area has a beach, large grassy play area, playground, picnic shelter, water taps and vault toilets."), 4: (heading: "\(fFT)", detail: "Flush toilets are found in various locations throughout the park, including the comfort station in the main campground."), 5: (heading: "\(fL)", detail: "Laundry facilities can be found at the comfort station in the main campground."), 6: (heading: "\(fPSt)", detail: "Located in the Park Office, the store features clothing items, souvenirs, camper supplies, ice and firewood.\n\nGroceries are available outside of the park in Dryden, 11 km west of the park on Highway 17."), 7: (heading: "\(fPSh)", detail: "There is one picnic shelter in the day-use area of the park and it is available on a first-come first-served basis."), 8: (heading: "\(fR)", detail: "Canoes and kayaks are available for rent at the Park Office. Personal Floatation Devices (PFDs) are also available for loan with a $25 refundable deposit.")])