//
//  balsam.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let balsam = Park(name: "balsam lake",
                  about: "\u{2022} Boating on the Trent-Severn Waterway\n\u{2022} Large sandy beach\n\u{2022} Good fishing for Walleye, Muskellunge, Large and Small Mouth Bass\n\u{2022} Canoe, kayak and paddleboat rentals\n\u{2022} Easy day-trip hiking trails\n\u{2022} Gift shop\n\u{2022} Fully-furnished 4-bedroom rental cottage near the water",
                  general: "\u{2022} Phone: 705-454-3324\n\u{2022} Size: 448.81 ha\n\u{2022} Year established: 1968\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t2238 Hwy 48 R.R #1\n\tKirkfield\n\tK0M 2B0",
                  camping: [0: (heading: "\(cCar)", detail: "Balsam Lake has a range of campsites with and without electricity for tents and RVs. For a private, natural experience car access walk-in sites are also available. Campsites may be reserved from the second Friday in May through to the Thanksgiving weekend. Reservations are accepted five months in advance of arrival – reserve early to avoid disappointment."), 1: (heading: "\(cDog)", detail: "Dog free camping is available at the six Eco (walk-in) sites."), 2: (heading: "\(cGrp)", detail: "At Balsam Lake there are three Group Camping sites serviced with vault privies and drinking water. The use of the site is for non-profit youth groups only and must be requested by completion of the online application form."), 3: (heading: "\(cRad)", detail: "Eco (walk-in) sites, Cedar Grove, Mapleview and Hawthorne Valley campgrounds are now radio-free."), 4: (heading: "\(cWak)", detail: "Six radio-free, pet free, Eco (walk-in) campsites are available."), 5: (heading: "\(cRof)", detail: "Please see website for most up to date information on roofed accomodation.")],
                  activities: [0: (heading: "\(aBik)", detail: "Cycle on campground roads and over 10 km of local cottage roads (adjacent to the park)."), 1: (heading: "\(aBrd)", detail: "Find a wide range of birds from hummingbirds, Blue birds, cardinals, Northern orioles, Pileated woodpeckers, hawks, osprey and owls. Relax to the call of the loon."), 2: (heading: "\(aBtg)", detail: "Canoes, kayaks and paddle boats are available to rent on the south end of the beach. Personal floatation devices (PFDs) are supplied for all rentals. A boat launch and boat trailer parking is available."), 3: (heading: "\(aCan)", detail: "Explore the shores of Balsam Lake."), 4: (heading: "\(aFsh)", detail: "Fish for Walleye, Muskellunge, Large and Small Mouth Bass."), 5: (heading: "\(aHik)", detail: "\u{2022} Lookout Trail – 2.6 km (1.5 hours) walk through eskers and kames formed over 10,000 years ago from the Wisconsin Glacier. Enjoy a panoramic view of the surrounding area. \n\n\u{2022} Plantation Trail – 4.2 km (2 hours) – a moderate forest trek with both natural and pioneer highlights."), 6: (heading: "\(aNHE)", detail: "Regularly scheduled programs and events including excellent children’s programs are available during the summer season."), 7: (heading: "\(aSwm)", detail: "The clean, sandy beach is marked with buoys. Please note that there are no lifeguards posted.")],
                  facilities: [0: (heading: "\(fBL)", detail: "Docking and trailer parking is available."), 1: (heading: "\(fDU)", detail: "There is a shady, grassed area with an excellent view of the lake and a children’s playground."), 2: (heading: "\(fL)", detail: "Coin operated washers and dryers are available at our four comfort stations."), 3: (heading: "\(fPSt)", detail: "The park gift shop offers clothing items, souvenirs, ice, ice cream, coffee and firewood. Groceries are available just outside the park at The Park Store and in the town of Coboconk."), 4: (heading: "\(fPEA)", detail: "Located at canoe launch."), 5: (heading: "\(fPSh)", detail: "There are three large picnic shelters located near the main beach area. The shelters maybe reserved by calling the park at (705)-454-3324 (not available to reserve on holiday weekends)."), 6: (heading: "\(fR)", detail: "Canoes, kayaks and paddle boats are available to rent on the beach.")])
