//
//  Caliper.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let caliper = Park(name: "caliper lake",
                   about: "\u{2022} Campground features an impressive stand of old growth red and white pine trees\n\u{2022} The dedicated angler might catch Northern pike, crappie, walleye, or Smallmouth bass\n\u{2022} Large beach and buoyed swimming area provide family fun\n\u{2022} Lucky individual might see American White pelicans that occasionally make Caliper Lake their home",
                   general: "\u{2022} Phone: 807-484-2181 or 807-468-2669 (Sept – April)\n\u{2022} Size: 147.35 ha\n\u{2022} Year established: 1960\n\u{2022} Park Classification: Recreational\n\u{2022} Address:\n\tP.O. Box 188\n\tNestor Falls, ON\n\tP0X 1K0",
                   camping: [0: (heading: "\(cCar)", detail: "Almost 100 picturesque campsites await you at Caliper Lake. One-quarter of the sites have electrical hook-up and a dump and fill station is located in the park. A modern comfort station with showers and flush toilets is centrally located in the campground. \n\nA limited number of seasonal campsites are available via a draw in early May. Contact the park directly at (807) 484-2181 for further details."), 1: (heading: "\(cGrp)", detail: "Caliper Lake has one group campsite located on the east side of the park, directly overlooking the lake.  A water tap and vault toilets are on site; showers are located a ten minute walk away at the comfort station.  This site can accommodate up to 40 people.  Reservations for group camping can be made by calling the park directly at (807) 484-2181 beginning in May."), 2: (heading: "\(cWak)", detail: "Caliper Lake has eight waterfront campsites where you park along the main road and then take a short path (20m– 50m) to your campsite. These campsites are very popular.")],
                   activities: [0: (heading: "\(aBik)", detail: "Biking on park roads is a great way to get around and explore the park. Visitors are reminded that Ontario law requires helmets to be worn by those aged 18 years and younger when biking on roads, including those in provincial parks."), 1: (heading: "\(aBrd)", detail: "Visitors may spot nesting pelicans at Caliper Lake or listen for the call of the Barred Owl."), 2: (heading: "\(aBtg)", detail: "Caliper Lake is easily navigable with few water hazards. A boat launch and docking facilities are available in the park."), 3: (heading: "\(aCan)", detail: "The peaceful waters of Caliper Lake offer a relaxing option for a day of canoeing. Visitors can rent canoes at the park office or bring their own."), 4: (heading: "\(aFsh)", detail: "Caliper Lake’s clean, warm waters are home to Northern Pike, walleye, crappie and Smallmouth Bass."), 5: (heading: "\(aHik)", detail: "\u{2022} Beaver Pond Trail - 2– 3km, moderate \n\tThe Beaver Pond Trail is accessed off the main entrance road between the Park Office and the beach.  Two loops offer hikers a choice between a 2 km and 3 km hike."), 6: (heading: "\(aSwm)", detail: "A large beach and sectioned off swimming area make swimming a favourite activity at Caliper Lake. Enjoy the warm, shallow water and floating swim platform.")],
                   facilities: [0: (heading: "\(fBF)", detail: "The camping and day-use comfort stations provide barrier-free access to showers and flush toilets. Campsites #52 (electrical) and #53 (non-electrical) are also barrier free."), 1: (heading: "\(fBL)", detail: "Two boat launches, with ample space for trailer parking, are located in the park."), 2: (heading: "\(fCS)", detail: "A clean and modern comfort station with flush toilets and showers is conveniently located between the electrical and non-electrical camping areas. A second comfort station with flush toilets is located in the main day-use area by the beach."), 3: (heading: "\(fDU)", detail: "The large grassy day-use area next to the beach is an excellent place to spend the day.  This area has a picnic shelter and playground."), 4: (heading: "\(fFT)", detail: "Flush toilets are located at each of the two comfort stations."), 5: (heading: "\(fPSt)", detail: "Firewood, ice, souvenirs and basic camping supplies are available at the park office."), 6: (heading: "\(fPSh)", detail: "A picnic shelter is located in the main day-use area and adjacent to the beach. The shelter is available on a first-come, first-served basis."), 7: (heading: "\(fR)", detail: "Canoes and kayaks are available for rent at the park office.")])
