//
//  Chutes.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let chutes = Park(name: "chutes",
                  about: "\u{2022} A quiet campground located on the Aux Sables River\n\u{2022} A six kilometre hiking trail with great views of scenic waterfalls and river gorge\n\u{2022} One kilometer from the Trans-Canada Highway this is the only provincial park between Sudbury and Sault Ste Marie\n\u{2022} Close to the town of Massey with amenities, cultural museum, public librar\n\u{2022} Situated near a variety of hiking trails, fishing and canoeing/kayaking opportunitie\n\u{2022} A great base to explore Manitoulin Island and the North Channel of Lake Huron",
                  general: "\u{2022} Phone: 705-865-202\n\u{2022} Size: 108.32 h\n\u{2022} Year established: 197\n\u{2022} Park Classification: Recreationa\n\u{2022} Address\n\tP.O. Box 37, 660 Imperial Street Nort\n\tMasse\n\tP0P 1P0",
                  camping: [0: (heading: "\(cCar)", detail: "Most of the campsites are within a short walking distance of scenic waterfalls. Almost half of the sites in the park are electrical and all electrical sites are situated in a pine forest. \n\nEach site has a fire pit and picnic table and is located close to vault toilets and water taps containing potable water. A comfort station at the centre of the campground has flush toilets, showers and laundry facilities. \n\nTwo campgrounds, A and B, offer electrical sites and are situated closest to the comfort station. There are many large sites suitable for RVs and trailers although none are pull-through sites. \n\nCampground A has two barrier-free campsites; these are located close to the comfort station and have barrier-free fire pits and gravelled ground cover. \n\nCampground D is located in an area of mixed forest near the day-use and swimming area. Some of the sites in D are close to townhomes and activity."), 1: (heading: "\(cGrp)", detail: "Two large group sites are available at Chutes and both are non-electric. Group site #401 can accommodate 25-30 tents and is a five minute walk to the comfort station and a ten minute walk to the beach..There is water on-site and bathrooms nearby. \n\nGroup site #402 is slightly smaller and will accommodate 10-15 tents. The site is a five minute walk to the campground and a ten minute walk to the beach. A water supply and bathrooms are located close to the site. \n\nDue to the proximity of the group campsites within the regular campground, they can only be reserved by “organized groups” (i.e. church or youth groups). Reservations can be made by calling the Park Clerk at (705) 865-2021."), 3: (heading: "\(cRad)", detail: "Campground C is a radio-free area.  This campground is situated in a mixed forest and is close to the hiking trail and day-use area.  The sound of the main waterfall can be heard from campsites #90-96.")],
                  activities: [0: (heading: "\(aBik)", detail: "Biking is available on park roads only. There are no dedicated bike trails in the park. Chutes is a few blocks north of Highway 17 and right next to the town of Massey where local town and municipal roads are available for cycling."), 1: (heading: "\(aBrd)", detail: "Many species of birds nest in the park. Walking the trails along the river is a great way to see and hear them but you’ll come across many birds right in the campground. Local species include a variety of woodpeckers (Pileated, Downy, Hairy), sapsuckers, thrushes, nuthatches, chickadees, kinglets, flycatchers, vireos and warblers."), 2: (heading: "\(aFsh)", detail: "The river can be fished along the banks in several areas. On the Aux Sables River north of the park and on the Spanish River there is good fishing available. In the fall, salmon run up the Aux Sables River to spawn below the main waterfall."), 3: (heading: "\(aHik)", detail: "\u{2022} Twin Bridges Trail - 6 km return (2 hours) moderate \n\t Following the Aux Sables River this trail leads to lookouts at the falls and the Seven Sisters Cataracts. Interpretive panels at the Falls Lookout tell the history of the area. There is an interpretive trail guide available. \n\nOther trails to hike in the area include the Cup and Saucer Trail on Manitoulin Island, Willisville Mountain in the La Cloche Range near Espanola, and the many trails at Mississagi Provincial Park near Elliott Lake, an hour northeast of Chutes."), 4: (heading: "\(aSwm)", detail: "The park has a fine sandy beach tucked in a bend in the river below the falls. There are no lifeguards. Swimming is not permitted in any other area of the river within the park."), 5: (heading: "\(aWA)", detail: "The park is gated, but visitors are welcome to walk in. The views of the .Aux Sables River are spectacular in winter and the many waterfalls and cataracts along the river are especially scenic. Bring your snowshoes and cross-country skis or just come for a winter hike.")],
                  facilities: [0: (heading: "\(fBF)", detail: "Campground A has two barrier-free campsites. These are located close to the comfort station and have barrier-free fire pits and gravelled ground cover."), 1: (heading: "\(fCS)", detail: "The comfort station offers five showers and two bathrooms with flush toilets, as well as a laundry facility with washers and dryers. All facilities are barrier-free. The laundry machines operate with $1 coins (loonies)."), 2: (heading: "\(fDU)", detail: "A picnic and day-use area next to the beach and the Falls Lookout make the park an ideal stop for lunch or a short hike. A picnic shelter can be reserved for large groups."), 3: (heading: "\(fFT)", detail: "Flush toilets are available in the comfort station."), 4: (heading: "\(fL)", detail: "Laundry facilities are available in the comfort station."), 5: (heading: "\(fPSt)", detail: "The park store, located in the gatehouse, offers a selection of Ontario Parks’ merchandise. There is a Pepsi vending machine at the comfort station. Personal floatation devices (PFDs) are available with a $25 refundable deposit."), 6: (heading: "\(fPEA)", detail: "A fenced section for pets to exercise off-leash is found in the day-use area. There is a path to a section of the river where pets can swim. The current here can vary depending on water levels."), 7: (heading: "\(fPSh)", detail: "There is one picnic shelter in the day-use area near the river which can be reserved for family gatherings, picnics and functions (call the Park Clerk at 705-865-2021). The shelter has no hydro but does have picnic tables and garbage bins.")])
