//
//  Craigleith.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let craigleith = Park(name: "craigleith",
                      about: "\u{2022} Located on the southern shore of Georgian Bay\n\u{2022} Fractured plates of shale that form our shoreline contain fossils that are 450 million years old\n\u{2022} Flat rock is ideal for launching a sailboat, kayak/canoe, paddle board, wind surfing, fishing or watching a spectacular sunset\n\u{2022} Located at the Base of Blue Mountain we are an ideal hub to enjoy what the local area has to offer. Hike the Bruce Trail, bike the Georgian Trail, visit the Blue Mountain Village or use your vehicle permit to gain free access to Wasaga Beach Provincial Park (the longest freshwater beach in the world)\n\u{2022} Camping experience for everyone: RVs or tents\n\u{2022} Host your next family function while overlooking Georgian Bay at our Picnic Shelter; call the park office to reserve.",
                      general: "\u{2022} Phone: (705) 445-4467\n\u{2022} Size: 65.69 ha\n\u{2022} Year established: 1967\n\u{2022} Park Classification: Recreational\n\u{2022} Address:\n\t209403 Highway 26\n\tBlue Mountains, ON\n\tL9Y 0T6",
                      camping: [0: (heading: "\(cCar)", detail: "All of Craigleith’s campsites are accessible by car. There are four comfort stations located throughout the park so all campsites are within a short distance of one. Two of our comfort stations offer shower facilities and one offers laundry facilities. \n\nArea A contains non-electrical sites that are ideal for tents. This area also has a designated dog beach at the west end of the park and a comfort station with flush toilets, showers, laundry facitlities and a water tap. \n\nArea B contains both electrical and non-electrical sites that are ideal for both tents and trailers. This area is close to the Area A comfort station and also has another mini-comfort station one that offers flush toilets and showers. \n\nArea C is made up of both electrical and non-electrical sites that are all radio free. The non-electrical sites are ideal for tents or small trailers. The electrical sites are ideal for trailers and RVs. This area also has a comfort station, trailer filling and dumping station, playground, volleyball court, horseshoe pits and playing field. \n\nArea D is primarily made up of electrical sites with only two non-electrical sites. Most of the electrical sites have water hook-up which makes this area ideal for trailers and RVs. This area is radio-free and has one comfort station and the day-use area which is located at the east end."), 1: (heading: "\(cRad)", detail: "Areas C and D, which offer both electrical and non-electrical sites provide radio-free camping.")],
                      activities: [0: (heading: "\(aBik)", detail: "Bike on the park roads or the Georgian Trail located just outside of the park. A nice flat, stone chip trail runs from Meaford to Collingwood. \n\nFor downhill and cross-country skiing as well as road riders you can visit the park store for the most up to date information on trails."), 1: (heading: "\(aBrd)", detail: "Craigleith is home to a variety of songbirds, raptors and waterfowl. Visitors often see chickadees, juncos, nuthatches, cardinals, Blue Jays, robins, finches and hummingbirds."), 2: (heading: "\(aCan)", detail: "Craigleith’s shores are ideal to take the canoe out but be very cautious of the big water and its ability to change suddenly. For a relaxing adventure visit the local Beaver River which offers two, four and six hours of canoeing, beginning in Kimberley in the heart of the Beaver Valley. Shuttle service and canoe rentals are available in the village of Heathcote which is where the canoe route ends."), 3: (heading: "\(aFsh)", detail: "Craigleith is famous for its spring and fall offshore fishing. Cast your line and you may catch a Rainbow Trout, Salmon or even a Whitefish. Another great fishing area close by is the Beaver River; the mouth of the river is located 10 minutes outside of the park in the town of Thornbury."), 4: (heading: "\(aHik)", detail: "There are no designated hiking trails within the park but lots of opportunity for hiking all around the park; many within walking distance and many more within a short drive. Craigleith is a perfect hub for what the local area has to offer. Located at the Base of Blue Mountain and the Niagara Escarpment the opportunities are endless. The Georgian Trail is located directly across the highway from the park entrance and is an excellent biking and easy hiking trail. It runs along the highway all the way to Meaford and Collingwood. For intermediate to advanced hiking the Bruce Trail offers a variety of different experiences from spectacular views of Georgian Bay, The Niagara Escarpment and The Beaver Valley, rolling countryside, crevice caves and falling rivers and creeks over a tumbling landscape. These hikes all start within a fifteen minute drive of the park and trail maps and information are available at the park store."), 5: (heading: "\(aNHE)", detail: "Craigleith offers one program a week in the summer months. Refer to the Park Tabloid, online or inquire at the Park Store for details.")],
                      facilities: [0: (heading: "\(fBF)", detail: "Available at all comfort stations and the showers in Area B."), 1: (heading: "\(fCS)", detail: "Comfort stations are located in each campground Area. Area A comfort station has full washrooms, showers and laundry and also has a water tap on the outside of the building. Area B contains full washrooms and showers. Areas C & D have full washrooms."), 2: (heading: "\(fDU)", detail: "We have a designated day-use area at the east end of Craigleith. This area provides picnic tables, campfire pits, BBQs, access to the waterfront and a designated parking area."), 3: (heading: "\(fFT)", detail: "Flush toilets are found in all of our comfort stations."), 4: (heading: "\(fL)", detail: "Laundry facilities are located in our comfort station in Area A and laundry soap and fabric softener are sold in the park store."), 5: (heading: "\(fPSt)", detail: "Craigleith’s store is combined with our gatehouse. The store carries a variety of convenience and necessity items, groceries, firewood, treats, ice, ice cream, slushies, pop, snacks, souvenirs, Bruce Trail Guides and Nature Books. The store also carries freshly brewed coffee/hot chocolate and a free book and movie exchange. It is a one stop shop where you can register for your site, purchase your s’mores kit, firewood, sweatshirt and coffee and then borrow a book to relax with on the waterfront. The park store is located at the park entrance where you register for your campsite."), 6: (heading: "\(fPSh)", detail: "There is one picnic shelter in the park which is located in the day-use area. The shelter can be reserved for $50.00 for a full day or $25.00 for a half day for functions. Contact the Park Office at 705-445-4467 to reserve the shelter."), 7: (heading: "\(fR)", detail: "Personal Floatation Devices (PFDs) are available with a $60 refundable deposit. A variety of sports equipment is also available for rent (i.e. volleyballs, horseshoes).")])
