//
//  Driftwood.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let driftwood = Park(name: "driftwood",
                     about: "\u{2022} Waterfront campsites on the Ottawa River\n\u{2022} Panoramic views of the scenic Upper Ottawa Valley and Laurentian Hills\n\u{2022} Beautiful sunsets\n\u{2022} Peaceful, family-oriented setting\n\u{2022} Ideal base camp for exploring this section of the Ottawa River and the mouth of the Dumoine river by sea-kayak\n\u{2022} Large sandy beach",
                     general: "\u{2022} Phone: (613) 586-2553\n\u{2022} Size: 422.30 ha\n\u{2022} Year established: 1963\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t39520 Highway 17\n\tStonecliffe\n\tK0J 2K0",
                     camping: [0: (heading: "\(cCar)", detail: "Ottawa Campground is the larger campground with two thirds of the park’s campsites located here. There is a full-service, barrier-free comfort station that includes showers, flush toilets and laundry facilities. Many of the campsites are waterfront. All campsites are non-electrical and have a picnic table and fire ring. \n\nAll campsites in Brumm Campground are electrical and are geared toward larger trailer units and RVs. Pull-through campsites are available and each site has a picnic table and fire ring."), 1: (heading: "\(cGrp)", detail: "Two group campsites are available to larger, organized groups. The sites may be reserved by contacting the park directly at (613) 586-2553")],
                     activities: [0: (heading: "\(aBik)", detail: "Biking is a popular activity on the main park roads."), 1: (heading: "\(aBrd)", detail: "A variety of songbirds that use the adjacent waterway are regularly sighted in the park. Keep an eye out and an ear open for the many species of brightly coloured warblers that nest in the park."), 2: (heading: "\(aBtg)", detail: "The Ottawa River is well renowned for boating and other water-based recreational activities."), 3: (heading: "\(aCan)", detail: "The park is located on the Ottawa River directly across from the mouth of the Dumoine River, which is a popular wilderness canoe route, making the park a good place to camp before and after yo6r trip. Calm days provide great opportunities for exploration. \n\nA number of canoe routes are also found in Algonquin Provincial Park which provides good day trips from Driftwood."), 4: (heading: "\(aFsh)", detail: "You can fish for Walleye, Northern Pike and Small-mouth Bass in the Ottawa River. Nearby lakes are stocked with Splake, Lake and Brook Trout. The Dumoine River on the Quebec side of the Ottawa River, directly across from the park, is known for its excellent Walleye fishing. (Don’t forget to buy a Quebec fishing licence!)"), 5: (heading: "\(aHik)", detail: "\u{2022} The Oak Highland Trails: 1 km Riverview Loop and 2.5 km Beaver Pond Loop; moderate \n\tThis trail climbs steeply to a lookout with a panoramic view of the Ottawa River. \n\n\u{2022} The Chevrier Creek Trails: \n\t4 loops vary in range from 1.3 – 3.7 km loop; moderate"), 6: (heading: "\(aSwm)", detail: "The refreshing, cool, clear waters of the Ottawa River provide a relaxing way to spend a warm summer day. A sandy camper’s beach stretches the entire length of the Ottawa Campground adjacent to many of the campsites. A separate day-use area provides a smaller, more private sand beach. A free Personal Floatation Device (PFD) loan program is provided at the park office.")],
                     facilities: [0: (heading: "\(fBF)", detail: "A barrier-free site is located beside the comfort station in Ottawa East Campground and can be reserved through the Ontario Parks central reservation service."), 1: (heading: "\(fBL)", detail: "A boat launch and small docking facility is provided for access to the Ottawa River."), 2: (heading: "\(fCS)", detail: "The comfort station, located in the Ottawa East Campground is a modern facility with showers, flush toilets and laundry facilities."), 3: (heading: "\(fDU)", detail: "The day-use area provides a small sand beach and grassed picnic area on the shores of the Ottawa River."), 4: (heading: "\(fFT)", detail: "Both the comfort station and small washrooms located throughout the campground contain flush toilets."), 5: (heading: "\(fL)", detail: "A coin operated washer and dryer is located at the comfort station."), 6: (heading: "\(fPSt)", detail: "Canoe rentals, ice, firewood and a selection of souvenir merchandise can be purchased at the park store."), 7: (heading: "\(fR)", detail: "Rental canoes are conveniently located in the campground and day-use area on the shores of the Ottawa River. Rentals include Personal Floatation Devices (PFDs), paddles and a boat safety kit. \n\nA motorboat is also available for rent.  Arrangements for rentals can be made at the park office.")])
