//
//  Fairbank.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let fairbank = Park(name: "fairbank",
                    about: "\u{2022} Spring-fed Fairbank Lake, is crystal clear with great swimming at the buoyed sandy beach.\n\u{2022} Family oriented with waterfront campsites, located near Sudbury.\n\u{2022} Popular outdoor destination in the region for over 50 years!\n\u{2022} Interesting geology linked to its location on the very edge of the Sudbury Basin – a huge crater produced by a meteorite strike over a billion years ago.",
                    general: "\u{2022} Phone: 705-866-0530\n\u{2022} Size: 105.22 ha\n\u{2022} Year established: 1957\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\tP.O. Box 560, c/o Windy Lake Provincial Park\n\tLevack, ON\n\tP0M 2C0",
                    camping: [0: (heading: "\(cCar)", detail: "Campsites include a picnic table, fireplace and nearby amenities.  Many are located along the waterfront and 25% are electrical sites."), 1: (heading: "\(cGrp)", detail: "Fairbank Provincial Park provides a beautiful and isolated group camping area.  Located just before the campground, and a short walk to the beach, the site comes with a horseshoe pit, fire pit, water tap and bathrooms.  The site will accommodate four to six small trailers and five to ten tents. Group camping reservations can be made at the park gatehouse or by contacting the park directly at 705-866-0530.")],
                    activities: [0: (heading: "\(aBrd)", detail: "Fairbank isn’t known for any rare species or significant migrations, but it does have a wide variety of birds. The typical residents of the northern forests make Fairbank their home: woodpeckers, warblers, loons and ducks."), 1: (heading: "\(aBtg)", detail: "Boating is a popular summer activity."), 2: (heading: "\(aCan)", detail: "Fairbank Lake is a popular boating destination in the Sudbury Area for canoeing and kayaking."), 3: (heading: "\(aFsh)", detail: "Fairbank Lake is a favourite of anglers looking to reel in Smallmouth Bass and Lake Trout."), 4: (heading: "\(aHik)", detail: "\u{2022} Wa-Shai-Ga-Mog Rating: Easy - Length: 0.5 km, 30 minutes\n\t Wa-Shai-Ga-Mog is the original name of Fairbank Lake and is the Ojibway word for “clear water”. A fitting name for a lake where it is possible to see for over 8 m (24 feet) into the spring fed lake. This short but challenging trail travels up bedrock outcrops and provides panoramic views of the surrounding forests, the Fairbank Fault and of course the beautiful blue waters of Fairbank Lake. Be sure to bring your camera!"), 5: (heading: "\(aSwm)", detail: "The crystal clear waters attract visitors from all over the region for snorkelling and swimming. Families can swim safely in a buoyed area at the long sandy beach. Please note: lifeguards are not posted on the beach.")],
                    facilities: [0: (heading: "\(fBF)", detail: "Fairbank has one barrier-free campsite."), 1: (heading: "\(fBL)", detail: "Fairbank features a large cement boat launch, dock and parking lot."), 2: (heading: "\(fCS)", detail: "Fairbank has a large comfort station in the campground which features flush toilets, hot showers, sinks, change tables and laundry facilities."), 3: (heading: "\(fDU)", detail: "The picnic grounds feature a picnic shelter and a playground. \n\nThe crystal clear waters attract visitors from all over the region with snorkelling, swimming, fishing and boating being popular summer activities"), 4: (heading: "\(fFT)", detail: "Flush toilets are located in the campground comfort station."), 5: (heading: "\(fL)", detail: "Laundry facilities are located in the campground comfort station."), 6: (heading: "\(fPSt)", detail: "Ontario Parks merchandise is available in the gatehouse."), 7: (heading: "\(fPEA)", detail: "Pet exercise Area is located at the boat launch."), 8: (heading: "\(fPSh)", detail: "There is one picnic shelter in the park."), 9: (heading: "\(fR)", detail: "Fairbank offers canoe rentals.")])
