//
//  Fitzroy.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let fitzroy = Park(name: "fitzroy",
                   about: "\u{2022} Great family camping park with large campsites; swim, hike or relax by the beach\n\u{2022} Stay at the park and explore the Ottawa Valley or visit the nation’s capital - only one hour away\n\u{2022} Located at the junction of the meandering Carp River and the mighty Ottawa River\n\u{2022} See century-old White Pine forest and a stand of 200-year-old Bur Oak",
                   general: "\u{2022} Phone: 613-623-5159\n\u{2022} Size: 198.40 ha\n\u{2022} Year established: 1963\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t5201 Canon Smith Drive\n\tFitzroy Harbour\n\tK0A 1X0",
                   camping: [0: (heading: "\(cCar)", detail: "Fitzroy has over 200 campsites in two campgrounds; Pine Grove and Two Rivers. Waterfront campsites are available on the Carp and Ottawa Rivers which bisect the park. Some electrical sites are available in each campground. Amenities such as water taps, comfort stations and laundry facilities are located centrally in each campground. Two Rivers Campground has a small beach which is great for families with small children."), 1: (heading: "\(cGrp)", detail: "Fitzroy has six large group campsites that can accommodate 50 to 100 visitors, depending on equipment. These sites are ideal for youth groups and families. Vault toilets and water taps are located throughout this area. \n\nReservations are required and can be made, starting the first Monday in April, by calling the park directly: 613-623-5159.")],
                   activities: [0: (heading: "\(aBrd)", detail: "The park offers ample opportunities for birders to see killdeer, flickers, warblers, goldfinches. The annual fall migration of geese and ducks is also popular."), 1: (heading: "\(aBtg)", detail: "There is a small boat launch into the Ottawa River that can accommodate small fishing boats, canoes and kayaks. This facility is influenced by fluctuating water levels in the river."), 2: (heading: "\(aCan)", detail: "Paddlers can explore the Ottawa River and its shoreline around the park. Visitors can bring their own canoe/kayak or rent one from the park store."), 3: (heading: "\(aFsh)", detail: "The Ottawa River provides excellent fishing opportunities for walleye, pike, bass and panfish. Cast your line at the park dock, along the shoreline or near Butternut Island where the Ottawa and Carp rivers meet."), 4: (heading: "\(aHik)", detail: "\u{2022} Carp Trail, 1 km, easy \n\tFollow the banks of the Carp River through a mature forest. \n\n\u{2022} Terraces Trail - 2 km, moderate \n\tThis trail takes visitors along a geological journey. See shale pillars that stand as testaments to the erosive power of water and fields that are strewn with erratics - massive boulders left by glaciers."), 5: (heading: "\(aSwm)", detail: "There are two beaches in the park. The main beach is located in the day-use area with ample parking and a comfort station. The camper’s beach is located in Two Rivers Campground and is ideal for families with small children."), 6: (heading: "\(aWA)", detail: "Fitzroy, in partnership with West Carleton Nordic Ski Club, provides 20 km of groomed cross-country ski trails for traditional and skate skiing.")],
                   facilities: [0: (heading: "\(fBF)", detail: "All comfort stations offer barrier-free access. There is also a wheelchair ramp at the day-use area."), 1: (heading: "\(fBL)", detail: "There is a small boat launch into the Ottawa River that can accommodate small fishing boats, canoes and kayaks. This facility is influenced by fluctuating water levels in the river."), 2: (heading: "\(fCS)", detail: "Both the Pine Grove and Two Rivers Campgrounds have a centrally located comfort station with flush toilets and showers."), 3: (heading: "\(fDU)", detail: "Fitzroy offers a large day-use area for swimming, picnicking and canoeing, along with a volleyball court. The park has three large separate picnic areas with a group barbecue. Reservations are required. Please call the park directly at 613-623-5159."), 4: (heading: "\(fFT)", detail: "Flush toilets are located at the comfort stations in each campground and at the day-use area beach."), 5: (heading: "\(fL)", detail: "Laundry facilities are available at the comfort stations located centrally in each campground."), 6: (heading: "\(fPSt)", detail: "The park store offers groceries, snacks, camping supplies, souvenirs and every kid’s favourite - ice cream. Campers can also purchase firewood or rent canoes and kayaks at the park store."), 7: (heading: "\(fR)", detail: "Canoe/kayak rentals are available at the park store.")])
