//
//  Fushimi.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let fushimi = Park(name: "fushimi lake",
                   about: "\u{2022} A clean, clear northern lake, surrounded by lush Boreal Forest\n\u{2022} Camping experience for everyone: RV, tent or trailer sites, or backcountry sites on your own island.\n\u{2022} Excellent Walleye, Northern Pike and Yellow Perch fishing.\n\u{2022} Boat launch and fish cleaning station\n\u{2022} Two great hiking trails; one trail leads to a fire tower\n\u{2022} Excellent wildlife viewing",
                   general: "\u{2022} Phone: 705-372-5909\n\u{2022} Size: 5294.00 ha\n\u{2022} Year established: 1979\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\tPO BOX 670, 613 Front Street\n\tHearst\n\tP0L 1NO",
                   camping: [0: (heading: "\(cBac)", detail: "Thirteen interior campsites are located on the shores of Fushimi Lake. The sites are away from the campground and some are on their own private island. All sites are accessible by water and can only be reached by canoe or motorboat. Each site has a tent pad, fire pit and outhouse."), 1: (heading: "\(cCar)", detail: "The Park’s campsites are quite secluded and almost all have electrical service. They are a convenient distance to hot showers, laundromat and flush toilets. Seasonal camping is also available."), 2: (heading: "\(cGrp)", detail: "One group campsite is located close to the beach and boat launch and a two minute walk from the comfort station. It can accommodate six trailers (or several tents) and approximately 40-50 people. Vault toilets and water taps are located on site. Reservations can be made by calling the park directly at 705-372-5909"), 3: (heading: "\(cRof)", detail: "Please see website for most up to date information regarding roofed accommodations.")],
                   activities: [0: (heading: "\(aBik)", detail: "Biking is available on park roads."), 1: (heading: "\(aBrd)", detail: "Fushimi Lake lies within the vast Boreal Forest region. This is often called the songbird nursery, as hundreds of bird species nest here each summer. Warblers are the most colourful and have the prettiest songs, but many other birds can be heard and seen, including woodpeckers, ducks, finches and flycatchers, as well as fishing birds like Great Blue Herons, Ospreys and Bald Eagles."), 2: (heading: "\(aBtg)", detail: "The boat launch is located near the campground. After launching, boats can be loaded at the dock, and beached on our sandy shore overnight."), 3: (heading: "\(aCan)", detail: "There are excellent canoeing opportunities on Fushimi Lake. The lake has many bays and coves and the sections of the Valentine River, at either end of the lake, are also worth exploring. Keep an eye out for wildlife."), 4: (heading: "\(aFsh)", detail: "Fish for Walleye, Northern Pike, Lake Whitefish and Yellow Perch in Fushimi Lake and Valentine River. You can then clean your catch at the fish cleaning hut next to the boat launch."), 5: (heading: "\(aHik)", detail: "\u{2022} Achilles Lake Trail - 1 km return (45 minutes) easy. \n\tThis trail leads to the shore of Achilles Lake, a small lake on the north side of the campground. The lake is a popular spot for watching sunsets. There is a canoe rental at the end of this trail so you can paddle and try your luck at catching Walleye and Northern Pike. \n\n\u{2022} Fire Tower Trail 7 km return (2 hours) strenuous.  \n\tThis trail takes you to one of the few original fire lookout towers left in Ontario. The Bannerman Fire Tower was erected in the 1930s and the ranger in charge of the tower, watched for smoke and lived in a cabin nearby with his family through the summer. Along the shores of Fushimi Lake there are a few great spots for lunch and a swim."), 6: (heading: "\(aHnt)", detail: "Hunting in this park is subject to the Ontario Hunting Regulations. Certain restrictions apply. For more information, contact the park or your local area or district office of the Ministry of Natural Resources."), 7: (heading: "\(aSwm)", detail: "The sandy beach, shallow, clear water and buoyed swimming area next to the campground are perfect for family swimming. There are change facilities. There is a full size sand volleyball court at the Day-Use Area, another beach and a place to play horseshoes.")],
                   facilities: [0: (heading: "\(fBF)", detail: "The comfort station is barrier-free, including showers, and we offer a barrier-free campsite in the nearby campground."), 1: (heading: "\(fBL)", detail: "There is lots of room to launch your boat – docking is temporary, for loading and unloading. Parking is located nearby for vehicles and boat trailers."), 2: (heading: "\(fCS)", detail: "The campground comfort station has flush toilets, mirrors, sinks, hand sanitizer, hand dryers and showers."), 3: (heading: "\(fDU)", detail: "Our day-use area offers lots of room for family picnics with shaded areas along the shore and access to the sandy day-use beach."), 4: (heading: "\(fFT)", detail: "The main comfort station and all outhouses have flush toilets, sinks, mirrors, and hand sanitizer."), 5: (heading: "\(fL)", detail: "There are washers and dryers, and a laundry tub at the comfort station, as well as a laundry soap dispenser with detergents for sale."), 6: (heading: "\(fPSt)", detail: "The Park Store is found in the Main Gate House. A variety of supplies are available, from key needs like ice, bug spray and suntan lotion, to coffee, ice cream and candy. You will also find a variety of Ontario Parks merchandise for the whole family."), 7: (heading: "\(fR)", detail: "We rent motorboats, canoes, kayaks, peddle boats and bikes.")])
