//
//  Inverhuron.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let inverhuron = Park(name: "inverhuron",
                      about: "\u{2022} Prized for its sandy beach, dunes and glorious sunsets.\n\u{2022} Includes a wetland and a young hardwood forest\n\u{2022} Diverse habitat nutures rare plants and protects many woodland animals and birds.\n\u{2022} Steeped in history. First Nations people lived here for thousands of years. In the 1800s a small town was established in what is now part of the park.",
                      general: "\u{2022} Phone: 519-368-1959\n\u{2022} Size: 288.10 ha\n\u{2022} Year established: 1967\n\u{2022} Park Classification: Cultural Heritage \n\u{2022} Address:\n\t19 Jordon Rd., RR#2\n\tTiverton, ON\n\tN0G 2T0",
                      camping: [0: (heading: "\(cCar)", detail: "Inverhuron has two campgrounds with a range of features including electrical service and pull-through sites ideal for larger RVs. The campsites are well separated and private. All sites are treed, spacious and have a level surface making them ideal for larger trailers. The large private sites may mean that you need to bring an extra long extension cord to reach the electrical outlet. All sites are conveniently located close to the comfort stations and showers. \n\nNote: Campers sensitive to Poison Ivy should be aware that it grows naturally throughout the park."), 1: (heading: "\(cGrp)", detail: "Group campsites are available. To reserve, please call 1-888-ONT-PARK (1-888-668-7275) or 1-519-826-5290 outside of North America.")],
                      activities: [0: (heading: "\(aBik)", detail: "There is a shared-use trail in the park and cycling on all park roads."), 1: (heading: "\(aBrd)", detail: "Self-guided opportunities, best during spring and fall migrations."), 2: (heading: "\(aBtg)", detail: "There is access to Lake Huron via a boat launch in the park."), 3: (heading: "\(aCan)", detail: "Caution should be used by anyone canoeing or kayaking along the shore of Lake Huron as water conditions can quickly change. The nearby Saugeen River provides excellent canoeing and kayaking opportunities."), 4: (heading: "\(aFsh)", detail: "A good spot to fish for Lake Trout, bass, pickerel, perch, salmon, pike."), 5: (heading: "\(aHik)", detail: "There is a shared-use trail in the park."), 6: (heading: "\(aNHE)", detail: "The Natural Heritage program at Inverhuron Provincial Park consists of programs for all ages. All through the week, there are a wide variety of children’s programs, evening programs, special events and guided hikes that allow campers to learn about the natural features of the park as well as its vast cultural history. Weekly program notices are posted throughout the park as well online. \n\nFor additional information on programs visit the parks twitter page."), 7: (heading: "\(aSwm)", detail: "The park is well-known for the clear waters of its shallow, sandy beach – ideal for swimming. Sections of the 1 km beach are buoyed and change facilities are available."), 8: (heading: "\(aWA)", detail: "The park is gated during the winter.")],
                      facilities: [0: (heading: "\(fBF)", detail: "Designated campsites, showers and flush toilets."), 1: (heading: "\(fBL)", detail: "There is a boat launch ramp available in the park."), 2: (heading: "\(fCS)", detail: "Comfort stations are centrally located in each of the three campgrounds as well as the day-use area. Showers are offered in the Gunn Point, Lime Kiln and Holmes Bay Campground comfort stations."), 3: (heading: "\(fDU)", detail: "A large day-use area with picnic shelter and a beautiful sandy beach.  Change rooms and a comfort station are located in the day-use area."), 4: (heading: "\(fFT)", detail: "Flush toilets are located at the comfort stations which are centrally located in each of the three campgrounds as well as at the day-use area."), 5: (heading: "\(fL)", detail: "Laundry facilities are located in the Gunn Point, Lime Kiln and Holmes Bay Campground comfort stations."), 6: (heading: "\(fPEA)", detail: "There is a designated dog beach."), 7: (heading: "\(fPSt)", detail: "A picnic shelter is available in the day-use area."), 8: (heading: "\(fR)", detail: "Trailer Storage: Available during the operating season. \n\nPersonal Floatation devices (PFDs): Available at the Registration Office. For a refundable deposit, you can borrow a properly fitted PFD. \n\nExtension Cord Loan Service: For a refundable deposit, you are able to borrow extension cords. Electrical pedestals are at times a distance from the site and may require cords that are longer than some people might bring.")])
