//
//  Kawartha.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let kawartha = Park(name: "kawartha highlands",
                    about: "\u{2022} Largest park in Ontario, south of Algonquin Provincial Park\n\u{2022} Enjoy solitude, tranquility and dark night skies in this newly established park\n\u{2022} Wide variety of canoe camping and backcountry experiences\n\u{2022} Rugged rolling landscape of small lakes, wetlands, forests and rocky barrens\n\u{2022} Great wildlife viewing opportunities and a large diversity of species\n\u{2022} In the spring, beat the summer rush and see this unique landscape come to life",
                    general: "\u{2022} Phone: 613-332-3940 ext. 261\n\u{2022} Size: 37587.00 ha\n\u{2022} Year established: 1989\n\u{2022} Park Classification: Natural Environment \n\u{2022} Address:\n\t106 Monck Street,  Box 500\n\tBancroft, ON\n\tK0L 1C0", camping: [0: (heading: "\(cBac)", detail: "Kawartha Highlands Provincial Park has over 100 backcountry campsites spread over six recommended loops. Most sites have three tent pads, a designated fire ring, a picnic table and a privy toilet. Campsites can only be reached by canoe and most require portaging to access them; there are no car campsites in the park. \n\nPlan Ahead \n\n\u{2022} \n\tPlan your route and learn the park regulations. Let someone know what your travel plans are and when you plan to be back. Whenever possible, schedule your trip to avoid times of high use. \n\tBring proper clothing and equipment - including a map, compass and first aid kit. Prepare for extreme weather, hazards and emergencies. \n\tPack food in reusable, leak-proof containers to minimize waste. \n\tCamp only on designated sites. Keep your group to nine people or less."), 1: (heading: "\(cRad)", detail: "To maintain the wilderness atmosphere of Kawartha Highlands, the use of amplified stereo devices is prohibited throughout the park.")],
                    activities: [0: (heading: "\(aBrd)", detail: "Watch for Common Loons, Great Blue Herons and Osprey on park lakes. The park’s rock barrens attract a number of bird species including Whip-poor-will, Common Nighthawk, Scarlet Tanager and Eastern Towhee.  Many species of warblers, vireos and sparrows are found in the park as well."), 1: (heading: "\(aBtg)", detail: "Motorboats are permitted on most lakes within the park. Check with the Park Office for more information."), 2: (heading: "\(aCan)", detail: "Kawartha Highlands provides a taste of wilderness canoeing, close to southern Ontario. There are six recommended canoe routes through the park, ranging from easy to moderate in difficulty. A canoe route map is available for sale from the park office."), 3: (heading: "\(aFsh)", detail: "Try your luck for bass, walleye, panfish and trout. Note: The use and possession of live baitfish is prohibited in the park."), 4: (heading: "\(aHnt)", detail: "Hunting in this park is subject to the Ontario Hunting Regulations. Certain restrictions apply. For more information, contact the park or your local area or district office of the Ministry of Natural Resources."), 5: (heading: "\(aSwm)", detail: "The many clear lakes of Kawartha Highlands provide great opportunities for swimming at campsites and throughout the park."), 6: (heading: "\(aWA)", detail: "Winter camping is allowed and you must obtain a permit by calling 1-888-668-7275 or online at https://reservations.ontarioparks.com. Please note that although you have made a reservation for a designated campsite, you are required to camp at least 30 metres away from any designated campsite, shoreline, trail or portage between December 1 and March 31. \n\nWe recommend that you camp in low sheltered areas where there is a good supply of standing dead firewood for warmth and cooking.")],
                    facilities: [0: (heading: "\(fBL)", detail: "Boat launches for small vessels exist at the following access points: Anstruther, Wolf, Loon Call and Long Lakes."), 1: (heading: "\(fDU)", detail: "Kawartha Highlands offers many options for those who want to paddle for the day.  During your day trip you can enjoy a shore lunch and swim at a scenic lakeside spot.  There are limited day-use facilities at a few of the access points.")])
