//
//  Kettle.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let kettle = Park(name: "kettle lakes",
                  about: "\u{2022} Twenty-two deep, spring-fed kettle lakes formed by glaciers\n\u{2022} Primarily Jack Pine Boreal Forest, with great blueberry picking in August.\n\u{2022} Many lakes are stocked with Rainbow and Brook Trout for excellent fishing.\n\u{2022} Fourteen kilometers of biking trails.\n\u{2022} Interpretive programs for the whole family.",
                  general: "\u{2022} Phone:\n\u{2022} 705-363-3511 (summer)\n\u{2022} 705-272-7107 (winter)\n\u{2022} Size: 1260.79 ha\n\u{2022} Year established: 1957\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t1350 Municipal Road\n\tConnaught, ON\n\tP0N 1H0",
                  camping: [0: (heading: "\(cCar)", detail: "Kettle Lakes offers car camping in two campgrounds: The Pines and Island Lake. Both campgrounds can accommodate equipment ranging from tents to large trailers. Many campsites offer electrical hook-up. Amenities such as water taps, comfort stations with hot water, showers and laundry facilities are close by. Swimming is available at Island Lake adjacent to the campground. Swimming is also available at Slab Lake a few minutes from The Pines Campground."), 1: (heading: "\(cGrp)", detail: "A large group camping site is available very close to Slab Lake.  This secluded area is great for family reunions or just hanging out with a group of friends.")],
                  activities: [0: (heading: "\(aBik)", detail: "Kettle Lakes has 14 kilometres of biking trails ranging from easy to moderate levels of difficulty. The trails wind through the forest and lead you to Slab Lake where you can have a swim before continuing your journey. Bicycles are available for rent at the front gate."), 1: (heading: "\(aBrd)", detail: "Kettle Lakes is part of the great expanse of the Boreal Forest that covers northern Ontario. The variety of tree species in the park creates a great habitat for a range of birds from: woodpeckers, grouse, warblers, loons to a variety of waterfowl. The park is home to these birds while they nest and raise their young."), 2: (heading: "\(aBtg)", detail: "Power boats are permitted on Hughes Lake only."), 3: (heading: "\(aCan)", detail: "Canoe rentals are available including paddles and life jackets."), 4: (heading: "\(aFsh)", detail: "Many of the 22 lakes within the park are stocked with Rainbow and Brook Trout. Northern Pike and Yellow Perch occur naturally within some of the lakes in the park."), 5: (heading: "\(aHik)", detail: "Kettle Lakes Provincial Park has four different hiking trails: \n\n\u{2022} Kettle Trail, 2 km, one hour, moderate \n\tThis trail leads you along an esker (an ancient glacial riverbed) and passes bogs that occupy some of the kettle depressions. \n\n\u{2022} Tamarack Trail, 2 km, one hour, easy \n\tFollow this picturesque trail around Tamarack Lake. \n\n\u{2022} Wintergreen Trail, 1.5 km, one hour, moderate \n\tHikers are rewarded with beautiful views of Island Lake. \n\n\u{2022} Oh-Say-Ya-Wah-Kaw Trail, 3 km, one hour moderate"), 6: (heading: "\(aNHE)", detail: "Our Natural Heritage Education staff keep campers busy learning new things and having fun!  Interpretive programs include guided hikes, evening programs and children’s programs. The park’s small Visitor Centre is open most days in the summer, where campers can see displays and chat with the park naturalists."), 7: (heading: "\(aSwm)", detail: "Two main beach areas are located on Island Lake and Slab Lake. A playground is found at Slab Lake.")],
                  facilities: [0: (heading: "\(fBF)", detail: "Barrier-free access is available at the Visitor Centre as well as two campsites which are specifically designed as barrier-free."), 1: (heading: "\(fBL)", detail: "A boat launch is available at Hughes Lake."), 2: (heading: "\(fCS)", detail: "There is one full-sized comfort station available in the Island Lake Campground which includes hot showers, laundry facilities and flush toilets. There is also a mini comfort station with flush toilets and hot water on the west side of the campground."), 3: (heading: "\(fDU)", detail: "The Slab Lake Day-Use area is a popular place for a nice summer swim.  A large playground is on site to entertain the little ones."), 4: (heading: "\(fFT)", detail: "Flush toilets are located in the Island Lake Campground comfort station."), 5: (heading: "\(fL)", detail: "Laundry facilities are available at the Island Lake Campground comfort station."), 6: (heading: "\(fPSt)", detail: "The Park Store is your one-stop shopping experience for all your camping needs. Located within the front gate, the store maintains a stock of ice, firewood, ice cream, Ontario Parks’ merchandise and other amenities."), 7: (heading: "\(fPEA)", detail: "There is a pet exercise area at Spring Lake where your best friend can enjoy a swim in the lake."), 8: (heading: "\(fPSh)", detail: "A picnic shelter exists at Green Lake and Slab Lake. This is available to rent for special occasions."), 9: (heading: "\(fR)", detail: "Rentals are available for canoes and paddle boats (both come with PFDs), bicycles, and a picnic shelter. Trailer storage is available in the park. The park also has a Tackleshare program which lends out fishing rods and tackle to park visitors, free of charge."), 10: (heading: "\(fVC)", detail: "There is a Visitor Centre tucked away near the front gate which has interactive displays and is the central location for many Natural Heritage Education activities.")])
