//
//  Long.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let long = Park(name: "long point",
                about: "\u{2022} Fourth oldest Provincial Park in Ontario (Est. 1921)\n\u{2022} Over 1.5 km sandy beach on the warm waters of Lake Erie\n\u{2022} Excellent fishing and boating opportunities in Long Point Bay\n\u{2022} One of the largest bird and waterfowl migration and staging areas in North America\n\u{2022} Located within a designated World Biosphere Reserve",
                general: "\u{2022} Phone: 519-586-2133\n\u{2022} Size: 150.00 ha\n\u{2022} Year established: 1921\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\tPO Box 99 350 Erie Blvd\n\tPort Rowan, ON\n\tN0E 1M0",
                camping: [0: (heading: "\(cCar)", detail: "Long Point offers four campground areas in two sections of the park. Almost half of campsites have electrical service. \n\nThe section generally called “New Park” includes three of the campgrounds: Monarch’s Rest, Firefly and Turtle Dunes Campgrounds as well as the popular Day-Use area. \n\nFirefly Campground offers large pull-through sites equipped with electrical service. Located on the bay side of the campground, they are a short five minute walk to the beach. \n\nMonarch’s Rest and Turtle Dunes Campgrounds offer some electrical sites that are able to accommodate a variety of equipment. The premium campsites, located in the dunes at the ends of the loops closest to the beach, offer a soft sandy base. \n\nThe Old Park section of Long Point includes Cottonwood Campground, a radio-free campground. The sites can accommodate a variety of equipment sizes. For 2012 this campground will feature a new barrier-free comfort station with showers. Premium campsites are located at the ends of the loops and are very close to the beach. We also have our first-come, first-served campsites available in Cottonwood Campground."), 1: (heading: "\(cRad)", detail: "Cottonwood Campground (Old Park) is a radio-free campground with a total of 81 campsites.")],
                activities: [0: (heading: "\(aBik)", detail: "Enjoy cycling on over 5 km of park roadways."), 1: (heading: "\(aBrd)", detail: "More than 300 different species of song birds and waterfowl migrate through Long Point every spring and autumn. More than 80 species of birds nest on the point annually, making Long Point one of the top bird watching destinations in North America. \n\nThe Long Point Bird Observatory is located just outside the park and Bird Studies Canada is located a short distance away in the village of Port Rowan."), 2: (heading: "\(aBtg)", detail: "Excellent boating opportunities are provided on Long Point Bay. The park offers boat launch facilities that are able to accommodate most pleasure boats."), 3: (heading: "\(aCan)", detail: "Many visitors enjoy canoeing along the sheltered marsh of Long Point Bay. Opportunities also exist outside of the park, in the area of Big Creek, located on the Long Point causeway."), 4: (heading: "\(aFsh)", detail: "There are excellent fishing opportunities in Long Point Bay. We have one of the finest bass fisheries in Ontario. Fishing licenses may be purchased in the village of Long Point."), 5: (heading: "\(aHnt)", detail: "The park is the home base for the Long Point Waterfowl Management Unit (LPWMU), a controlled waterfowl hunt. The LPWMU is open for hunting Monday, Wednesday, Friday and Saturday during the open season for waterfowl. (mid-September through to mid-December) \n\nInformation regarding the LPWMU may be obtained by calling the Park Office.\n Hunting does not take place on park property and hunting is not permitted within the park."), 6: (heading: "\(aNHE)", detail: "The park does not offer a formal NHE program but we do offer several exciting and informative programs throughout the season on topics such as Reptiles at Risk, Creatures of the Night and the Fowler’s Toad."), 7: (heading: "\(aSwm)", detail: "Large, sandy beaches are located by Monarch’s Rest and Turtle Dunes Campground and the Day-Use are in the New Park as well as Cottonwood Campground in the Old Park. Over two kilometres of soft sand and warm water awaits you. \n\nPlease note: There are no lifeguards posted and pets are only allowed in the designated pet exercise area. Lake Erie does have an undertow present so please be cautious while swimming.")],
                facilities: [0: (heading: "\(fBF)", detail: "All comfort stations, as well as the park store, provide barrier-free access. \n\nTwo barrier-free campsites are offered, one with electricity located in Firefly Campground and one without electricity in Cottonwood Campground."), 1: (heading: "\(fBL)", detail: "A boat launch is located in the New Park on Long Point Bay and can accommodate most pleasure boats. Use of the boat launch is included with your campsite or day-use permit."), 2: (heading: "\(fCS)", detail: "Comfort stations, complete with flush toilets and showers, are located in Turtle Dunes, Monarch’s Rest and Cottonwood Campgrounds. \n\nComfort stations are also located in the day-use area and they provide flush toilets."), 3: (heading: "\(fDU)", detail: "The well known and very popular day-use area is located in the New Park and is open daily until 10:00 p.m., with parking that will accommodate over 650 vehicles. Picnic areas are located adjacent to the parking lots, in close proximity to the beautiful sandy beach. Picnic tables and 12 upright barbeques are provided along with two comfort stations. \n\nThe swimming areas are not supervised by lifeguards – you are responsible for your own and your children’s safety."), 4: (heading: "\(fFT)", detail: "Flush toilets are found in each campground and in the day-use area."), 5: (heading: "\(fL)", detail: "A washer and dryer are located in Monarch’s Rest Campground. Laundromat facilities are also located in village of Port Rowan."), 6: (heading: "\(fPSt)", detail: "The Park Store is conveniently located at the Registration Office inside the entrance to the New Park. In addition to offering Ontario Parks’ merchandise, you will find a variety of souvenir clothing, camping supplies, activities to entertain young and old, snacks, Pepsi beverages, VanHoutte coffee and ice cream novelties. Firewood and ice are also available at this location. \n\nThe village of Long Point and town of Port Rowan are located nearby and offer groceries, hardware and many other supplies and services."), 7: (heading: "\(fPEA)", detail: "Long Point offers an off-leash dog exercise/beach area located at the west end of the day-use beach, in the New Park area. It is important to remember that dogs must be controlled by their owner at all times and must be kept on a leash at all times when in any other area of the park."), 8: (heading: "\(fR)", detail: "Extension cords 15 and 30 amp, are available at the Registration Office. Fees apply. \n\nPersonal Floatation Devices (PFDs) are available for loan with a refundable deposit. \n\nFishing rods are also available for loan through the Ontario Federation of Anglers and Hunters (OFAH) Tackleshare program. \n\nCanoe rentals are available outside of the park.")])
