//
//  MacLeod.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let macleod = Park(name: "macleod",
                   about: "\u{2022} Named after an abandoned gold mine, this park is located on a peninsula in Kenogamisis Lake\n\u{2022} The lake offers excellent swimming and walleye and pike fishing in its bays and marshes\n\u{2022} Look up at the sky on a clear summer night and you may see the northern lights\n\u{2022} Bird watch and view wildlife as the forest comes alive after a long, cold northern Ontario winter",
                   general: "\u{2022} Phone: (807) 854-0370\n\u{2022} Size: 74.06 ha\n\u{2022} Year established: 1963\n\u{2022} Park Classification: Recreational\n\u{2022} Address:\n\tMacLeod Provincial Park c/o Geraldton Community Forests Inc.\n\tBox 400\n\tGeraldton, ON\n\tP0T 1M0",
                   camping: [0: (heading: "\(cCar)", detail: "This quiet campground has 100 campsites, one quarter of which are electrical. Sites are available on a first-come, first-served basis and there is usually no problem with campsite availability. Campsites suit a range of equipment from tents, to trailers, to RVs. \n\nCampsites at this park are all well treed and many sites are located on a peninsula jutting out into the lake and they have their own shoreline."), 1: (heading: "\(cGrp)", detail: "MacLeod has one group camping area, isolated in the heart of nature, though in close proximity to the nature trail and the comfort station. The site lies just minutes from Kenogamisis Lake, making for beautiful scenery. Water and toilets (privies) are on site. Approximately 100 people can be accommodated on this site.  Reservations can be made by calling the park directly at (807) 854-0370.")],
                   activities: [0: (heading: "\(aBik)", detail: "Bicycles are a great way to explore the campground and are encouraged as a mode of transportation within the park. They are permitted on park roads but not on the trail system."), 1: (heading: "\(aBrd)", detail: "Visitors to MacLeod could expect to see Red-eyed Vireos, ovenbirds, Northern Warblers, Broad-winged Hawks and ospreys."), 2: (heading: "\(aBrd)", detail: "Bring your own boat and launch it from the park’s boat launch, or rent a boat from suppliers nearby. Explore the lake with its many inlets, bays, islands and marshes."), 3: (heading: "\(aCan)", detail: "Travelling by canoe is the perfect way to explore Kenogamisis Lake. Canoes can be rented from local outfitters near the park."), 4: (heading: "\(aFsh)", detail: "Cast a line for pike and walleye in Kenogamisis Lake and Kenogamisis River."), 5: (heading: "\(aHik)", detail: "\u{2022} MacLeod Trail - 1 km (30 minutes) easy \n\tThis trail passes through a forest of Trembling Aspen, the prominent tree in the park. Much of the original forest was destroyed by fire in 1939. A trail guide is available that explains forest succession."), 6: (heading: "\(aSwm)", detail: "The sandy beach is a popular attraction for day visitors and campers.")],
                   facilities: [0: (heading: "\(fBF)", detail: "The flush toilets and showers at the comfort station have barrier-free access."), 1: (heading: "\(fBL)", detail: "A boat launch is located in the day-use area of the park."), 2: (heading: "\(fCS)", detail: "The park has two comfort stations centrally located in the campground."), 3: (heading: "\(fDU)", detail: "Come for a swim at the beach and a picnic near the waterfront. MacLeod has a large day-use area with picnic tables, fire pits and grills. Water and toilet facilities are nearby."), 4: (heading: "\(fFT)", detail: "Flush toilets are available at each of the park’s comfort stations.")])
