//
//  Makobe.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let makobe = Park(name: "makobe grays river",
                  about: "\u{2022} The Makobe River is one of the wild whitewater rivers that flow from the headwaters contained in Lady Evelyn-Smoothwater Provincial Park.\n\u{2022} In the high water levels of spring and early summer, many of the numerous rapids may be run as Class I and ll by skilled whitewater paddlers, for a short but challenging trip.\n\u{2022} The Makobe River has cut a series of narrow canyons through shield bedrock as it flows northward from the height of land to the Montreal River.\n\u{2022} During summer, canoeing consists mainly of flatwater with some moving water, lining and numerous portages.\n\u{2022} This waterway park offers numerous small waterfalls, scenic ravines and fishing.",
                  general: "\u{2022} Phone: (705) 569-3205\n\u{2022} Size: 1427.00 ha\n\u{2022} Year established: 1985\n\u{2022} Park Classification: Waterway \n\u{2022} Address:\n\t24 Finlayson Park Road\n\tTemagami\n\tP0H 2H0",
                  camping: [0: (heading: "\(cBac)", detail: "When flying into Makobe Lake, the time required preparing for the flight, and the flight itself mean that camping on Banks Lake is the likely end to the first day. There are several campsites on Banks, including one where the Makobe River starts, next to the first falls. Alexander Lake has a number of campsites for the second night, although camping next to a rapid is often a great way to get to sleep. The last day ends at the Town of Elk Lake. \n\nPlease Note: Permits are required for all overnight backcountry camping.  For a list of best locations to obtain permits, please contact the park directly.")],
                  activities: [0: (heading: "\(aBrd)", detail: "Lady Evelyn-Smoothwater protects an area of rugged highland watersheds and contains forest that mixes Great Lakes-St. Lawrence and Boreal species of trees, creating many different habitats for birds. Makobe-Grays protects a similar although narrower forest, where many of the same species of birds can be seen. During the nesting season of spring and early summer, many species of warbler, thrush, flycatcher and woodpecker can be heard calling to defend territory. Eagles, osprey and many other birds of prey can be spotted hunting above the forests of the park. Keep an eye open for birds around the campsite in the morning and at the end of the day."), 1: (heading: "\(aBtg)", detail: "Motorboats are permitted on Alexander Lake only."), 2: (heading: "\(aCan)", detail: "Canoeists travelling the Makobe River come for challenging whitewater. The river itself is a short trip, two or three days of paddling if flying into Makobe Lake by floatplane, and taking-out at the Town of Elk Lake. \n\nThe rapids and drops along the river are technical and require scouting. Water conditions early in the season depend on the snowmelt and early trippers may encounter snowfall and even ice-bound lakes, after very cold winters. Lady Evelyn-Smoothwater and the Makobe River are higher in elevation than the surrounding areas, like Elk Lake and Temagami. A number of cliff-side locations retain ice and snow into late May. \n\nThe Makobe route can also be combined with other routes, primarily those of Lady Evelyn-Smoothwater where the Makobe River begins. The Grays River to the south connects to the Lady Evelyn River, and the Makobe flows into the Montreal River. These can be linked to Lady Evelyn Lake, forming a circle route but only when there are high water conditions."), 3: (heading: "\(aFsh)", detail: "Brook trout are the most abundant species on this river."), 4: (heading: "\(aHnt)", detail: "Hunting restrictions apply. Please refer to the Temagami Area Park Management Plan 2007 for zone specific management direction."), 5: (heading: "\(aSwm)", detail: "There are endless opportunities in the backcountry for swimming including both shallow and deeper water entries along rocky headlands.")],
                  facilities: [0: (heading: "\(fR)", detail: "Canoes and camping equipment can be rented from outfitters near the various park access points.")])
