//
//  Mara.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let mara = Park(name: "mara",
                about: "\u{2022} Approximately a 10 minute drive South of Orillia\n\u{2022} Beach located on the shores of Lake Simcoe\n\u{2022} 0.5 km nature trail\n\u{2022} A picnic shelter available for reservations\n\u{2022} Ice, firewood and novelty ice cream available at registration office\n\u{2022} Playground\n\u{2022} Restaurants, gas stations, convenience stores, boat rentals and shopping close by\n\u{2022} Within 15 minute drive of Casino Rama",
                general: "\u{2022} Phone: 705-326-4451\n\u{2022} Size: 45.25 ha\n\u{2022} Year established: 1970\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t181 Courtland Street\n\t\n\tRamara Township\n\tL3V 6H7",
                camping: [0: (heading: "\(cCar)", detail: "The park has car camping with both electrical and non-electrical campsites. Our campground has access to washrooms and a shower building. We also have two campsites that offer barrier- free access.")],
                activities: [0: (heading: "\(aBik)", detail: "Campers normally cycle on park roads."), 1: (heading: "\(aBrd)", detail: "Great Blue Heron, Green Heron, Coopers Hawk, Osprey"), 2: (heading: "\(aBtg)", detail: "Mara is on the shores of Lake Simcoe which has great fishing opportunities and also offers access to the Trent Severn Waterway."), 3: (heading: "\(aFsh)", detail: "Mara is on the shores of Lake Simcoe and has great fishing opportunities for sunfish, walleye, Lake Trout, Smallmouth Bass, perch and Lake Whitefish."), 4: (heading: "\(aHik)", detail: "Mara has a 0.5 kilometre trail which winds through a soft maple wetland and along a stream bank that is rich in flora and fauna. Look for Jack-in-the-Pulpits, Painted Turtles or a Great Blue Heron."), 5: (heading: "\(aSwm)", detail: "Mara is located on the shores of Lake Simcoe and prides itself on having one of the best beaches in Lake Country. A designated swimming area is available to park visitors from mid June through to Labour Day.")],
                facilities: [0: (heading: "\(fBF)", detail: "Barrier-free washrooms are available at both comfort stations and Mara has two electrical campsites (#39 and #40) with barrier-free access. These sites can be reserved by calling the Ontario Parks’ website and call centre."), 1: (heading: "\(fCS)", detail: "Mara offers one fully serviced comfort station with flush toilets and showers and one comfort station located at the day-use area with flush toilets only."), 2: (heading: "\(fDU)", detail: "During the summer months, our day-use area is open daily from 8:00 a.m. to 10:00 p.m. from the second Friday in May until Labour Day. No alcohol is permitted in our day-use area at any time, day or night.  If you are bringing pets, they must be leashed at all times, including during our off seasons and they are not permitted on the beach."), 3: (heading: "\(fFT)", detail: "Flush toilets are located in both comfort stations."), 4: (heading: "\(fPSh)", detail: "Mara has one picnic shelter available for reservation from the Friday of the Victoria Day weekend until Labour Day. This medium sized picnic shelter is located right on our beautiful beach and will accommodate up to 50 people. The shelter comes with the use of a charcoal barbeque and has enough picnic tables to accommodate maximum capacity. Alcohol is not permitted in our day-use area and this includes our picnic shelter. Parking is available within close proximity to the shelter and there are washrooms and drinking water taps available for use. \n\nCall the park directly to inquire about or reserve the picnic shelter (705) 326-4451")])
