//
//  Marten.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let marten = Park(name: "marten river",
                  about: "\u{2022} A replica 19th century logging camp brings a bygone era to life\n\u{2022} The park is the southern gateway to the Temagami area and is a base for canoeists, boaters, hikers and anglers\n\u{2022} Enjoy remnant stands of massive pines including a 350 year old White Pine as you walk the Transition Trail\n\u{2022} Take part in various logging contests, enjoy a logger’s bean lunch, be serenaded by fiddlers, charmed by the antics of chainsaw carvers and entertained by an array of musicians during Lumberjack Days\n\u{2022} Relax at one of the park’s three beaches, engage in a beach volleyball game or enjoy a friendly game of horseshoes",
                  general: "\u{2022} Phone: (705) 892-2200\n\u{2022} Size: 400.25 ha\n\u{2022} Year established: 1960\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t2860 Hwy 11 North\n\tMarten River\n\tP0H 1T0",
                  camping: [0: (heading: "\(cCar)", detail: "Campsites can accommodate equipment ranging from tents only to large trailers.  Many campsites offer electrical hook-up.  Amenities such as water taps, comfort stations and laundry facilities are close by.  Swimming, boating, angling and hiking opportunities are only a short distance away."), 1: (heading: "\(cGrp)", detail: "Marten River has one group camping site that accommodates up to 125 people and offers on-site toilets and water taps.  The site is approximately one kilometre from the comfort station and 0.5 km from the beach.")],
                  activities: [0: (heading: "\(aBik)", detail: "Biking is allowed on park roads."), 1: (heading: "\(aBrd)", detail: "Marten River and the surrounding landscape provide many different habitats for birds. Warblers, flycatchers, hawks owls and ducks nest here each year. Watch and listen for them as they look for food, feed their chicks and defend their territories from rivals."), 2: (heading: "\(aBtg)", detail: "Power boats are allowed on Marten River and many of the nearby lakes."), 3: (heading: "\(aCan)", detail: "Marten River itself provides lots of opportunities to explore, with numerous bays and long stretches of shoreline. As the park is the southern gateway to the Temagami region, there are many canoeing opportunities close by. Nearby, Kenny Forest Provincial Park has a number of large, interconnected lakes to paddle, and for whitewater enthusiasts, the Temagami River is a great canoe or whitewater kayak route, either for the day or overnight. \n\nMany more canoe route options can be found in the Temagami region. The area includes a number of other provincial parks, and with adjacent Crown land includes 2400 km of interconnected waterways. Canoe route maps of the many routes are available for purchase."), 4: (heading: "\(aFsh)", detail: "Marten River offers Northern Pike, Pumpkinseed, Rock Bass, Smallmouth Bass, Walleye and Yellow Perch. Lake Trout, Lake whitefish and Brook trout can also be found in nearby lakes."), 5: (heading: "\(aHik)", detail: "Transition Trail: Marten River’s Transition Trail offers a moderate hike that is five kilometers long and will take approximately two hours to complete. The trail takes you through a variety of forest types from mature pine stands to a Black Spruce bog."), 6: (heading: "\(aNHE)", detail: "Marten River offers a variety of interpretive programs for all ages. Park naturalists lead hikes, give evening programs and campfires, as well as telling visitors about the days of horse logging at the Winter Camp, a replica 19th-century logging camp that brings a bygone era to life. An award-winning film, “The Winter Camp”, was shot here years ago, depicting the hard work and dangers faced by the men who lived and worked in the frozen Canadian forests each winter. It is regularly shown in the Museum Theatre during summer months."), 7: (heading: "\(aSwm)", detail: "There are three natural sand beaches recommended for swimming. These beaches are marked with buoys and have gradual drop-offs. Please note: there are no lifeguards posted at the beaches and pets are not permitted.")],
                  facilities: [0: (heading: "\(fBF)", detail: "The following facilities are barrier-free: showers, flush toilets, swimming, nature/visitor centre."), 1: (heading: "\(fBL)", detail: "There are two boat launches in the Chicot Section, one in the Assinka Section and one near the Marten River entrance."), 2: (heading: "\(fCS)", detail: "There are two comfort stations in the campground providing barrier-free showers, flush toilets, and sinks. Laundry facilities are also available. \n\nThe day-use area has a comfort station with flush toilets and sinks."), 3: (heading: "\(fDU)", detail: "Marten River has a day-use area not far from the park entrance and Highway 11.  The comfort station is a barrier-free facility, with flush toilets and sinks.  There is a large beach and picnic area on Marten River with canoe access and a boat launch.  The day-use area is next to the Winter Camp, a replica 19th-century logging camp that brings a bygone era to life.  Along with a number of log buildings and period logging equipment, there is a museum and theatre.  Check with the park office for program and tour schedules."), 4: (heading: "\(fFT)", detail: "Flush toilets are available in the campground and day-use area."), 5: (heading: "\(fPSt)", detail: "The store features clothing items, souvenirs, maps, ice, firewood and books. Groceries and other essentials are available from local businesses near the park."), 6: (heading: "\(fR)", detail: "The park runs a TackleShare program which lends out fishing rods and tackle to park visitors. \n\nTrailer storage is available at Marten River.")])
