//
//  Massassauga.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let massaasauga = Park(name: "the massasauga",
                       about: "\u{2022} Backcountry camping on Georgian Bay stretching from Parry Sound to the Moon River\n\u{2022} Park takes in hundreds of windswept islands, inland forests and lakes\n\u{2022} Camp by the bay or paddle to inland lake sites\n\u{2022} Protected sanctuary for the Massasauga Rattlesnake\n\u{2022} Boat mooring in a quiet cove\n\u{2022} Visit Calhoun Lodge for a glimpse of 1930s cottage life",
                       general: "\u{2022} Phone: 705-378-2401\n\u{2022} Size: 13105.00 ha\n\u{2022} Year established: 1989\n\u{2022} Park Classification: Natural Environment \n\u{2022} Address:\n\t380 Oastler Park Drive\n\tParry Sound\n\tP2A 2W8",
                       camping: [0: (heading: "\(cBac)", detail: "The Massasauga is a backcountry only park. The only way to access the park’s 135 campsites is by canoe, kayak or boat. Forty-eight campsites are on inland lakes accessible by portages.")],
                       activities: [0: (heading: "\(aBrd)", detail: "White-tailed deer, moose, black bears and wolves are commonly spotted in the park. Chipmunks, raccoons, birds, hybrid toads and five-linked skinks appear around the campsites. This area is also home to the poisonous, but rarely seen, Massasauga Rattlesnake."), 1: (heading: "\(aBtg)", detail: "The Massasauga is best explored by boat. Sailing, sea kayaking and motorboating are popular, but only experienced boaters with proper navigational charts should rely on motorized travel. Motorized travel is not permitted on inland lakes."), 2: (heading: "\(aCan)", detail: "Canoe rentals available for campers, reservations are recommended."), 3: (heading: "\(aFsh)", detail: "The Massasauga boasts a first-class fishery of muskie and bass. Pike and panfish are also very common. Please refer to fishing regulations for seasons."), 4: (heading: "\(aHik)", detail: "\u{2022} Baker Trail 5.5 km, (3 hours), moderate-difficult \n\tThis self-guided interpretive trail starts at Calhoun Lodge and leads to the Baker pioneer homestead. Side trails branch to the shore, ideal for picnicking. Don’t forget to wear proper hiking footwear and bug repellent. \n\nMoon Island Trail – This is a 4 km self-guided trail of moderate difficulty that can be accessed from the Wood’s Bay Day-Use site. The trail traverses various terrain and forest types with impressive lookouts onto Georgian Bay. There are excellent opportunities to view waterfowl, a heron rookery and beaver pond. Along the trail you can see signs of wildlife including moose, deer, bear, and grouse. \n\u{2022} Wreck Island Trail 1.5 km, (1 hour), moderate (self-guided) \n\tNine interpretive stops explain the geology along this trail. Those who find the trail too rugged, can opt for a shorter loop of about 800 m."), 5: (heading: "\(aHnt)", detail: "Hunting in this park is subject to the Ontario Hunting Regulations. Certain restrictions apply. For more information, contact the park or your local Ministry of Natural Resources office."), 6: (heading: "\(aSwm)", detail: "Small, sandy beaches interrupt a rocky shore next to water that is crystal clear and sometimes deep. Islands in the park offer many swimming spots. There are no buoyed areas or change facilities.")],
                       facilities: [0: (heading: "\(fBL)", detail: "Pete’s Place only."), 1: (heading: "\(fDU)", detail: "The Massasauga can be explored by boat daily from 7:00 a.m. to 7:00 p.m. from any one of four day-use areas, overnight boating bays or Calhoun Lodge. Visitors moored to shore after 7:00 p.m. or occupying a designated campsite require a valid permit. \n\nPete’s Place Day Use – No parking available – water access only."), 2: (heading: "\(fR)", detail: "Canoe rentals are available, reservations are recommended; non-reserved canoes are available on first-come, first-served basis for campers. Check at the Park Office for more information.")])
