//
//  McRae.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let mcrae = Park(name: "mcrae point",
                 about: "\u{2022} Pull-through sites for large and extra large equipment\n\u{2022} On the shores of Lake Simcoe near Orillia\n\u{2022} 1.2 km nature trail\n\u{2022} Boat launch and boat rentals close by\n\u{2022} Swimming\n\u{2022} Novelty ice cream, firewood, ice, and Ontario Parks merchandise available at Registration Office\n\u{2022} Restaurants, gas stations, shopping and convenience stores within a 15 min drive.\n\u{2022} Only 15 minute drive from Casino Rama",
                 general: "\u{2022} Phone: 705-325-7290\n\u{2022} Size: 137.60 ha\n\u{2022} Year established: 1971\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t4366 McRae Park Road\n\tRamara Township\n\tL3V 6H7",
                 camping: [0: (heading: "\(cCar)", detail: "McRae Point offers car camping in the North and South Campgrounds.  The North Campground is fully serviced with electricity and has large pull-through sites that accommodate extra large trailers and motorhomes.  There are fully serviced washroom and shower buildings located in this campground with smaller washrooms found throughout. The South Campground is a campground that features both electrical and non-electrical campsites.  This campground has access to the shower buildings in the North Campground and has washrooms located throughout.")],
                 activities: [0: (heading: "\(aBik)", detail: "Visitors are welcome to cycle on park roads."), 1: (heading: "\(aBrd)", detail: "McRae is host to 79 species of birds including the Yellow-throated Vireo and Pileated Woodpecker."), 2: (heading: "\(aBtg)", detail: "McRae Point has boat launch facilities and its location on Lake Simcoe offers access to the Trent Severn Waterway."), 3: (heading: "\(aFsh)", detail: "Lake Simcoe offers great fishing opportunities for the avid angler."), 4: (heading: "\(aHik)", detail: "Tucked away in McRae Point Provincial Park, is The Water’s Edge Trail. This trail offers visitors the chance to explore a diverse ecosystem and makes for a memorable experience at McRae Point. The start of the trail is located near our boat launch and will guide you along Lake Simcoe to a section of boardwalk, passing through lush hardwood swamp, rich in a variety of ferns. Further along the trail you will come out to a point known for magnificent sunsets over Lake Simcoe."), 5: (heading: "\(aHnt)", detail: "For information about hunting at McRae Point Provincial Park, you can visit the Ministry of Natural Resources web page at www.mnr.gov.on.ca. The annual Hunting Regulations Summary publication is available at Service Ontario on their website under the Publications tab at www.publications.serviceontario.ca \n\nYou could also call the Ministry of Natural Resources Information Centre at 1-800-667-1940."), 6: (heading: "\(aSwm)", detail: "McRae Point offers a large designated swimming area for visitors.")],
                 facilities: [0: (heading: "\(fBF)", detail: "Barrier-free washrooms are available in both the North and South campgrounds. There are two electrical barrier-free sites (#51 and #53) that can be reserved through the Ontario Parks website and reservation call centre."), 1: (heading: "\(fBL)", detail: "McRae Point has boat launch facilities and its location on Lake Simcoe offers access to the Trent Severn Waterway."), 2: (heading: "\(fCS)", detail: "McRae Point offers fully serviced comfort stations in the North Campground and comfort stations with flush toilets in the South Campground. Barrier-free washrooms are available in both campgrounds."), 3: (heading: "\(fDU)", detail: "Our large day-use area is available upon purchase of a valid day use permit, summer pass, annual pass or if you have a valid camping permit. The day-use area is open daily from 8:00 a.m. to 10:00 p.m. from the second Friday in May until the Thanksgiving Monday.  No alcohol is permitted in our day-use area at any time, day or night.  If you are bringing pets, they must be leashed at all times, including our off-season and they are not permitted on the beach."), 4: (heading: "\(fFT)", detail: "Flush toilets are found in comfort stations in the North and South Campgrounds."), 5: (heading: "\(fR)", detail: "Personal Floatation Devices can be borrowed with a $30 refundable deposit for each jacket at our Registration Office.")])
