//
//  Mikisew.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let mikisew = Park(name: "mikisew",
                   about: "\u{2022} Three sandy beaches perfect for the family\n\u{2022} Great boating and paddling on Eagle Lake, west of South River and Hwy. 11\n\u{2022} Four great interconnected hiking trails that meander through a variety of terrain\n\u{2022} Eagle Lake is a popular fishing lake for several species of trout, walleye, bass, perch and pike.\n\u{2022} Private sunny campsites are available from mid June to the end of September",
                   general: "\u{2022} Phone: (705) 386-7762 (May – September) (705) 729-2010 (October – April)\n\u{2022} Size: 130.71 ha\n\u{2022} Year established: 1964\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t301 Park Road South\n\tSouth River\n\tP0A 1X0",
                   camping: [0: (heading: "\(cCar)", detail: "Mikisew offers camping in two campgrounds: The Hardwoods and The Pines. Comfort stations are centrally located in each campground and include amenities such as flush toilets, showers and laundry facilities. Several campsites are fully wheelchair accessible and located adjacent to each of the comfort stations. \n\nHardwoods Campground features rolling hills in woods of Yellow Birch, Maple and Oak. Campsites accommodate most sizes of camping equipment from tents to RVs. Electrical sites are also available. \n\nPines Campground is located in a Red Pine plantation, covered in a soft bed of Pine needles. Campsites accommodate most any size camping equipment from tents to RVs. Electrical sites are also available."), 1: (heading: "\(cGrp)", detail: "Mikisew offers two group campsite options; choose from a site on the shore of Eagle Lake or in a secluded section of the Pines Campground. \n\nBonfire Group Site can accommodate up to 50 people and is close to one of the beaches on Eagle Lake. \n\nWoodlot group site can accommodate up to 25 people and is located in the Hardwoods campground. Both sites are in close proximity to water taps, toilets, and the comfort stations. \n\n \n\nGroup reservations can be made by calling Restoule Provincial Park from the first business day of May to June 1 at (705) 729-2010. After June 1, group reservations can be made by calling Mikisew directly at (705) 386-7762.")],
                   activities: [0: (heading: "\(aBik)", detail: "Cycling is permitted on all trails and park roads."), 1: (heading: "\(aBrd)", detail: "More than 90 species of birds frequent the waters and forests of Mikisew such as Bald Eagle and Osprey."), 2: (heading: "\(aBtg)", detail: "Power boats are allowed on Eagle Lake. A note of caution: there are numerous unmarked shoals."), 3: (heading: "\(aCan)", detail: "Eagle Lake - Launch your canoe or rent one from one of the local outfitters and you can paddle right into Eagle Lake. Spend the day exploring all that Eagle Lake has to offer."), 4: (heading: "\(aFsh)", detail: "Eagle Lake is a popular fishing lake for Walleye, Small and Large mouth Bass, Lake Whitefish, Perch and Northern Pike."), 5: (heading: "\(aHik)", detail: "Four interconnected loops meander through mixed terrain with steep grades. Choose a hike that suits you. \n\n\u{2022} Beaver Meadow Trail: 3.2 Km (1 hour) loop trail, moderate \n\tA refreshingly beautiful trail, the Beaver Meadow Trail loops around a beaver wetland complex that is slowly returning to forest. There are many opportunities for bird watching on this trail as it travels through wetland areas to lowland and upland forest. \n\n\u{2022} Maple Canyon Trail: 2.3 Km (1 hour) loop trail, moderate \n\tRock outcrops and a changing forest are the highlights on this moderate trail. The Maple Canyon has two trailside rocky outcrops with excellent examples of quartz intrusion and rock tripe. Take a close look at these rocks and discover Mikisew’s geologic past. \n\n\u{2022} Lakeview / Point Trail: 1 Km (25 minutes) linear trail, easy \n\tA short trail along the shore of Eagle Lake, the Lakeview Trail boasts a beaver pond and fantastic Lakeside views close to the campgrounds. Bring your binoculars as you may be lucky enough to see a Great Blue Heron or Wood Duck in the beaver pond. The Point Trail is a small spit of land that juts out into Eagle Lake. Bring a picnic lunch and a book and enjoy this private getaway within the park. \n\n\u{2022} Old Dog Trail: 1.7 Km (20 minutes) linear trail, easy \n\tThe Old Dog Trail is a short hike through the lowland forest of Mikisew and connects to the trailhead of the Beaver Meadow and Maple Canyon Trails. You will see ash trees, Red Maple and many wildflowers. This trail is suitable for all ages."), 6: (heading: "\(aSwm)", detail: "There are three sand beaches for swimming located along Eagle Lake in Mikisew Provincial Park. The North Beach and Centre Beach are located in the Hardwoods Campground and the Day-Use Beach is located in the Day-Use area. All of these beaches are marked with buoys and have gradual drop-offs. \n\nThe pet exercise area (also located in the Day-Use area) has a pet friendly beach. \n\nPlease note: there are no lifeguards posted at the beaches and pets are permitted only at the pet exercise area.")],
                   facilities: [0: (heading: "\(fBF)", detail: "Barrier-free washrooms are available in each of the two comfort stations. Mikisew also offers four barrier-free campsites."), 1: (heading: "\(fBL)", detail: "A boat launch is found near the Day-Use Area."), 2: (heading: "\(fCS)", detail: "Comfort stations (complete with showers, flush toilets, and laundry facilities) are located in Hardwoods and Pines Campgrounds."), 3: (heading: "\(fDU)", detail: "All three beaches are popular Day-Use areas. All have sandy beaches with buoyed swimming areas (but no life guards) and shady areas with picnic tables and water taps located near by."), 4: (heading: "\(fFT)", detail: "Flush toilets are located in each of the two comfort stations."), 5: (heading: "\(fL)", detail: "Laundry facilities are located in each of the two comfort stations."), 6: (heading: "\(fPEA)", detail: "A pet exercise area is located near the Day-Use area and includes a pet friendly swimming area and an agility course."), 7: (heading: "\(fR)", detail: "\u{2022} Beach volley balls \n\n\u{2022} Basketballs \n\n\u{2022} Horseshoes \n\n\u{2022} Soccer balls \n\n\u{2022} Baseballs \n\n\u{2022} Frisbees")])
