//
//  Nagamisi.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let nagagamisis = Park(name: "nagagamisis",
                       about: "\u{2022} Anglers return year after year to this large secluded lake north of Hornepayne. They are drawn by the excellent fishing for Great Walleye, Northern Pike and Yellow Perch.\n\u{2022} Boat launch, fish cleaning station and fish smoker.\n\u{2022} Two great hiking trails and a new playground!\n\u{2022} The lake’s name in Cree means “lake with fine, sandy shores” and is part of a significant Boreal Forest landscape.\n\u{2022} Excellent wildlife viewing and bird watching.\n\u{2022} Motorboat, canoe, kayak and bike rentals.\n\u{2022} A good jump-off point for challenging canoe routes on the Nagagami and Shekak Rivers.",
                       general: "\u{2022} Phone: 807-868-2254\n\u{2022} Size: 40683.00 ha\n\u{2022} Year established: 1957\n\u{2022} Park Classification: Natural Environment \n\u{2022} Address:\n\tPO BOX 670, 613 Front Street\n\tHearst\n\tP0L 1N0",
                       camping: [0: (heading: "\(cCar)", detail: "Car camping is available at two campgrounds in close proximity to showers, a laundromat and flush toilets. No electrical sites are available.")],
                       activities: [0: (heading: "\(aBik)", detail: "Cycling is available only on park roads. Mountain biking opportunities are available outside the park on the many bush roads winding through the forest."), 1: (heading: "\(aBrd)", detail: "Nagagamisis lies within the vast boreal forest region. This is often called the songbird nursery, as hundreds of bird species nest here each summer. Warblers are the most colourful and have the prettiest songs, but many other birds can be heard and seen in the park, including many types of woodpeckers, ducks, finches and flycatchers, as well as fishing birds like Great Blue Herons, Ospreys and Bald Eagles."), 2: (heading: "\(aBtg)", detail: "Enjoy the extensive boating opportunities on Nagagamisis Lake. Launch your boat and pull it up on shore, especially if you camp on one of the waterfront sites."), 3: (heading: "\(aCan)", detail: "There are excellent canoeing opportunities on Nagagamisis Lake and Park Lake. Nagagami and Shekak Rivers both provide backcountry canoeing opportunities for experienced canoeists."), 4: (heading: "\(aFsh)", detail: "Fish for Walleye, Northern Pike, Lake Whitefish and Yellow Perch, then clean your catch at a fish cleaning hut close to the fish smoker and playground."), 5: (heading: "\(aHik)", detail: "\u{2022} Shaganash Trail 4 km (2 hours) moderate \n\t This trail follows the shoreline of Park Lake. Interpretive stops along the way explain how Aboriginals used plants and wildlife to survive in this environment. \n\n\u{2022} Time Trail 1.5 km loop (1.5 hours) moderate \n\t Along the trail are signs of the different stages of this land’s development."), 6: (heading: "\(aHnt)", detail: "Hunting in this park is subject to the Ontario Hunting Regulations. Certain restrictions apply. For more information, contact the park or your local Ministry of Natural Resources office."), 7: (heading: "\(aSwm)", detail: "The sandy beaches, clear water and buoyed area are perfect for family swimming. There are change facilities. There is a full size sand volleyball court at the Day-Use Area, and a place to play horseshoes. A bit closer o the campground is our new playground!")],
                       facilities: [0: (heading: "\(fBF)", detail: "The comfort station and showers are barrier-free, and we offer a barrier-free campsite."), 1: (heading: "\(fBL)", detail: "The park boat launch provides lots of room to launch your boat and parking for vehicles and trailers."), 2: (heading: "\(fCS)", detail: "Our barrier-free comfort station, located in Bedwash Campground, has flush toilets, mirrors, sinks, hand sanitizer, hand dryers and showers."), 3: (heading: "\(fDU)", detail: "Our Day-Use area offers lots of room for picnics, with shaded areas along the shores of Nagagamisis Lake."), 4: (heading: "\(fFT)", detail: "All park outhouses have flush toilets, sinks, mirrors, and hand sanitizer."), 5: (heading: "\(fL)", detail: "There are washers and dryers, a laundry tub, and a laundry soap dispenser with common detergents for sale at the comfort station."), 6: (heading: "\(fPSt)", detail: "The Park Store is found in the Main Gate House. A variety of supplies are available, from key needs like ice, bug spray and suntan lotion, to coffee, ice cream and candy. You will also find a variety of Ontario Parks’ merchandise for the whole family."), 7: (heading: "\(fR)", detail: "The park rents motorboats, canoes, kayaks, peddle boats and bicycles.")])
