//
//  Oastler.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let oastler = Park(name: "oastler lake",
                   about: "\u{2022} Set on the Boyne River, minutes from Parry Sound and Georgian Bay\n\u{2022} Panoramic views from the waterfront campsites overlooking Oastler Lake\n\u{2022} Summer hiking and biking on the nearby Seguin Recreational Trail\n\u{2022} Great fishing for Rainbow Trout, pike and bass\n\u{2022} Canoe rentals on site\n\u{2022} Note: railway tracks near the park are used frequently.",
                   general: "\u{2022} Phone: 705-378-2401\n\u{2022} Size: 31.56 ha\n\u{2022} Year established: 1967\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t380 Oastler Park Drive\n\tParry Sound\n\tP2A 2W8",
                   camping: [0: (heading: "\(cCar)", detail: "The park provides car camping in five campgrounds. Each campground offers easy access to drinking water, toilets and a comfort station. There is also a small boat launch; a trailer dumping/filling station and a picnic shelter close by. Parking for one vehicle is allowed on the campsite and all other vehicles must park in the additional vehicle parking lot. The park has water filling stations throughout however there is a boil water advisory in effect. \n\nNote: railway tracks near the park are used frequently."), 1: (heading: "\(cRad)", detail: "The Point Campground is radio-free."), 2: (heading: "\(cWak)", detail: "Ten walk-in campsites are located on the tip of the peninsula in the Point Campground.  Parking for one vehicle per campsite is available and is approximately 100 to 300 metres from your campsite.")],
                   activities: [0: (heading: "\(aBik)", detail: "Cycling on park roads is limited. Please wear your helmets and use extra caution. The Seguin Recreational Trail is a 5 km drive outside of the park, take exit 214 just off of Hwy. 400."), 1: (heading: "\(aBtg)", detail: "This small inland lake is suitable for small boats less than 20 feet long. There is a boat launch and limited docking facilities on a first-come, first-served basis."), 2: (heading: "\(aCan)", detail: "Canoe rentals are available on first-come, first-served basis for campers."), 3: (heading: "\(aFsh)", detail: "Summer is the best time to fish for Rainbow Trout, pike and bass. Please refer to the Ontario Fishing Regulations for seasons."), 4: (heading: "\(aSwm)", detail: "Oastler Lake boasts one of the best beaches in the Parry Sound Area. There is plenty of room to play a game of volleyball, build sand sculptures, or just relax on the beach.")],
                   facilities: [0: (heading: "\(fBF)", detail: "There are barrier-free showers and flush toilets in the comfort stations."), 1: (heading: "\(fBL)", detail: "Small launch, limited space, first come-first serve"), 2: (heading: "\(fCS)", detail: "Enjoy modern camping facilities on beautiful Oastler Lake. Comfort stations with showers and flush toilets are located in the campground.  Paddle your way across the lake in rental canoes with free Personal Floatation Device (PFD) rentals! For the four legged campers, Oastler offers a pet friendly swimming area."), 3: (heading: "\(fDU)", detail: "Great place to spend the day swimming, having a family picnic or barbeque."), 4: (heading: "\(fPSt)", detail: "Souvenirs, clothing and firewood are available for purchase at the Park Office. Groceries can be purchased in Parry Sound, just minutes down the road from the park."), 5: (heading: "\(fPEA)", detail: "The Pet Exercise Area includes a very small sandy beach, grassy area with a couple benches and picnic tables. It’s a great place to bring your pet for a swim off-leash."), 6: (heading: "\(fPSh)", detail: "Reservations are recommended and can be made for a half day or full day."), 7: (heading: "\(fR)", detail: "Canoes are available for rent on a first-come, first-served basis, but may only be used within the park on Oastler Lake.")])
