//
//  Obabika.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let obabika = Park(name: "obabika river",
                   about: "\u{2022} This waterway park contains an incredible diversity of landscapes, from island-speckled lakes, to meandering rivers, bedrock uplands and expansive wetlands, as well as towering stands of old growth pine and rocky cliffs\n\u{2022} Part of Temagami’s 2400km network of portages and waterways, the park contains segments of a number of canoe routes that link with other parks, conservation reserves and Crown land.\n\u{2022} Archaeological evidence of the area’s rich aboriginal heritage dates back 6,000 years, and canoeists will travel on ancient portages or “nastawgan”.\n\u{2022} Remnants of the horse logging days and old lumber camps are found along many of the lakes in the park\n\u{2022} The trails in Obabika Lake Old Growth Forest take hikers through one of Temagami’s old-growth Red and White Pine stands, hundreds of years old and untouched by logging.",
                   general: "\u{2022} Phone: (705) 569-3205\n\u{2022} Size: 20520.00 ha\n\u{2022} Year established: 1989\n\u{2022} Park Classification: Waterway \n\u{2022} Address:\n\t24 Finlayson Park Road\n\tTemagami\n\tP0H 2H0",
                   camping: [0: (heading: "\(cBac)", detail: "Backcountry campsites are rustic, with a box privy and fire pit. Campsites are marked on the Temagami Canoe Route Map. Please check it or other trip planning resources for route ideas and campsites. \n\nPlease Note: Permits are required for all overnight backcountry camping.  For a list of best locations to obtain permits, please contact the park directly.")],
                   activities: [0: (heading: "\(aBrd)", detail: "Lady Evelyn-Smoothwater and the surrounding waterway parks including Obabika River, protect an area of rugged highland watersheds and contain forest that mixes Great Lakes-St. Lawrence and Boreal species of trees, creating many different habitats for birds. During the nesting season of spring and early summer, many species of warbler, thrush, flycatcher and woodpecker can be heard calling to defend territory. Eagles, osprey and many other birds of prey can be spotted hunting above the forests of the park."), 1: (heading: "\(aBtg)", detail: "Motorboat restrictions apply. Please refer to the Temagami Area Park Management Plan 2007 for zone specific management direction."), 2: (heading: "\(aCan)", detail: "As part of the interconnected network of canoe routes in the Temagami region, Obabika River Provincial Park can be used as part of a number of different routes. Common routes include Lake Temagami, Diamond, Wakimika and Obabika Lakes; Obabika Lake and the Obabika River itself can be combined as a loop; and Lady Evelyn, Sucker Gut and Willow Island Lakes are part of the route to Maple Mountain and beyond. Check the Temagami Canoe Route Planning map or other trip planning resources for route ideas."), 3: (heading: "\(aFsh)", detail: "Ontario Fishing regulations apply."), 4: (heading: "\(aHik)", detail: "Obabika Lake Old Growth Trails: A system of day-use hiking trails spread through the old growth forest area. These trails are rated as intermediate and require a full day or more to explore. Hikers are encouraged to take food and water along and are reminded to be especially respectful when using the trails of this spiritually significant area."), 5: (heading: "\(aHnt)", detail: "Hunting restrictions apply. Please refer to the Temagami Area Park Management Plan 2007 for zone specific management direction."), 6: (heading: "\(aSwm)", detail: "The lakes and rivers of this provincial park offer typical backcountry swimming opportunities with some fine sand/silt shorelines and rocky headlands for access to the water.")],
                   facilities: [0: (heading: "\(fR)", detail: "Canoes and camping equipment can be rented from outfitters near the various park access points.")])
