//
//  Ojibway.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let ojibway = Park(name: "ojibway",
                   about: "\u{2022} Tranquil and wild, this retreat on Little Vermilion Lake offers a sandy beach and good swimming\n\u{2022} Fantastic fishing for Smallmouth Bass\n\u{2022} Park lakes link to several major northern canoe routes\n\u{2022} A small, quiet park where reservations are not required",
                   general: "\u{2022} Phone: (807)737-2033 summer (807)223-7535 winter\n\u{2022} Size: 2630.55 ha\n\u{2022} Year established: 1963\n\u{2022} Park Classification: Natural Environment \n\u{2022} Address:\n\tBox 730, 479 Government Street\n\tDryden\n\tP8N 2Z4",
                   camping: [0: (heading: "\(cCar)", detail: "Ojibway is a small campground offering fewer than 50 campsites, half of which have electricity.  Campsites can accommodate equipment ranging from tents only to large trailers.  Seasonal leased campsites are also available. Amenities such as water taps, comfort stations and laundry facilities are close by.  Swimming, boating, great fishing and hiking are only a short distance away."), 1: (heading: "\(cGrp)", detail: "Ojibway has one group campsite available which can accommodate 15 to 50 people.  Water taps and vault toilets are on site. The area is within walking distance of the beach and hiking trails. \n\nTo reserve, call the park directly (807) 737-2033.")],
                   activities: [0: (heading: "\(aBik)", detail: "Cycling is a popular way to explore the campground. Children are reminded to wear their helmets."), 1: (heading: "\(aBtg)", detail: "All boats are allowed in Ojibway’s numerous lakes."), 2: (heading: "\(aCan)", detail: "Launch your canoe or rent one at the Park Office and enjoy exploring Little Vermilion Lake. The lakes in the park also link to longer canoe routes."), 3: (heading: "\(aFsh)", detail: "The lakes in and around the park teem with Northern Pike, walleye, Smallmouth Bass and Lake Trout. A fish cleaning station, with running water and cutting tables, is located by the north boat launch. Huge Smallmouth Bass can be caught right from the dock!"), 4: (heading: "\(aHik)", detail: "\u{2022} Boreal Walking Trail - 1.5 km, easy  \n\tAlong this trail through the boreal forest, larch and Jack Pines grow among White and Black Spruce and White Birch. \n\n\u{2022} Lakeshore Trail – 6 km, moderate \n\tFour interpretive stops explain the vegetation and geology found along the shore of Little Vermilion Lake. \n\n\u{2022} Little Walking Trail - 0.8 km, easy  \n\tTwelve interpretive stops along this trail describe the diversity of trees, plants and wildlife typical of the boreal forest. \n\n\u{2022} Red pine Walking Trail - 0.5 km, easy \n\tLearn about forest succession at the nine interpretive stops along this trail. \n\n\u{2022} Ridge Bottom Trail - 2.8 km, moderate \n\tA wide variety of lichens, soils and fungi is featured at the 14 interpretive stops along this trail. \n\n\u{2022} Terry Lake Trail - 1.5 km, easy \n\tThe trail leads to Terry Lake where you can fish for Northern Pike and view wildlife such as moose."), 5: (heading: "\(aSwm)", detail: "The Beach is located in the Day-Use area. The beach is marked with buoys. Please note: there are no lifeguards posted at the beaches and pets are not permitted.")],
                   facilities: [0: (heading: "\(fBF)", detail: "Barrier-free access is available at the comfort station in the main campground. There is also a wheelchair ramp at the Day-Use area."), 1: (heading: "\(fBL)", detail: "Two boat launches are located at either end of the campground. Docking facilities are available for park visitors."), 2: (heading: "\(fCS)", detail: "A comfort station with showers and flush toilets is located in the main campground."), 3: (heading: "\(fDU)", detail: "The Day-Use area has a sandy beach with buoyed swimming areas, playground, picnic shelter, water taps and vault toilets."), 4: (heading: "\(fFT)", detail: "Flush toilets are found in various locations in the campground."), 5: (heading: "\(fL)", detail: "Laundry facilities can be found at the comfort station in the main campground."), 6: (heading: "\(fPSh)", detail: "There is one picnic shelter located in the day-Use area. The shelter is available on a first-come, first-served basis.")])
