//
//  Pakwash.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let pakwash = Park(name: "pakwash",
                   about: "\u{2022} Secluded and serene, this northern park guarantees a sandy beach and shallow, warm waters ideal for swimming, fishing and canoeing\n\u{2022} Gateway for northern canoe routes\n\u{2022} Fantastic walleye fishing\n\u{2022} Small, quiet park where camping reservations are not necessary",
                   general: "\u{2022} Phone: (807)222-3346 summer (807)223-7535 winter\n\u{2022} Size: 3993.00 ha\n\u{2022} Year established: 1967\n\u{2022} Park Classification: Natural Environment \n\u{2022} Address:\n\tBox 730, 479 Government Street\n\tDryden\n\tP8N 2Z4",
                   camping: [0: (heading: "\(cCar)", detail: "This small, quiet campground has over 50 campsites, almost half of which have electricity.  A few campsites are located away from the main campground and have their own beach front view. Campsites can accommodate equipment ranging from tents only to large trailers.  Amenities such as water taps, comfort stations and laundry facilities are close by.  Swimming, boating, great fishing and hiking are only a short distance away."), 1: (heading: "\(cGrp)", detail: "Pakwash has one group campsite and can accommodate from 15 to 100 people.  Water taps and vault toilets are on site. The area is within walking distance of comfort stations, the beach and hiking trails. \n\nTo reserve, call the park directly (807) 222-3346.")],
                   activities: [0: (heading: "\(aBik)", detail: "Cycling is a popular way to wander through the campground. Kids are reminded to wear their helmets"), 1: (heading: "\(aBtg)", detail: "Boating is permitted on Pakwash Lake but please take care when there are high winds; this open lake can get very choppy."), 2: (heading: "\(aCan)", detail: "Launch your canoe or rent one at the Park Office and you can paddle on Pakwash Lake."), 3: (heading: "\(aFsh)", detail: "The lakes in and around the park teem with Northern Pike, walleye and Lake trout. A fish-cleaning station with lights, running water and cutting tables is located by the boat launch. In early June you can catch a feed of walleye from the shoreline of your campsite."), 4: (heading: "\(aHik)", detail: "\u{2022} Nature Trail - 5 km, moderate  \n\tHikers will cross a marsh, pass a beaver pond and walk through woods along this nature trail. Along the way nine interpretive stops explain the flora and fauna that inhabit the area."), 5: (heading: "\(aSwm)", detail: "Pakwash features a long, sandy beach located in the day-use area of the park. The swimming area is marked with buoys. Please note that there are no lifeguards posted at the beaches and pets are not permitted.")],
                   facilities: [0: (heading: "\(fBF)", detail: "The comfort station located in the main campground offers barrier-free access. There is also a wheelchair ramp at the day-use area."), 1: (heading: "\(fBL)", detail: "A boat launch is located in the campground by the fish cleaning hut."), 2: (heading: "\(fCS)", detail: "A comfort station, complete with showers and flush toilets, is located in the main campground."), 3: (heading: "\(fDU)", detail: "The day-use area has a long, sandy beach with buoyed swimming areas (but no life guards), playground, picnic shelter, water taps and vault toilets."), 4: (heading: "\(fFT)", detail: "A comfort station, complete with showers and flush toilets, is located in the main campground."), 5: (heading: "\(fL)", detail: "Laundry facilities can be found at the comfort station located in the main campground."), 6: (heading: "\(fPSt)", detail: "A small park store is located in the Park Office. The store features clothing items, souvenirs, camper supplies, ice and firewood. Groceries are available outside of the park in Ear Falls 20 km south on Highway 105."), 7: (heading: "\(fPSh)", detail: "There is one picnic shelter in the day-use area which is available on a first-come, first-served basis.")])
