//
//  Peter.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let peter = Park(name: "lake st. peter",
                 about: "\u{2022} Large lake to explore by boat; great fishing opportunities\n\u{2022} Beautiful sandy beaches for swimming\n\u{2022} Spend the day at nearby Algonquin or Silent Lake Provincial Parks, free for day-use with your camping permit from Lake St. Peter",
                 general: "\u{2022} Phone: 613-338-5312\n\u{2022} Size: 478.16 ha\n\u{2022} Year established: 1971\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t356 Lake St. Peter Road\n\tLake St. Peter\n\tK0L 2K0",
                 camping: [0: (heading: "\(cCar)", detail: "Lake St. Peter has sixty-five beautiful campsites to offer visitors. They are spacious, comfortable and sheltered by the mixed forest. Many of the sites will accommodate large trailers. There are several electrical sites and waterfront sites to choose from. All sites are close to drinking water taps and vault toilets. A centrally located comfort station has washrooms, showers and laundry facilities.")],
                 activities: [0: (heading: "\(aBik)", detail: "There are no dedicated cycling trails in the park, but local forest access and municipal roads provide excellent cycling opportunities. The Hastings Heritage Trail is open to cyclists and is only two kilometres away."), 1: (heading: "\(aBrd)", detail: "Warblers, thrushes, chickadees, woodpeckers and Great Blue Herons all make their home at Lake St. Peter."), 2: (heading: "\(aBtg)", detail: "Motorboats are permitted on Lake St. Peter and can be launched at the park’s boat launch located at the eastern end of the park."), 3: (heading: "\(aCan)", detail: "Rent a canoe or kayak at the park for the day and explore Lake St. Peter."), 4: (heading: "\(aFsh)", detail: "Lake St. Peter is known for Lake Trout and bass. Although you can fish from the shoreline, for best results try fishing from a boat or canoe."), 5: (heading: "\(aHik)", detail: "\u{2022} Lookout Trail 2.5 km (1.5 hours) Strenuous \n\tThis trail crosses rugged terrain, passes close to a kettle lake and leads to a spectacular lookout over the lake. \n\n\u{2022} Cabin Trail 4km (2 hours) Strenuous \n\tNamed after an abandoned log cabin; this trail branches off the Lookout Trail after the lookout. \n\n\u{2022} Hastings Heritage Trail \n\tLake St. Peter is the northern terminus of the Hastings Heritage Trail. Located two kilometers from the park, the trail is open year-round to hikers, cyclists, horseback riders, skiers, dogsledders, snowmobilers and recreational vehicle operators."), 6: (heading: "\(aHnt)", detail: "Hunting in this park is subject to the Ontario Hunting Regulations. Certain restrictions apply. For more information, contact the park or your local Ministry of Natural Resources office."), 7: (heading: "\(aSwm)", detail: "Lake St. Peter has two sandy beaches, both of which are marked with buoy lines. There are no lifeguards at the beaches and pets are not permitted.")],
                 facilities: [0: (heading: "\(fBF)", detail: "The comfort stations located centrally in the campground and site #28 offer barrier-free access."), 1: (heading: "\(fBL)", detail: "A boat launch is located at the tip of the peninsula, in the most eastern part of the park."), 2: (heading: "\(fCS)", detail: "Enjoy the luxury of a modern comfort station, centrally located and easily accessible from all areas of the campground."), 3: (heading: "\(fDU)", detail: "Lake St. Peter boasts of a beautiful sandy beach with a large picnic area, a volleyball court and horseshoe pits. It is ideal for families."), 4: (heading: "\(fFT)", detail: "Flush toilets are located in the comfort station."), 5: (heading: "\(fL)", detail: "Laundry facilities are located in the comfort station."), 6: (heading: "\(fPSt)", detail: "Located at the park office, the park store sells camping supplies, ice, firewood and park souvenirs."), 7: (heading: "\(fR)", detail: "Canoes and kayaks are available for rent at the park office.")])
