//
//  Petroglyphs.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let petroglyphs = Park(name: "petroglyphs",
                       about: "\u{2022} Largest known concentration of Aboriginal rock carvings (petroglyphs) in Canada, depicting turtles, snakes, birds, humans and more; this sacred site is known as “The Teaching Rocks”\n\u{2022} Visit the Learning Place Visitor Centre to discover the traditions of the Ojibway (Nishnaabe) people through the teachings of the medicine wheel\n\u{2022} Visit bright blue/green McGinnis Lake – one of only a handful of meromictic (layers of water that don’t intermix) lakes in Canada\n\u{2022} Great opportunities for wildlife viewing including Ontario’s only lizard, the Five-lined Skink\n\u{2022} Petroglyphs Operating Hours Daily 10:00am - 5:00pm (No vehicle access after 4:30pm. All vehicles must exit before gates close at 5:30pm). The park is closed on Mondays and Tuesdays in the Spring and Fall with the exception of Holiday Mondays.",
                       general: "\u{2022} Phone: 705-877-255\n\u{2022} Size: 1643.00 h\n\u{2022} Year established: 197\n\u{2022} Park Classification: Cultural Heritage \n\u{2022} Address\n\t2249 Northey’s Bay Rd\n\tWoodvie\n\tK0L 3E0",
                       camping: [0: (heading: "Petroglyphs is a day-use only park. There are no overnight camping facilities. If you are interesting in camping nearby try Lake St. Peter or Silent Lake Provincial Parks.", detail: "Petroglyphs is a day-use only park. There are no overnight camping facilities. If you are interesting in camping nearby try Lake St. Peter or Silent Lake Provincial Parks.")],
                       activities: [0: (heading: "\(aBrd)", detail: "Petroglyphs Provincial Park borders the Peterborough Crown Game Reserve. Birds such as Gray Jays, Wild Turkeys, Ruffed Grouse and various types of hawks are visible in the summer."), 1: (heading: "\(aHik)", detail: "\u{2022} Ratarat Trail - 1 km, moderate  \n\tLocated at the West McGinnis Picnic Area, this short hike meanders through mixed forest and past the beautiful and unique McGinnis Lake. It’s a great area to have a picnic and then go for a short hike. \n\n\u{2022} Marsh Trail - 7 km (2.5 hours) moderate \n\tThis trail winds through dense pine forest and marsh and then climbs - steeply in parts - to uplands.   \n\n\u{2022} Nanabush Trail 5.5 km (1.5 hours) easy \n\tThe trail crosses a variety of terrain from wetlands to rock outcrops. A trail booklet describes native legends: Learn how the White Birch got its black marks, why moss grows on rocks and how the Milky Way was created. \n\n\u{2022} West Day-Use Trail 5 km (1.5 hours) moderate  \n\tThis narrow trail winds through large pine stands and areas of oak and birch. A bridge crosses an ancient streambed made thousands of years ago."), 2: (heading: "\(aNHE)", detail: "The Natural Heritage Education team offers several evening programs during July and August. Each program begins with showing the award winning film “The Teaching Rocks,” at the Learning Place theatre. Visitors are then led to the sacred Petroglyphs Site. Listen to park guides tell stories generations old, relating to First Nations and various understandings as to why these carvings were made. \n\nGuided tours are available for public groups and school groups throughout the operating season.  Group leaders have several options for planning their day; groups may make use of the hiking trails and picnic areas, the group can book to watch the film “The Teaching Rocks” at the Learning Place before going to the Petroglyphs site for a tour.  If a group is on a tight timeframe they may alternatively forego the film and go directly to see the Petroglyphs tour.  Depending on staff availability, a small guided walk-through may be available at the Learning Place in addition to the Petroglyphs tour.  There are currently no fees for group programs however all applicable school bus and/or daily vehicle permits must be purchased to enter the park.  Group programs must book at least one week in advance (preferably earlier) to ensure that a tour will be available.  Groups larger than 30 in number may have split tours to ensure all group members and other park visitors have an enjoyable visit to the Petroglyphs site.  Group leaders should ensure that members of their group/class are prepared to have appropriate respect and appreciation for this spiritually significant site.")],
                       facilities: [0: (heading: "\(fBF)", detail: "Paths from the parking lots to the Learning Place and petroglyph site are barrier-free. A parking lot closer to the petroglyph site and Learning Place is available for senior citizens and others who cannot walk long distances. \n\nOne wheelchair is available at the Learning Place upon request and another is located at the Petroglyph Site. \n\nVisitors with baby strollers will have no problem on the paths leading to the Visitor Centre and petroglyph site, however the hiking trails are too rugged."), 1: (heading: "\(fDU)", detail: "Picnic tables are located throughout the park.  You can picnic at either the east or west side of McGinnis Lake or by the Learning Place.  Vault toilets are available at each of the day-use areas by McGinnis Lake as well as by the main parking lot. \n\nIn order to preserve McGinnis Lake’s unique meromictic nature and scientifically significant sediment record, swimming is prohibited and there are no provisions for any other water-based recreation in the park.  A swimming area outside the park is available at ‘Quarry Bay’ municipal beach on Stoney Lake, 1.5km east of the Petroglyphs Provincial Park entrance."), 2: (heading: "\(fFT)", detail: "Flush toilets are available at the Learning Place."), 3: (heading: "\(fPSt)", detail: "The Park Store, located in the Learning Place, offers souvenirs and refreshments. Browse through nature books for children and adults, as well as books on rock art and Aboriginal culture. Relax in front of the stone fireplace while enjoying a cup of coffee, tea or cider and a snack."), 4: (heading: "\(fPSh)", detail: "A covered picnic shelter is located at the McGinnis Lake East day-use area.")])
