//
//  Pigeon.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let pigeon = Park(name: "pigeon river",
                  about: "\u{2022} Dramatic High Falls, 28 m high and Middle Falls, 6m high\n\u{2022} Scenic views of Lake Superior and the USA shoreline\n\u{2022} Great hiking and walking trails, taking in views of the falls and river gorge and featuring carved metal art sculptures that depict the history of the area\n\u{2022} Evidence of human occupation dating back to 7000 BC\n\u{2022} Part of the Voyageur Boundary Waters Canadian Heritage River\n\u{2022} Day-use park",
                  general: "\u{2022} Phone: (807) 473-9231 (Kakabeka Falls)\n\u{2022} Size: 949.00 ha\n\u{2022} Year established: 1960\n\u{2022} Park Classification: Natural Environment \n\u{2022} Address:\n\tc/o Kakabeka Falls, Box 252\n\tKakabeka Falls\n\tP0T 1W0",
                  camping: [0: (heading: "Pigeon River is a day-use only park. There are no overnight camping facilities. If you are interesting in camping try nearby Sleeping Giant or Kakabeka Falls Provincial Parks.", detail: "Pigeon River is a day-use only park. There are no overnight camping facilities. If you are interesting in camping try nearby Sleeping Giant or Kakabeka Falls Provincial Parks.")],
                  activities: [0: (heading: "\(aBrd)", detail: "Pigeon River marks a transition from the forest of the Great Lakes-St Lawrence Lowlands to boreal forest. This means that bird species of both regions can be found in the park. Birders could see Grey Catbirds, Rose-Breasted Grosbeaks, Common Ravens and Gray Jays."), 1: (heading: "\(aFsh)", detail: "The Pigeon River offers fishing opportunities for pickerel, Northern Pike, Chinook Salmon, Smallmouth Bass, and Rainbow Trout."), 2: (heading: "\(aHik)", detail: "Pigeon River has a number of hiking options for visitors. The Boardwalk, Finger Point and High Falls trails begin at the Ontario Travel Centre. The Middle Falls Walk, Lookout Trail and Logging Road Trail begin at the Middle Falls Access. A trail brochure is available at the Ontario Travel Information Centre. \n\n\u{2022} Boardwalk Trail – 350 m one way (15 minutes round trip) barrier-free access \n\tFollow the accessible boardwalk that takes you to a viewing platform above the Lake Superior shoreline. The beach section of this trail shows evidence of the logging era and the view of Pigeon Bay up to Finger Point Trail. \n\n\u{2022} Finger Point Trail – 2.5 km one way (two hours round trip), steep and rugged terrain in sections \n\tTake a hike up to panoramic views of Lake Superior, the shores of Canada and the USA and to scenic Finger Point. Enjoy all of this from a sculptural bench inspired by Lake Superior. \n\n\u{2022} High Falls Trail – 2 km loop (one hour round trip), steep stairs and hills in sections \n\tHike along a historic logging road to a spectacular view of High Falls; shared by both Ontario and Minnesota. Enjoy a view of Pigeon River’s steep walled gorge and visit the old chimney site. A plaque recognizing the Pigeon River as part of the Boundary Waters Voyageur Canadian Heritage River is located near the chimney site.  Across the river you will see the lookouts of Grand Portage State Park. High Falls is the highest waterfall in Minnesota (but not the highest in Ontario). \n\n\u{2022} Middle Falls Walk – 700 m (20 minute round trip), easy \n\tEnjoy this short walk from the Middle Falls parking area to the beautiful 6 m high Middle Falls. \n\n\u{2022} Lookout Trail – 1.6 km one way (one and a half hour round trip) Steep sections, cliffs and rugged terrain in areas \n\tEmbrace this challenging hike up steep cliff tops to spectacular views over Lake Superior and Pigeon River. On a clear day you can see out to Michigan’s Isle Royale. \n\n\u{2022} Old Logging Road Trail – 2.5 km one way (two hour round trip) Steep and wet sections, use at your own risk as this trail is not maintained. \n\tThis is a challenging hike to a scenic view with a brief side trip to a beaver pond."), 3: (heading: "\(aHnt)", detail: "Signs along the highway indicate areas where hunting is permitted."), 4: (heading: "\(aWA)", detail: "Enjoy Pigeon River Provincial Park’s hiking trails during the winter months, by foot or on snowshoe.")],
                  facilities: [0: (heading: "\(fBF)", detail: "The Boardwalk Trail provides a barrier-free access to a view of the Lake Superior shoreline and Pigeon Bay."), 1: (heading: "\(fDU)", detail: "Enjoy hiking trails, scenic views and sculpted artwork benches. Visitors can hike the many trails or picnic along the river."), 2: (heading: "\(fFT)", detail: "Flush toilets are located at the Pigeon River Ontario Travel Information Centre."), 3: (heading: "\(fPSt)", detail: "A variety of Ontario Parks’ souvenirs can be purchased at the Ontario Travel Information Centre.")])
