//
//  Point.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let point = Park(name: "point farms",
                 about: "\u{2022} Once the site of a popular Victorian resort, this park north of Goderich is perched on a bluff and offers spectacular views of the blue water and beautiful sunsets of Lake Huron.\n\u{2022} The park offers many family-friendly experiences including a large sandy beach with good swimming; 6 km of hiking trails, playgrounds and playing fields.\n\u{2022} Halloween activities (usually on Thanksgiving Weekend) are a special treat for families who decorate campsites and trick or treat throughout the park.\n\u{2022} A camping experience for everyone: RV, trailer, tents.\n\u{2022} Pet friendly area.",
                 general: "\u{2022} Phone: (519) 524-7124\n\u{2022} Size: 307.57 ha\n\u{2022} Year established: 1970\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t82491 Bluewater Highway R.R.3\n\tGoderich\n\tN7A 3X9",
                 camping: [0: (heading: "\(cCar)", detail: "Point Farms offers car camping in two campgrounds: Colborne and Huron. The park also has six large group campsites which accommodate up to 45 people. \n\nThe Colborne Campground is open May to October and can accommodate all equipment types. Several pull-through sites are available. Many campsites offer electrical hook-up.  Amenities such as water taps, comfort stations, laundry facilities, playground, playing field and trails are close by.  Swimming and a pet beach are only a short distance away. \n\nThe Huron Campground is open for the long weekend in May, again in late June to Labour Day and the Thanksgiving weekend. This area is radio-free and offers camping to users with tents to mid-size trailers. Many campsites offer electrical hook-up.  Amenities such as water taps, comfort stations, laundry facilities, playground, and trails are close by.  Swimming and a pet beach are only a short distance away."), 1: (heading: "\(cGrp)", detail: "Point Farms has six group campsites available from approximately the middle of June to early September.  The non-electric sites vary in size and can accommodate nine to 45 people.  A comfort station and vault toilets are available and showers are located in nearby campgrounds. Water taps are available and steps access a nearby beach.  Reservations are accepted 5 months in advance of the arrival date.  To reserve, please call 1-888-ONT-PARK (1-888-668-7275) or 1-519-826-5290 outside of North America."), 2: (heading: "\(cRad)", detail: "Huron Campground is radio-free.")],
                 activities: [0: (heading: "\(aBik)", detail: "Trails and roadways are available for cycling."), 1: (heading: "\(aBrd)", detail: "The park offers a wide range of habitat that hosts a variety of birds. Some of which include turkeys, Red-tailed Hawks, Yellow-bellied Sapsuckers, chickadees, Orioles, Blue Jays."), 2: (heading: "\(aBtg)", detail: "There is no boat ramp within the park."), 3: (heading: "\(aFsh)", detail: "Fishing is popular in the nearby Maitland River and from the pier in the town of Goderich."), 4: (heading: "\(aHik)", detail: "\u{2022} Old Farms Trail – 4km (1.5 hours), loop, easy \n\tTake a leisurely walk through areas that were once old farm fields and orchards. \n\n\u{2022} Under the Bluff Trail - 0.5 km (20 minutes) linear, easy \n\tWalk beneath a mixed wood forest while listening to the birds above and waves from nearby Lake Huron. \n\n\u{2022} Ravine Trail - 1 km (30 minutes) linear, moderate \n\tA more challenging hike with rugged terrain and steep inclines that wind along side of a ravine. Steps to the beach can be accessed at the end of the trail."), 5: (heading: "\(aHnt)", detail: "Hunting for small game is permitted in designated areas after the park closes in October. Contact the Park Office for more information."), 6: (heading: "\(aSwm)", detail: "There is a beautiful natural, sandy beach located north of the point and easily accessible from the Colborne Campground and beach parking lot. Please note: there are no lifeguards posted at the beaches. Pets are only permitted in the designated area."), 7: (heading: "\(aWA)", detail: "The park is closed in the winter however cross-country skiing and hiking is permitted on roads and trails. Snowmobiling on roadways only is also permitted.")],
                 facilities: [0: (heading: "\(fBF)", detail: "Barrier-free campsites are available with a barrier-free comfort station located nearby."), 1: (heading: "\(fCS)", detail: "Comfort stations (complete with showers and flush toilets) are located in Colborne and Huron Campgrounds. A small comfort station with flush toilets is located in the Group Camping area."), 2: (heading: "\(fDU)", detail: "The picnic area is equipped with picnic tables, water tap, large fire ring, vault toilets and a large briquette barbeque. Picnic tables are located along the beach area. The sandy beach is excellent for swimming, but please note: no lifeguards are posted. Volleyball nets are available in beach area."), 3: (heading: "\(fFT)", detail: "Flush toilets are found in the comfort stations located in Colborne, Huron Campgrounds, the Group Camping comfort station as well as the brick vault in the beach day-use area."), 4: (heading: "\(fL)", detail: "Laundry facilities are available at the comfort stations in Colborne and Huron Campgrounds."), 5: (heading: "\(fPSt)", detail: "The Park Office sells Ontario Parks’ merchandise, souvenirs and a few camper supplies. \n\nIce, firewood and groceries are available outside of the park at a nearby general store, or a short drive into Goderich.")])
