//
//  Rainbow.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let rainbow = Park(name: "rainbow falls",
                   about: "\u{2022} View the cascading waters as they plunge over the rock ledges of Rainbow Falls on their way to Lake Superior.\n\u{2022} Hike the trails which lead to panoramic views of Lake Superior and Whitesand Lake.\n\u{2022} The Rainbow Falls Trail located within the park is part of the 52 km Casque Isles Trail section of the Voyageur Trail that runs between the communities of Terrace Bay, Schreiber and Rossport.\n\u{2022} Camp at our Whitesand Lake location or along the rugged shore of Lake Superior at the Rossport Campground location.\n\u{2022} Take part in a variety of water sports in the warmer inland waters of Whitesand Lake or brave the cooler Lake Superior waters at the Rossport Campground.\n\u{2022} Located alongside the Lake Superior National Marine Conservation Area (Parks Canada).\n\u{2022} Shake out the cobwebs with a hike along the Casque Isle Trail.",
                   general: "\u{2022} Phone: Spring/Summer (807) 824- 2298 Fall/Winter (807) 825-3403\n\u{2022} Size: 575.59 ha\n\u{2022} Year established: 1963\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\tP.O. Box 280, 1004 Hwy 17\n\tTerrace Bay\n\tP0T 2W0",
                   camping: [0: (heading: "\(cCar)", detail: "\u{2022} Whitesand Lake Campground \n\tThe Whitesand Lake Campground is located on the north side of Highway 17. It offers almost 100 campsites, half of which have electrical service. A comfort station is located centrally within the campground for easy access. The Maggie and Selim Campground loops offer electrical campsites. Many sites in Selim are pull-through and relatively level. \n\nThe Whitesand loop offers sites that are wooded on three sides and well-buffered from neighbouring sites. There are no electrical sites in Whitesand but many are pull-through. \n\nThe Lakeside loop has no electrical sites but its campsites are up on a hill and offer lovely views of the lake through trees. \n\nYou will find the gate house located at the entrance to the Rossport Campground for quick and easy registration. \n\n\u{2022} Rossport Campground \n\tRossport Campground is located approximately 5 kilometers west of Whitesand Lake Campground, on the south side of Highway 17, situated along the shoreline of the pristine Lake Superior. This is a much smaller campground, offering 36 campsites (23 electrical). A comfort station is centrally located within the campground for easy access. \n\nCampsites at Rossport are more open then at Whitesand Lake being located in a grassy birch grove but offer great views of Lake Superior. This campground is very popular with return visitors.")],
                   activities: [0: (heading: "\(aBik)", detail: "Bicycles are a great way to explore the campground and are encouraged as a mode of transportation within the park. They are permitted on park roads but not on the trail system. Bicycles (with helmets) are available for rent at Rainbow Falls."), 1: (heading: "\(aBtg)", detail: "Recreational boating is popular on Whitesand Lake. Boaters are requested to avoid the water above the falls and around designated swimming areas. As a safety feature, buoy lines mark these areas. If you plan to boat on Lake Superior, where larger craft are advised, please take appropriate safety precautions, for example provide someone with a trip plan."), 2: (heading: "\(aCan)", detail: "The calm waters of Whitesand Lake are ideal for canoeing. An annual canoe regatta is held in July. Canoes can be rented at Whitesand Lake. Canoes and kayaks can also be rented from outfitters in Rossport.  Visitors to the Rossport Campground might try sea kayaking along the shoreline of Lake Superior."), 3: (heading: "\(aFsh)", detail: "For Brook Trout, cast your line in Whitesand River. Lake Trout and bass are more likely catches in Whitesand Lake. For Lake Trout, Rainbow Trout, salmon and whitefish, head for Lake Superior."), 4: (heading: "\(aHik)", detail: "\u{2022} Back Forty Trail 5.6 km return, 2.5 hours, strenuous \n\t This old road climbs steeply to a view of Whitesand Lake with Lake Superior as a backdrop. \n\n\u{2022} Rainbow Falls Trail 3 km, 1.5 hours, strenuous \n\tA series of stairs and platforms follow Rainbow Falls down to a sturdy bridge over the cascades. The trail then leaves the river and climbs to a lookout overlooking \n\n\u{2022} Lake Superior and Whitesand Lake.  Superior Trail 4.8 km return, 2 hours, moderate \n\t This trail winds along the top of a granite ridge to a beautiful view of Lake Superior. \n\n\u{2022} Voyager Hiking Trail - Casque-Isles Section, 52km, 5 days, strenuous \n\t This spectacular, rugged trail links Terrace Bay, Schreiber and Rossport and passes through Rainbow Falls Provincial Park. Many park visitors join the trail at the end of the Rainbow Falls Trail and make the journey to the village of Rossport."), 5: (heading: "\(aSwm)", detail: "The warm, inland waters of Whitesand Lake are ideal for family swimming. The lake has two sandy beaches with designated swimming areas. Only the hardy brave the cold waters of Lake Superior; rocky outcrops and cobblestone beaches are the standard at Rossport Campground."), 6: (heading: "\(aWA)", detail: "Although the park is closed in winter, campground roads are accessible for cross-country skiing.")],
                   facilities: [0: (heading: "\(fBF)", detail: "The comfort stations at Whitesand Lake and Rossport Campgrounds have barrier-free access."), 1: (heading: "\(fBL)", detail: "A boat launch is located at the east beach area of the Whitesand Lake Campground."), 2: (heading: "\(fCS)", detail: "A boat launch is located at the east beach area of the Whitesand Lake Campground."), 3: (heading: "\(fDU)", detail: "Whitesand Lake Campground has three picnic and day-use areas at East Beach, West Beach and the Falls. All three locations offer lakefront access and great views of Whitesand Lake.   \n\nAt Rossport Campground, the lakefront day-use and picnic areas offer a panoramic view of the sheltering Rossport Islands in Lake Superior, a group of islands that make this area such a water/nature lover’s paradise."), 4: (heading: "\(fFT)", detail: "Flush toilets are located at the comfort stations in Whitesand Lake and Rossport Campgrounds."), 5: (heading: "\(fL)", detail: "Laundry facilities are located at the comfort stations in Whitesand Lake and Rossport Campgrounds."), 6: (heading: "\(fPSt)", detail: "Firewood, ice and park souvenirs are available at the park store located at the gatehouse at Rossport Campground."), 7: (heading: "\(fPSh)", detail: "Organized groups can reserve picnic shelter facilities at Whitesand Lake Campground and Rossport Campground day-use area.  Please contact the park to reserve."), 8: (heading: "\(fR)", detail: "Canoes, paddle boats, bicycles, and water bikes are all available for rent. Ask at the gate house.")])
