//
//  Rene.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let rene = Park(name: "rene brunelle",
                about: "\u{2022} A camping experience for everyone: RV, tent and trailer camping located near Kapuskasing. Seasonal site rental available.\n\u{2022} Four sandy beaches on Remi Lake, a float plane base for many years in the early 1900s\n\u{2022} Great Walleye, Northern pike and Small-mouth bass fishing along with a fish cleaning station.\n\u{2022} New boat launch just outside the park and fish cleaning station\n\u{2022} Two great hiking trails one which tells of a 1922 bush pilot plane crash\n\u{2022} Motorboat, canoe, kayak and bike rentals\n\u{2022} Excellent bird watching and wildlife viewing",
                general: "\u{2022} Phone: 705-367-2692\n\u{2022} Size: 3015.00 ha\n\u{2022} Year established: 1957\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\tPO BOX 670, 613 Front Street\n\tHearst\n\tP0L 1N0",
                camping: [0: (heading: "\(cCar)", detail: "The Park has 88 secluded campsites, the majority with electricity, and all at a convenient distance from hot showers, laundromat and flush toilets. Seasonal campsites are also available."), 1: (heading: "\(cGrp)", detail: "One of the best group campsites in any park, this group site is beautiful, with its own beach that faces the undeveloped and wild north shore of the park and Remi Lake.  The site is separate from the main campground, is well landscaped and slopes down gently to the sand at the water’s edge. It can accommodate 20 trailers or more and is suitable for weddings, reunions and work retreats.  Reservations can be made during regular season by calling the park at 705-367-2692."), 2: (heading: "\(cRof)", detail: "Please check the website for the most up to date information on roofed accommodations.")],
                activities: [0: (heading: "\(aBik)", detail: "There are no dedicated bike trails in the park - only park roads are available for biking, but just outside the park entrance are the Moonbeam Nature trails that offer kilometers of paved cycling, single track mountain biking and excellent bike riding."), 1: (heading: "\(aBrd)", detail: "This is an ecological region known as the Boreal Forest, often called the songbird nursery because so many nest here each summer. Many species of birds can be seen and heard throughout the park, even from your campsite. Warblers may be the most colourful and have the prettiest songs, but there are also many types of sparrows, flycatchers, thrushes, finches and woodpeckers. Spruce Grouse and their chicks are sometimes seen crossing park roads – keep and eye out for them and drive slowly!"), 2: (heading: "\(aBtg)", detail: "Launch your boat and enjoy the ample boating opportunities on Remi Lake. A modern boat launch is located just off Provincial Park Road south of the park entrance. The park has docking facilities available for mooring campers’ boats."), 3: (heading: "\(aCan)", detail: "There are excellent canoeing opportunities on Remi Lake, especially exploring the park’s undeveloped north shore."), 4: (heading: "\(aFsh)", detail: "Fish for Walleye, Northern pike, Small-mouth bass, Lake whitefish and Yellow perch in Remi Lake. Then back on shore, clean your catch at the fish cleaning hut close to the floating docks."), 5: (heading: "\(aHik)", detail: "\u{2022} La Vigilance Trail 1.5 km (1hour) easy \n\t Discover this park’s place in the colourful history of northern aviation and the history of Remi Lake as a base for floatplanes in the 1920s, when aviation was in its infancy. \n\n\u{2022} Spruce Lowland Trail 1.6 km (1 hour) easy \n\tThis trail offers a great opportunity to explore the Boreal Forest, passing through stands made up of Black Spruce, Balsam Fir, Trembling Aspen or Poplar and White Birch. These are common trees of the Boreal Forest, but the trail also passes through a stand of Black Ash growing in moist and poorly drained soil, which is found at the northern tip of its range and is uncommon here. The trail passes a very old spruce bog, with a range of wetland plants that thrive there, like Sphagnum Moss, Labrador Tea and Tamarack trees."), 6: (heading: "\(aSwm)", detail: "The four sandy beaches, shallow, clear water and buoyed areas are perfect for family swimming. There are change facilities, a full-size sand volleyball court at the Day Use Area, and a place to play horseshoes.")],
                facilities: [0: (heading: "\(fBF)", detail: "The comfort station and showers are barrier-free, and we offer a barrier free campsite."), 1: (heading: "\(fBL)", detail: "A modern boat launch is located just off Provincial Park Road south of the park entrance. The park has docking facilities available for mooring campers’ boats."), 2: (heading: "\(fCS)", detail: "Our comfort station has flush toilets, mirrors, sinks, hand sanitizer and hand dryers, showers, and is barrier-free."), 3: (heading: "\(fDU)", detail: "Our day use area offers lots of room for picnics, with shaded areas along the shore, as well as a large children’s playground."), 4: (heading: "\(fFT)", detail: "All park outhouses have flush toilets, sinks, mirrors, and hand sanitizer."), 5: (heading: "\(fL)", detail: "There are washers and dryers, laundry tub and a laundry soap dispenser with common detergents for sale at all comfort stations."), 6: (heading: "\(fPSt)", detail: "The Park Store is found in the Main Gate House. A variety of supplies are available, from key needs like ice, bug spray and suntan lotion, to coffee, ice-cream and candy. You will also find a variety of Ontario Parks merchandise for the whole family."), 7: (heading: "\(fPSh)", detail: "Relax in the shade of our Picnic shelter on Phipps Point there is always a gentle breeze blowing and a great view of the lake."), 8: (heading: "\(fR)", detail: "The park rents motorboats, canoes, kayaks, peddle boats and bikes.")])
