//
//  Rideau.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let rideau = Park(name: "rideau river",
                  about: "\u{2022} Located on the historic Rideau Waterway, a UNESCO World Heritage Site\n\u{2022} Enjoy family camping on nice level, shaded campsites with all of the amenities nearby\n\u{2022} Great base for exploring Ottawa; only 40 minutes away or the small towns that line the Rideau.\n\u{2022} Explore the waters of the Rideau by canoe or motorboat; perhaps fish for muskie or bass",
                  general: "\u{2022} Phone: 613 258-2740\n\u{2022} Size: 97.93 ha\n\u{2022} Year established: 1963\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t2680 Donnelly Drive\n\tKemptville\n\tK0G 1J0",
                  camping: [0: (heading: "\(cCar)", detail: "Rideau River has almost 200 level campsites, located in a mature forest. One-quarter have electrical service and two barrier-free sites have electricity and water. Nine group campsites accommodate large groups. Two comfort stations with showers are centrally located and drinking water and vault toilets are throughout the campground."), 1: (heading: "\(cGrp)", detail: "Rideau River has seven group campsites that accommodate groups up to 125 people. Two sites are located near the beach and all are within walking distance of the beach. Water taps and vault toilets are available on site. Proximity to comfort stations varies depending on the site. Reservations can be made by calling the park directly at (613) 258-2740.")],
                  activities: [0: (heading: "\(aBik)", detail: "There are no dedicated bicycle trails at Rideau River but bicycles are permitted on campground roads."), 1: (heading: "\(aBrd)", detail: "Watch for waterfowl, Great Blue Herons and osprey along the Rideau River in the park. The Rideau Bird Sanctuary, west of Merrickville, provides excellent birding opportunities."), 2: (heading: "\(aBtg)", detail: "Power boats are allowed on the Rideau River. There are many fascinating points of interest to explore. Venture upstream, 20 km to Burritts Rapids lockstation or downstream, 20 km to Long Reach lockstation in Manotick. Take a trip through the locks for a real adventure! Marinas are located along the way. \n\nVisit http://www.rideau-info.com/canal/paddling/index.html#guides for suggested points of interest and click on guides 13 or 14 for day trips from the park."), 3: (heading: "\(aCan)", detail: "Paddling on the Rideau \n\tThe Rideau River is part of the Rideau Canal UNESCO World Heritage Site. This waterway offers lots of opportunities for paddlers wanting to explore. Visit this website and click on paddling guide 14 for points of interest near the park, for example, a 7 km paddle up Kemptville Creek to the town of Kemptville."), 4: (heading: "\(aFsh)", detail: "This section of the Rideau River is very popular for muskie anglers. Good opportunities also exist for bass, walleye and panfish. Ask at the Park Office about Tackleshare, a fishing rod and reel loaner program."), 5: (heading: "\(aHik)", detail: "\u{2022} Shoreline Trail – 1.5 km, linear, easy \n\tHike the Shoreline Trail and look for wildlife along the riverbank such as frogs, turtles and Great Blue Herons."), 6: (heading: "\(aSwm)", detail: "The Main Beach, a sandy beach on the Rideau River, is located next to the campground. The swimming area is marked with buoys and has a gradual drop-off. Please note: there are no lifeguards posted at the beaches. Amenities include picnic tables and a picnic shelter in the shady, grassy area. Flush toilets and change rooms are on site as well.")],
                  facilities: [0: (heading: "\(fBF)", detail: "The Main Beach, a sandy beach on the Rideau River, is located next to the campground. The swimming area is marked with buoys and has a gradual drop-off. Please note: there are no lifeguards posted at the beaches. Amenities include picnic tables and a picnic shelter in the shady, grassy area. Flush toilets and change rooms are on site as well."), 1: (heading: "\(fBL)", detail: "A boat launch provides access to the Rideau River."), 2: (heading: "\(fCS)", detail: "Two comfort stations complete with showers and flush toilets, are centrally located in the campground. The Main Beach also has flush toilets."), 3: (heading: "\(fDU)", detail: "Picnic tables are located at the Main Beach. There is a separate beach area with picnic tables available for rental by groups. Contact the park directly (613-258-2740) for more information or to reserve."), 4: (heading: "\(fFT)", detail: "Flush toilets are found in the two campground comfort stations and at the Main Beach."), 5: (heading: "\(fL)", detail: "Laundry facilities are located in one comfort station."), 6: (heading: "\(fPSt)", detail: "The Park Office stocks ice cream, firewood, ice, canoe rentals, worms and park souvenirs."), 7: (heading: "\(fPSh)", detail: "A picnic shelter is located at the main beach. It is available on a first-come, first-served basis."), 8: (heading: "\(fR)", detail: "Canoes can be rented from the Park Office and picked up at the boat launch. Personal Floatation Devices (PFDs) are also available for loan with a $25 refundable deposit. Fishing rod and reel are available free to loan from the Park Office as part of the Tackleshare program.")])
