//
//  Rock.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let rock = Park(name: "rock point",
                about: "\u{2022} Exposed fossils of a coral reef dating back to over 350 million years embedded in limestone shelf along the beach\n\u{2022} Viewing platform above sand dunes\n\u{2022} 2 km hiking trail\n\u{2022} 1 km of sandy beach\n\u{2022} Fall monarch butterfly migration",
                general: "\u{2022} Phone: (905) 774-6642\n\u{2022} Size: 187.00 ha\n\u{2022} Year established: 1957\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t215 Niece Rd\n\tDunnville\n\tN1A 2X5",
                camping: [0: (heading: "\(cCar)", detail: "There are four areas for car camping in Rock Point: Kinsey, Niece, Minor and Lookout. \n\nKinsey and Niece camping areas offer electrical campsites and can accommodate equipment ranging from large trailers to tents. Amenities such as water taps, comfort stations and laundry facilities are close by. Swimming, access to hiking trails and the Park Store are nearby. \n\nMinor and Lookout do not offer electrical service but the campsites accommodate tents to small trailers. Water taps and comfort stations complete with laundry facilities are close by. Waterfront trails are easily accessed taking you to the park beach or to the limestone shelf that juts out into Lake Erie."), 1: (heading: "\(cGrp)", detail: "Rock Point has three group campsites available. Each site can accommodate up to 35 to 40 people and has a fire pit and picnic table. Water tap and flush toilets are close by. It is a short walk to the beach and Park Store. To reserve, please call 1-888-ONT-PARK (1-888-668-7275) or 1-519-826-5290 outside of North America.")],
                activities: [0: (heading: "\(aBrd)", detail: "Over 260 bird species have been recorded in the park."), 1: (heading: "\(aBtg)", detail: "Boats are permitted on Lake Erie but there is no boat launch or docking within the park."), 2: (heading: "\(aFsh)", detail: "Fish of the limestone rock outcrop for Large and Smallmouth Bass and pickerel."), 3: (heading: "\(aHik)", detail: "\u{2022} Woodlot Trail - 2 km \n\tExplore a variety of forest and wetland communities including Carolinian, Oak Savanna and old farm fields that are slowly being reclaimed by the forest. The trail will lead you to a viewing platform built on top of the park’s sand dunes overlooking Lake Erie. \n\n\u{2022} Pet Exercise Trail - .5 km linear trail."), 4: (heading: "\(aHnt)", detail: "Fall waterfowl hunting is permitted after the park closes. For more information please contact the park (905) 774-6642"), 5: (heading: "\(aNHE)", detail: "Fun and active educational programs are offered by park staff. Take a hike with the naturalist, join staff at a slide show or stop by an evening campfire program to learn about the park’s natural and cultural environment."), 6: (heading: "\(aSwm)", detail: "There is a 1 km natural sand/pebble beach that runs from the campground to the day-use area. The beach gradually drops off and is not marked with a buoy line. Please note: there are no lifeguards posted at the beach. Pets are only permitted on the far west end of the beach in the day-use area.")],
                facilities: [0: (heading: "\(fBF)", detail: "Barrier-free access is available at all comfort stations, park office and park store."), 1: (heading: "\(fCS)", detail: "Barrier-free access is available at all comfort stations, park office and park store."), 2: (heading: "\(fDU)", detail: "Day-use is on the west end of the park and runs along the park’s beach. Picnic tables and washroom facilities are available. Gas barbeques are available for rent from the park store that is located in this area. Please note that there are no lifeguards are on duty."), 3: (heading: "\(fDU)", detail: "Day-use is on the west end of the park and runs along the park’s beach. Picnic tables and washroom facilities are available. Gas barbeques are available for rent from the park store that is located in this area. Please note that there are no lifeguards are on duty."), 4: (heading: "\(fFT)", detail: "Flush toilets are found in all comfort stations, including the day-use and group camping areas."), 5: (heading: "\(fL)", detail: "Both comfort stations found in the Kinsey and Minor Camping areas have coin operated washing machines and driers. Laundry soap dispensers are also available."), 6: (heading: "\(fPSt)", detail: "The park store is located in the day-use area and carries a variety of camping items, ice, groceries, gifts and souvenirs, snacks, hot food and drinks."), 7: (heading: "\(fPEA)", detail: "Pets are permitted on the far west end of the beach in the day-use area."), 8: (heading: "\(fPSh)", detail: "There is one picnic shelter located in the day-use area. This shelter can be reserved by contacting the park office (905) 774-6642."), 9: (heading: "\(fR)", detail: "Bicycles and barbeques are available for rent from the park store.")])
