//
//  Samuel.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let samuel = Park(name: "samuel de champlain",
                  about: "\u{2022} Located on historic Mattawa River fur trade route in the scenic Mattawa Valley\n\u{2022} Great hiking trails with scenic views – outstanding fall colours\n\u{2022} Voyageur adventure interpretive experience – try paddling a Voyageur canoe\n\u{2022} New Mattawa River Visitor Centre (2011) depicting historical, cultural and natural features\n\u{2022} Excellent opportunities for exploration by canoe\n\u{2022} Natural Heritage Education programs for all ages",
                  general: "\u{2022} Phone: (705) 744-2276\n\u{2022} Size: 2550.00 ha\n\u{2022} Year established: 1967\n\u{2022} Park Classification: Natural Environment \n\u{2022} Address:\n\t6905 Highway 17 east PO Box 147\n\tMattawa\n\tP0H 1V0",
                  camping: [0: (heading: "\(cCar)", detail: "Babawasse Campground is comprised of 74 campsites, all of which have 15 and 30 amp electrical connections. A small comfort station provides flush toilets, showers and laundry facilities and is centrally located. Playground equipment is offered at the small private camper’s beach. The name “Babwasee” finds its roots in the Ojibway language meaning “a lake is seen through the woods”. \n\nJingwakoki Campground offers 137 campsites, 20 of which have 15 and 30 amp electrical connections. A comfort station located at the campground entrance provides, flush toilets, showers and laundry facilities. Playground equipment is offered at the shallow, sandy beach located on the northwest shore of Moore Lake. The Ojibway name Jingwakoki aptly describes the campground setting meaning “pine forest or tall pines”"), 1: (heading: "\(cGrp)", detail: "The Neiashi group campsite is available to larger, organized groups who prefer to camp in a more remote setting away from the car campground area.  The site can accommodate both trailers and tent, and has a water tap and basic toilet facilities.  The site is located on the Amable du Fond River.")],
                  activities: [0: (heading: "\(aBik)", detail: "Cycling is a popular activity on the main park roads."), 1: (heading: "\(aBrd)", detail: "A variety of songbirds, such as warblers, and other avian species such as Bald Eagles, hawks and Great Blue Herons are regularly sighted in the park."), 2: (heading: "\(aBtg)", detail: "Motorboats are permitted on Moore Lake, however a maximum horsepower rating of 10 HP is in effect."), 3: (heading: "\(aCan)", detail: "Moore Lake and the upriver section of the Amable du Fond River provide quiet canoeing opportunities to explore and view wildlife. \n\nAt Long Lake, you can paddle beside large cliffs while enjoying the serenity of a motor-free environment. \n\nThe Mattawa River Provincial Park and Canoe Route extends from Trout Lake, near North Bay and ends in the community of Mattawa, passing through the centre of Samuel de Champlain Provincial Park. The portion of river from Pimisi Bay to Samuel de Champlain offers the most challenging rapids and also some of the most spectacular scenery including beautiful Parreseux Falls."), 4: (heading: "\(aFsh)", detail: "A variety of fish species can be found in Moore Lake including Large and Smallmouth Bass, Walleye (Pickerel), Northern Pike and muskellunge."), 5: (heading: "\(aHik)", detail: "\u{2022} Etienne System Trails: four loops ranging in length from 2.5 to 9 km; strenuous \n\tDiscover scenic views of the Mattawa River while traversing challenging terrain. \n\u{2022} Kag Trail: 2.5 km loop; difficult with steep climbs \n\tThis trail travels through several ecosystems, including tall majestic Red Pine forests, Gem Lake and oak highlands. \n\u{2022} Wabashkiki Trail: 1 km loop; easy \n\tExplore a marsh and its resident wildlife on this trail and boardwalk set on a peninsula in the middle of Moore Lake. \n\u{2022} Forestry Research Trail: 1 – 2 km loop; easy \n\tThis trails winds its way through active forestry research plots. A trail guide is available at the Visitor Centre."), 6: (heading: "\(aNHE)", detail: "The park’s natural heritage education staff provides interactive programming suitable for all ages. Guided hikes, children’s programs, spirit nights, musical performances and campfire sing-alongs are just a few of the programs provided during the months of July and August. Visitors can also try their hand at paddling a replica Voyageur canoe.  The Mattawa River Visitor Centre showcases the area’s natural and human history with a variety of exhibits and houses a large birchbark freighter canoe."), 7: (heading: "\(aSwm)", detail: "The refreshing, clear waters of Moore Lake provide a relaxing way to spend a warm summer day. Small camper beaches are located in both Jingwakoki and Babawasse Campgrounds. The Bagwa Day-Use area also has a large sandy beach. A free Personal Floatation Device (PFD) loan program is available at the Park Store.")],
                  facilities: [0: (heading: "\(fBF)", detail: "Barrier-free sites are located in close proximity to each campground comfort station and are available through the Ontario Parks central reservation service."), 1: (heading: "\(fBL)", detail: "Boat launches in both Jingwakoki and Babawasse Campgrounds provide access Moore Lake."), 2: (heading: "\(fCS)", detail: "Both Jingwakoki and Babawasse Campgrounds offer comfort stations complete with showers, flush toilets and laundry facilities."), 3: (heading: "\(fDU)", detail: "The Bagwa Day-Use area provides a large sand beach, playground equipment and a large grassed picnic area suitable for special events."), 4: (heading: "\(fFT)", detail: "Both the comfort stations and small facilities interspersed throughout the campground contain flush toilets."), 5: (heading: "\(fL)", detail: "Coin-operated washers and dryers may be found at both campground comfort stations."), 6: (heading: "\(fPSt)", detail: "The Park Store offers souvenir merchandise, books, maps, canoe and kayak rentals, ice, firewood and a small selection of basic camper supplies. The Park Store is open daily during the months of July and August."), 7: (heading: "\(fPEA)", detail: "There is a road that that is not well-travelled that leads from Jingwakoki Campground out to our group camping area and back out along the Amable du Fond River to a gate at Highway 17 that is used as a pet exercise area."), 8: (heading: "\(fR)", detail: "Rental canoes and kayaks are conveniently located in each campground on the shores of Moore Lake. Rental arrangements can be made at the Park Store and include Personal Floatation Devices (PFDs) paddles and a boat safety kit."), 9: (heading: "\(fVC)", detail: "The Mattawa River Visitor Centre showcases the natural and cultural history of Samuel de Champlain Provincial Park and the Mattawa River valley. Regular hours and the opportunity to speak with a Park Naturalist are available during the months of July and August.")])
