//
//  Sandbar.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let sandbar = Park(name: "sandbar lake",
                   about: "\u{2022} Beautiful sandy beach with gently sloping swimming area that’s great for kids\n\u{2022} Transitional forest with plants and animals from the boreal forest as well as those of the Great Lakes-St. Lawrence Lowlands\n\u{2022} Erratic boulders are strewn amidst the trees- evidence of the power of glaciers\n\u{2022} Gateway to challenging northern canoe routes",
                   general: "\u{2022} Phone: (807)934-2995 summer (807)223-7535 winter\n\u{2022} Size: 8053.00 ha\n\u{2022} Year established: 1970\n\u{2022} Park Classification: Natural Environment \n\u{2022} Address:\n\tBox 730, 479 Government Street\n\tDryden\n\tP8N 2Z4",
                   camping: [0: (heading: "\(cCar)", detail: "Sandbar Lake is a small campground. One-third of its almost 75 campsites are electrified. Campsites can accommodate equipment ranging from tents only to large trailers.  Campsites are partially shaded with some offering a tantalizing glimpse of the lake. Amenities such as water taps, comfort stations and laundry facilities are close by.  Swimming, boating, great fishing and hiking are only a short distance away."), 1: (heading: "\(cGrp)", detail: "Sandbar Lake has two group campsites that vary in size and can accommode from 15 to 100 people.  Water taps and vault toilets are on site. The area is within walking distance of comfort stations, the beach and hiking trails. \n\nCall the park directly to reserve (807) 934-2995.")],
                   activities: [0: (heading: "\(aBik)", detail: "Cycling is a popular way to wander through the majestic 300 year old White Pines and Red Pines that grace the campground. Kids are reminded to wear their helmets."), 1: (heading: "\(aBtg)", detail: "Explore the delights of Sandbar Lake by boat. A boat launch is located centrally in the park."), 2: (heading: "\(aCan)", detail: "Launch your canoe or rent one at the Park Office and you can paddle right onto Sandbar Lake. There are options for both the day paddler and long distance paddler. \n\u{2022} Sandbar-Press Lake Canoe Loop: 160km, 9-12 days \n\tThis route passes by several pictograph sites. \n\u{2022} Canoe Route 79: 4-5 days \n\tPaddle through some of the finest fishing lakes in Northern Ontario. \n\nContact the park for more information about these canoe routes. Please note that these routes are not regularly maintained."), 3: (heading: "\(aFsh)", detail: "The lakes in and around the park teem with Northern Pike, walleye and Smallmouth Bass. A fish-cleaning station, with lights, running water and cutting tables is located by the boat launch."), 4: (heading: "\(aHik)", detail: "\u{2022} Silhouette Trail - 2km, moderate \n\tThis trail weaves its way through Jack Pine woods, aspen forests and wetlands. Along the trail you will see a variety of plant and wildlife silhouettes with descriptive information sheets. \n\u{2022} Red Pine Trail - 0.5km, easy \n\tThis small self-guided trail is great for a short walk through the wilderness. It takes you through a natural Red Pine stand and along the trail you will see remains of burnt trees, a result of a forest fire in the early 1900s. \n\u{2022} Rockcliff Trail – 4km, moderate \n\tThis trail will familiarize you with some of the unique natural and historical features of the park."), 5: (heading: "\(aHnt)", detail: "Hunting is allowed in the Sandbar Lake park additions. Please check with appropriate Ministry of Natural Resources personnel to ensure proper park boundaries are respected."), 7: (heading: "\(aSwm)", detail: "The sandy beach and gradual drop off make this a great swimming location for families. The beach is located in the day-use area and the swimming area is marked with buoys. Please note that there are no lifeguards posted at the beaches and pets are not permitted.")],
                   facilities: [0: (heading: "\(fBF)", detail: "The comfort station at the campground offers barrier-free access. There is also a wheelchair ramp at the day-use area."), 1: (heading: "\(fBL)", detail: "A boat launch is found in the campground by the fish cleaning hut."), 2: (heading: "\(fCS)", detail: "A comfort station with showers and flush toilets is located in the main campground."), 3: (heading: "\(fDU)", detail: "The day-use area has a sandy beach with buoyed swimming areas, playground, picnic shelter, water taps and vault toilets. Please remember that there are no lifeguards on duty at the beach so children should be supervised."), 4: (heading: "\(fFT)", detail: "Flush toilets are located in the comfort station at the campground."), 5: (heading: "\(fL)", detail: "Laundry facilities can be found at the comfort station."), 6: (heading: "\(fPSt)", detail: "Located in the Park Office, the shop features clothing items, souvenirs, camper supplies, ice and firewood. \n\nGroceries are available outside of the park in Ignace 11 km south of the park on Highway 599."), 7: (heading: "\(fPSh)", detail: "There is one picnic shelter in the day-use area beside the beach. The shelter is available on a first-come, first-served basis."), 8: (heading: "\(fR)", detail: "Canoes, kayaks, and motorboats are available for rent. \n\nPersonal Floatation Devices (PFDs) are also available for loan with a $25 refundable deposit.")])
