//
//  Sauble.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let sauble = Park(name: "sauble falls",
                  about: "\u{2022} The perfect base camp for visits to nearby Sauble Beach and to explore the Bruce Peninsula.\n\u{2022} An exceptional picnicking site including a children’s adventure playground.\n\u{2022} Spring and fall spawning runs for Rainbow Trout and Chinook salmon. Watch the fish struggle over each ledge of this cascading waterfall to spawn upstream.\n\u{2022} Excellent fishing.\n\u{2022} This historic falls used to power a timber mill and generating station. Now flanked by immature forest, the falls are the end of the Rankin River canoe route - ideal for novice canoeists.",
                  general: "\u{2022} Phone: 519-422-1952\n\u{2022} Size: 20.24 ha\n\u{2022} Year established: 1971\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t1400 Sauble Falls Road\n\tSouth Bruce Peninsula\n\tN0H 2T0",
                  camping: [0: (heading: "\(cCar)", detail: "Sauble Falls is a smaller park with a range of campsites including some with electrical service in two campgrounds.  All sites are convenient to the showers and comfort stations."), 1: (heading: "\(cGrp)", detail: "There are two group camping areas, one that accommodates 15-20 people and another that accommodates30-40.  Outhouses are on site and water taps nearby. Both are within a five minute drive to the beach and a three minute walk to the comfort station. To reserve, please call 1-888-ONT-PARK (1-888-668-7275) or 1-519-826-5290 outside of North America."), 2: (heading: "\(cRad)", detail: "West Campground is radio-free.")],
                  activities: [0: (heading: "\(aBik)", detail: "Cycling is permitted on park roads. You may wish to travel by bicycle to the beach less than 3 km from the park."), 1: (heading: "\(aBrd)", detail: "Osprey can often be seen at the mouth of the Sauble River and are known to nest in the Isaac Lake area. Many bird species can be found throughout the campgrounds and along the river."), 2: (heading: "\(aCan)", detail: "Canoe rentals are available on the north side of the Sauble River near the parking lot. \n\nCanoe launch facilities are located at the portage on the north side of the falls for a leisurely paddle up the Sauble River. Many paddle from Sauble Falls to Country Road 8. When traveling downstream, this 10 km length will take about 3.5 hours. Here the river winds through farmlands and steep sand dunes. The Rankin River joins the Sauble just above the canoe rental and bridge at Sauble Falls. \n\nAsk park staff for advice on paddling the river."), 3: (heading: "\(aFsh)", detail: "Anglers will find the areas adjacent to the falls to be excellent for trout and salmon fishing in the spring and fall. The area of the falls is closed to fishing year-round."), 4: (heading: "\(aHik)", detail: "\u{2022} Sauble Trail 2.5km (2 hours) easy  \n\tThis trail travels primarily through a Red Pine plantation. An interpretive leaflet explains current and historic forest management practices in the area. Bicycles are not allowed on this trail which travels through an area of ancient sand dunes.")],
                  facilities: [0: (heading: "\(fBF)", detail: "Barrier-free showers and flush toilets are located in each campground."), 1: (heading: "\(fCS)", detail: "Showers are located at the comfort stations which are centrally located in each of the three campgrounds."), 2: (heading: "\(fDU)", detail: "The picnic shelter is the perfect backdrop for group picnicking. Nearby is the children’s adventure playground. Platforms overlooking the Sauble River provide excellent views of Sauble Falls and the spring and fall Rainbow Trout and salmon migration upstream to spawning grounds."), 3: (heading: "\(fFT)", detail: "Flush toilets are located in each campground."), 4: (heading: "\(fL)", detail: "The park offers laundry facilities."), 5: (heading: "\(fPSt)", detail: "The shelter is very popular and is available on a first-come, first-served"), 6: (heading: "\(fR)", detail: "Canoes, paddle boats and kayaks can be rented adjacent to the Day-Use area.")])
