//
//  Selkirk.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let selkirk = Park(name: "selkirk",
                   about: "\u{2022} Quiet campground with grassed campsites\n\u{2022} Wheeler’s Walk Trail with boardwalk across marsh wetland\n\u{2022} Large day-use picnic area\n\u{2022} 15 minutes east of Port Dover\n\u{2022} Monthly camping offered",
                   general: "\u{2022} Phone: (905) 776-2600\n\u{2022} Size: 72.64 ha\n\u{2022} Year established: 1967\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t151 Wheeler’s Sideroad, R.R. # 1\n\tSelkirk\n\tN0A 1P0",
                   camping: [0: (heading: "\(cCar)", detail: "All campsites offered at Selkirk are car campsites. Most campsites located in Areas 2 and 4 can accommodate larger trailers, are pull-through and most offer electrical hook-ups. Amenities include a central comfort station in Area 2 which offers flush toilets, showers and laundry facilities. Water taps are located throughout all four campground areas. Areas 1, 3 and 4 offer vault toilets with vanity areas but visitors must go to Area 2 for comfort station facilities (this is on average less than a five minute walk from any of the other campground areas)."), 1: (heading: "\(cGrp)", detail: "Selkirk offers two group camping areas located between the campground and the lake, adjacent to the day-use area. The two sites are fairly large and open and can accommodate up to 25 people per site. A vault toilet building is nearby as well as a water tap located in the day-use area. The beach/lakeshore is located approximately 100 metres from each site. \n\nTo reserve, please call 1-888-ONT-PARK (1-888-668-7275) or 1-519-826-5290 outside of North America."), 2: (heading: "\(cRad)", detail: "Radio-free camping is offered in Area 3 Campground although there are no electrical campsites in this area.")],
                   activities: [0: (heading: "\(aBik)", detail: "Although Selkirk does not have dedicated bicycle trails, visitors can cycle along all of the campground roads which are fairly flat and easy to navigate."), 1: (heading: "\(aBrd)", detail: "Selkirk offers birding opportunities along the hiking trail, in the campground and near the lake. A bird banding station once existed in the park and monitored and banded migrating birds as they crossed Long Point Bay and across Lake Erie on their journey south in the fall and back north in the spring."), 2: (heading: "\(aBtg)", detail: "Although boating is not offered within the park, boats can be launched at a nearby marina on Sandusk Creek to access the lake in front of the park."), 3: (heading: "\(aCan)", detail: "A popular day trip takes paddlers out through the marsh area along Spring Creek and into the lake at the mouth of Sandusk Creek. You can also travel up Sandusk Creek which is outside the park boundary."), 4: (heading: "\(aHik)", detail: "\u{2022} Wheeler’s Walk Trail – 1.5 km, 30-40 minutes, easy \n\tThis trail takes hikers from the campground side of the park across a marsh wetland, via a boardwalk, to the west side of the park. You will travel through remnants of the forest that pre-date the park and through a White Pine plantation that was planted in the early 1970s."), 5: (heading: "\(aSwm)", detail: "There is a small beach in the day-use picnic area. There is a larger, natural beach fronting the lake however it tends to be pebbly. The water fronting the beach has a gradual drop off. At first entry it is a bit stony but turns to sand soon afterwards.")],
                   facilities: [0: (heading: "\(fBF)", detail: "Barrier-free access is available at the central comfort station and all vault toilet buildings within the campground areas. A designated barrier-free campsite with electrical hook up is also available and is located adjacent to the central comfort station."), 1: (heading: "\(fCS)", detail: "A comfort station complete with flush toilets, showers and laundry is located in Area 2 Campground. This comfort station is within a five minute walk from all other campground areas."), 2: (heading: "\(fDU)", detail: "There is a large day-use area beach area with shade, picnic tables and water taps. The swimming area is not supervised by a lifeguard."), 3: (heading: "\(fFT)", detail: "Flush toilets are found in the central comfort station in Area 2 Campground."), 4: (heading: "\(fL)", detail: "Laundry facilities are located at the central comfort station in Area 2 Campground."), 5: (heading: "\(fPSt)", detail: "A small park store is located at the Park Office. Basic camping supplies, souvenirs, snacks, beverages, ice and firewood are available.")])
