//
//  Sharbot.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let sharbot = Park(name: "sharbot lake",
                   about: "\u{2022} Located on two beautiful, clear lakes that offer great swimming, canoeing, boating and fishing\n\u{2022} Park your vehicle and enjoy all the park amenities within easy walking distance of each other, great for young families\n\u{2022} Nature trails are picturesque and offer a great variety of scenery\n\u{2022} Clean facilities and friendly staff are our top priority for customer service\n\u{2022} Easy access from major Ontario city centres for those weekend getaways or longer vacations",
                   general: "\u{2022} Phone: 613-335-2814\n\u{2022} Size: 80.00 ha\n\u{2022} Year established: 1958\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\tCivic # 25467 Hwy 7, R.R.#2\n\tSharbot Lake\n\tK0H 2P0",
                   camping: [0: (heading: "\(cCar)", detail: "The majority of sites at Sharbot Lake have vehicle access. A few sites do not have space for a on the site, however designated parking areas are just a short walk away. \n\nThere are over 150 treed campsites, some with electricity and two that are barrier-free. Large trailers can be accommodated in the Beach Front and Maple Grove Campgrounds. A barrier-free comfort station with showers and drinking water are among the amenities provided.")],
                   activities: [0: (heading: "\(aBik)", detail: "There are no dedicated bicycle trails at Sharbot Lake but bicycles are permitted on campground roads."), 1: (heading: "\(aBrd)", detail: "Listen for the haunting call of the loon on the lake and for the songs of warblers, Eastern Phoebes, Scarlet Tanagers, Barred Owls and Red-Shouldered Hawks in the woods."), 2: (heading: "\(aBtg)", detail: "Sharbot Lake, with its docks, is ideal for large boats and waterskiing. Black Lake is more suitable for smaller boats. Canoes can be rented in the park."), 3: (heading: "\(aCan)", detail: "Paddle on the sheltered waters of Black Lake or tackle the larger Sharbot Lake. A short portage connects the two bodies of water. Canoes can be rented in the park."), 4: (heading: "\(aFsh)", detail: "Walleye, bass, Northern Pike, perch and sunfish can be found in both Black and Sharbot Lakes. Lake Trout are found in Sharbot Lake."), 5: (heading: "\(aHik)", detail: "\u{2022} Discovery Trail - 1.2 km loop, 1hour, moderate  \n\tFollow this trail along the ridge of land that divides Black Lake and Sharbot Lake through stands of maple, oak and birch and see a dramatic change in topography. From the top of the ridge you can see both lakes. \n\u{2022} Ridgeview Trail - 0.5 km return, 30 minutes, easy to moderate \n\t This trail climbs the ridge that divides Black Lake from Sharbot Lake. There is one steep climb before you reach the top and a spectacular view."), 6: (heading: "\(aSwm)", detail: "Two sandy beaches located on Black Lake are great for swimming.")],
                   facilities: [0: (heading: "\(fBF)", detail: "Two campsites, the comfort station and the composting toilet facility (located in Beach Front campground) are barrier-free accessible."), 1: (heading: "\(fBL)", detail: "Boat launches are located on both Black Lake and Sharbot Lakes."), 2: (heading: "\(fCS)", detail: "A comfort station is located in Maple Grove Campground and provides flush toilets, showers and sinks and has barrier-free access."), 3: (heading: "\(fDU)", detail: "Come and enjoy the day with us and bring along a picnic basket with your family and friends.  The day-use area is located at the sandy beach at Black Lake.  Picnic tables are available and toilets are conveniently located. \n\nA playground with climbing equipment and swings is located near the picnic shelter at the day-use area.  A smaller playground for children is located on the beach between Maple Grove and The Point Campgrounds."), 4: (heading: "\(fFT)", detail: "Flush toilets are located at the comfort station in Maple Grove Campground."), 5: (heading: "\(fL)", detail: "Laundry facilities are located at the comfort station in Maple Grove Campground."), 6: (heading: "\(fPSt)", detail: "Ice, firewood, worms, and park souvenirs are available at the Park Store located in the Park Office. For other supplies, visit the nearby Village of Sharbot Lake."), 7: (heading: "\(fPEA)", detail: "A swimming area for your pet is provided on Sharbot Lake.  If you let your pet off leash, you must have control at all times."), 8: (heading: "\(fPSh)", detail: "Sharbot Lake has one picnic shelter which may be rented on a daily basis for those family or friends gathering to celebrate events. If the shelter is not rented it is available for park visitors on the days you need to get out of the weather. Please contact the park if you wish to reserve the shelter."), 9: (heading: "\(fR)", detail: "For those who want to explore Sharbot or Black Lakes further, canoes are available for rent on a daily basis. Personal Floatation Devices (PFDs) are available for loan with a $25 refundable deposit. The park has tents for rent upon request. Please contact the Park Office for further details.")])
