//
//  Sibbald.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let sibbald = Park(name: "sibbald point",
                   about: "\u{2022} Large sandy beach on Lake Simcoe\n\u{2022} Spacious electrical and non-electrical campsites with pull through trailer sites\n\u{2022} Audio Device Free Camping for a natural camping experience near an urban centre\n\u{2022} The Sibbald family museum – Eildon Hall (open in July & August)\n\u{2022} Grassy picnic areas and forested hiking trail\n\u{2022} Boat launch and parking area for boaters",
                   general: "\u{2022} Phone: (905) 722-8061\n\u{2022} Size: 225.01 ha\n\u{2022} Year established: 1957\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t26071 York Rd 18 (Park Road)\n\tSutton West\n\tL0E 1R0",
                   camping: [0: (heading: "\(cCar)", detail: "Sibbald Point offers car-camping in 10 different campgrounds, offering both electrical and non-electrical sites."), 1: (heading: "\(cGrp)", detail: "The campground has six group sites that accommodate 15 – 50 people. Water taps and vault toilets are available on site. Sites are a 15 minute walk to the beach and a five minute walk to the comfort station. The sites are available primarily for youth groups. Reservations can be made by calling the park Monday – Thursday starting in early May."), 2: (heading: "\(cRad)", detail: "Sites #1-145, #200-381, #501-586, #901-965 and the Group Camping Area are audio device-free zones.")],
                   activities: [0: (heading: "\(aBik)", detail: "Cycling on park roads makes for easy access to all park facilities. Tour the local Hedge Road along the Lake Simcoe waterfront."), 1: (heading: "\(aBrd)", detail: "Several species of birds make Sibbald Point a stopover on their migration north. Wild turkeys and Pileated woodpeckers are often seen."), 2: (heading: "\(aBtg)", detail: "Lake Simcoe is an ideal place for sailing and motorboats. Campers and day visitors can use the boat launch and dock temporarily or overnight."), 3: (heading: "\(aCan)", detail: "Paddlers should be aware of weather conditions on Lake Simcoe and it is recommended that you stay close to shore."), 4: (heading: "\(aFsh)", detail: "Lake Trout, bass, whitefish, pike, yellow pickerel and jumbo perch are abundant in Lake Simcoe."), 5: (heading: "\(aHik)", detail: "\u{2022} Maidenhair Fern Trail 2.0 km, 1-1.5 hours, easy \n\tThis self guided loop trail takes a close look at the variety of ecosystems at Sibbald Point. Pick up the trail brochure at the trailhead, the Registration Office or Park Office. \n\u{2022} The Cultural History of Sibbald Point Provincial Park 1.0 km, 1-2 hours, easy \n\tThis walk explores the rich history of the Sibbald Family through an interpretive guide book. Park visitors will explore the Eildon Hall Museum (Sibbald Family Estate Home (ca. 1836), the settlers cabin, a walk down “The Avenue”, St. George’s Anglican Church (ca.1877) and grave yard which is the burial site of famous Canadian authors Stephen Butler Leacock and Mazo de la Roche."), 6: (heading: "\(aNHE)", detail: "Park staff offer weekly educational programs for children and adults from late June to Labour Day. They include nature and historical walks, evening programs with guest speakers, videos, children’s crafts and games."), 7: (heading: "\(aSwm)", detail: "The blue waters of Lake Simcoe and the sandy beaches of the park are ideal for family swimming. There is a buoyed swimming area but please note there are no lifeguards posted. Comfort stations and change facilities are close to the beach."), 8: (heading: "\(aWA)", detail: "In winter, Lake Simcoe boasts some of the best ice fishing for perch and whitefish. Other unorganized winter activities within the park include hiking, cross-country skiing and snowshoeing. The main park road and a parking lot are kept open for winter visitors.")],
                   facilities: [0: (heading: "\(fBF)", detail: "There are barrier-free washroom stalls at all comfort stations and barrier free showers at the comfort stations located in the campground."), 1: (heading: "\(fBL)", detail: "There is a boat launch and docks for temporary docking."), 2: (heading: "\(fCS)", detail: "There are 12 comfort stations (complete with showers) located throughout the campgrounds and day-use areas."), 3: (heading: "\(fDU)", detail: "Picnic areas can be found in quiet, grassy locations throughout the park and at the main beach. Most are close to flush toilets and drinking water taps."), 4: (heading: "\(fFT)", detail: "All comfort stations are equipped with flush toilets."), 5: (heading: "\(fPSt)", detail: "The Park Store sells groceries, fast food, ice cream, park souvenirs and camping supplies. It is open from May until September."), 6: (heading: "\(fPSh)", detail: "Group picnic shelters in the day-use area accommodate 50–75 people and can be reserved for weekend use. The picnic shelters are also audio device free. Reservations can be made by calling the park Monday through Thursday, starting in early May."), 7: (heading: "\(fR)", detail: "Personal Floatation devices (PFDs) are available at the Registration Office. For a refundable deposit, you can borrow a properly fitted PFD."), 8: (heading: "\(fVC)", detail: "Eildon Hall Museum, once home to the Sibbald family, displays 19th century artefacts and furniture. It is open during July and August. St. George’s Anglican Church, built in 1877, is located at the northwest corner of the park. Its graveyard is the final resting place of famous Canadian authors Stephen Butler Leacock and Mazo de la Roche.")])
