//
//  Silver.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let silver = Park(name: "silver lake",
                  about: "\u{2022} Located on a picturesque lake that offers great swimming, canoeing, boating, and fishing\n\u{2022} Park your vehicle and enjoy all the park amenities within easy walking distance, great for young families with a good playground\n\u{2022} Clean facilities and friendly staff are our top priority\n\u{2022} Easy access from major Ontario city centres for those weekend getaways",
                  general: "\u{2022} Phone: 613-268-2000\n\u{2022} Size: 43.23 ha\n\u{2022} Year established: 1958\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\tCivic # 22726 Hwy 7, R.R.#2\n\tMaberly\n\tK0H 2B0",
                  camping: [0: (heading: "\(cCar)", detail: "Silver Lake has over 100 treed campsites; some sites have electrical service and one is barrier-free. Large trailers can be accommodated in the Wesley Campground. A barrier-free comfort station with showers and drinking water are among the amenities provided for your convenience. \n\nMost campsites have vehicle access. A few sites do not have vehicle access however a designated parking area is just a short walk away.")],
                  activities: [0: (heading: "\(aBik)", detail: "There no dedicated bicycle trails at Silver Lake however bicycles are permitted on campground roads."), 1: (heading: "\(aBrd)", detail: "Look and listen for the Eastern Kingbird, Red-winged Blackbird, mallards, American Bitterns, Common Loons and Great Blue Herons."), 2: (heading: "\(aBtg)", detail: "At 9 km long, Silver Lake is large enough to accommodate all types of boats: motorboats, sailboats, paddle boats, canoes and kayaks. A boat ramp is located next to the large beach. Canoe rentals are available at the park."), 3: (heading: "\(aCan)", detail: "Silver Lake is a picturesque lake for paddling, providing explorers with the opportunity to enjoy the surroundings. Canoe rentals are available at the park."), 4: (heading: "\(aFsh)", detail: "Anglers of all ages and abilities will find Northern Pike, Smallmouth Bass, Lake Trout, Yellow Perch and sunfish at Silver Lake."), 5: (heading: "\(aHik)", detail: "\u{2022} Marsh Trail - 0.5 km return, 30 minutes, easy \n\tAlong a boardwalk, cross the marsh at the eastern end of Silver Lake to higher ground, where you will see a transition between wetland and upland forest. This zone is rich in flora and fauna."), 6: (heading: "\(aSwm)", detail: "The wide crescent of sandy beach is Silver Lake’s main attraction. A smaller sandy beach is located near the picnic shelter.")],
                  facilities: [0: (heading: "\(fBF)", detail: "One campsite in the Dawson Campground and the comfort station offer barrier-free access."), 1: (heading: "\(fBL)", detail: "Silver Lake has one boat launch, located at the end of the main park road."), 2: (heading: "\(fCS)", detail: "A comfort station is located centrally in the park and provides flush toilets, showers and sinks."), 3: (heading: "\(fDU)", detail: "Come and enjoy the day with us and bring along a picnic basket with your family and friends.  The day-use area is located on a small peninsula that juts into Silver Lake.  It has its own sandy beach and picnic tables are provided.  Change rooms and washroom are located nearby. A playground with climbing equipment and swings is located in the day-use area of the park."), 4: (heading: "\(fFT)", detail: "Flush toilets are located at the comfort station."), 5: (heading: "\(fPSt)", detail: "Ice, firewood, worms, and park souvenirs are available at the park store located in the Park Office. For other supplies, visit the nearby village of Sharbot Lake or the town of Perth."), 6: (heading: "\(fPSh)", detail: "Silver Lake has one picnic shelter which may be rented on a daily basis for those family or friends gathering to celebrate events. When the shelter is not reserved, it is available for visitors on a first-come, first-served basis. Please contact the park if you wish to reserve the shelter."), 7: (heading: "\(fR)", detail: "For those who want to explore Silver Lake further, canoes are available for rent on a daily basis. Personal Floatation Devices (PFDs) are available for loan with a $25 refundable deposit. The park has tents for rent upon request. Please contact the park office for further details.")])
