//
//  Sioux.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let sioux = Park(name: "sioux narrows",
                 about: "\u{2022} Located on the shores of Lake of the Woods, this park offers recreation opportunities for the lake lover - boating, swimming, sailing and canoeing\n\u{2022} Internationally renowned for its walleye fishing\n\u{2022} Great location to start your exploration of Lake of the Woods; this 1 million acre lake has over 14,000 islands and 105,000 kilometres of shoreline\n\u{2022} Sioux Narrows is the site of an Ojibway battle with Sioux warriors and only a boat ride away from Aboriginal pictographs",
                 general: "\u{2022} Phone: May to September: 807-226-5223 September to April: 807- 226-5241 or 807-468-2669\n\u{2022} Size: 135.00 ha\n\u{2022} Year established: 1957\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\tP.O. Box 5080\n\tKenora\n\tP9N 3X9",
                 camping: [0: (heading: "\(cCar)", detail: "Sioux Narrows Provincial Park is situated along the shoreline of Lake of the Woods. On the edge of the Canadian Shield, bedrock outcrops and towering White Pine make each campsite unique. This is a small park with just over fifty car campsites, one-third of which have electrical service."), 1: (heading: "\(cGrp)", detail: "Sioux Narrows has two group campsites; the first is located on a point on the shores of Lake of the Woods. This private location has its own dock and excellent swimming and camping opportunities. It is suitable for 30-40 people. The second group campsite is also private, just outside the main camping area. This cozy spot is perfect for a group of 20-30 people."), 2: (heading: "\(cWak)", detail: "Sioux Narrows has eight walk-in campsites for those who want a bit of quiet from the main campground road and a unique waterfront location.  Your campsite will be a 20 to 50 m walk from where your car is parked.")],
                 activities: [0: (heading: "\(aBik)", detail: "Cycling on park roads is a great way to get around and an enjoyable way to explore the park. Visitors are reminded that Ontario law requires helmets to be worn by those 18 years old and younger, when cycling on roads, including those in provincial parks."), 1: (heading: "\(aBrd)", detail: "Lake of the Woods is home to a variety of migratory birds. Be sure to look for the large American White Pelicans."), 2: (heading: "\(aBtg)", detail: "Some of the most spectacular scenery in Northwestern Ontario can be viewed on the waters of Lake of the Woods. Launch your boat at the park ramp for cruising, sailing or waterskiing. A ten minute cruise down the lake takes you to centuries-old pictographs."), 3: (heading: "\(aCan)", detail: "Lake of the Woods offers many opportunities for exploration. Canoes are available for rent from the park office."), 4: (heading: "\(aFsh)", detail: "Lake of the Woods is internationally renowned for its walleye fishing; Smallmouth and Largemouth Bass are also extremely popular with anglers. Fishing licences are available a short distance away in the Town of Sioux Narrows."), 5: (heading: "\(aHik)", detail: "Sioux Narrows has three hiking trails. \n\u{2022} Deer Path Trail – This short 600 m trail connects the park office and campground. \n\u{2022} Lookout trail - 1.5 km, easy \n\tThe Lookout Trail starts near the beach and offers a two kilometre hike to a view of Lake of the Woods. \n\u{2022} Fern Valley Trail – 1.6 km, easy \n\tThis all season trail begins near the park entrance and connects to a trail system outside the park boundary."), 6: (heading: "\(aSwm)", detail: "The many waterfront sites at Sioux Narrows give campers the chance to swim without even leaving their sites. A family friendly sandy beach is only minutes from the campground."), 7: (heading: "\(aWA)", detail: "While the park is closed during the winter, a cross-country ski trail beginning at the entrance gate will take visitors on a tour of the park and surrounding area. For information on conditions and the trail route, please contact the Township of Sioux Narrows Nestor Falls at 807-226-5241.")],
                 facilities: [0: (heading: "\(fBF)", detail: "The park office and both comfort stations are barrier-free. The park also offers two barrier- free campsites."), 1: (heading: "\(fBL)", detail: "A boat launch to Lake of the Woods is available, however docking space is limited."), 2: (heading: "\(fCS)", detail: "Sioux Narrows has a main comfort station which is centrally located and a mini-comfort station located close to the waterfront group campsite."), 3: (heading: "\(fDU)", detail: "The large open grassy area is prefect for large groups."), 4: (heading: "\(fFT)", detail: "Flush toilets are located at the comfort stations."), 5: (heading: "\(fL)", detail: "Laundry facilities are located at the main comfort station."), 6: (heading: "\(fPSh)", detail: "A picnic shelter is located at the main day-use and picnic area. There is also a large BBQ available for rent. Please contact the park for details."), 7: (heading: "\(fR)", detail: "Canoes are available for rent at the park office.")])
