//
//  Six.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let six = Park(name: "six mile lake",
               about: "\u{2022} A pretty park with landscape that has inspired painters\n\u{2022} Many semi-private, larger sites\n\u{2022} Conveniently located off Hwy 40\n\u{2022} Three sand beache\n\u{2022} Canoe, kayak and pedal boat rental\n\u{2022} Three hiking trail\n\u{2022} Well-known for recreational boating and fishin\n\u{2022} Fully equipped park store",
               general: "\u{2022} Phone: (705) 756-274\n\u{2022} Size: 212.00 h\n\u{2022} Year established: 195\n\u{2022} Park Classification: Recreational \n\u{2022} Address\n\t2024 Joe King's Roa\n\tPort Sever\n\tL0K 1S0",
               camping: [0: (heading: "\(cCar)", detail: "Six Mile Lake offers six campgrounds in a natural setting and within walking distance of all park facilities. All campsites are equipped with a fire pit and picnic table. \n\nPine and Birch Campgrounds can accommodate large equipment and are equipped with hydro. Birch Campground is located close to the beach, playground and shower building and is within walking distance of the park store and nature centre. \n\nMaple, Oak and Poplar Campgrounds offer unserviced, semi-private campsites on low-traffic roadways. Most sites are surrounded by trees, offering both shade and privacy. \n\nThe Lakeview Heights Campground stretches the length of the park and offers premium waterfront sites with views of Six Mile Lake. The sites are located along the main park road and are close to washroom facilities.")],
               activities: [0: (heading: "\(aBik)", detail: "There are no bicycle trails however cycling is allowed on park roads and is an excellent way to get around the park. There are ample road cycling opportunities close to the park."), 1: (heading: "\(aBtg)", detail: "Six Mile Lake provides the perfect setting for recreational boating opportunities. Rental dock spaces are also available on a first-come, first-served basis."), 2: (heading: "\(aCan)", detail: "Six Mile Lake offers the ideal location for canoeists of all levels of ability; whether you prefer to stay in the sheltered waters of the park or spend the day exploring the lake, there is much to see and do. Canoes are available for rent at the park store. \n\nMany canoeists choose to use Six Mile Lake Provincial Park as a starting point for the Gibson-MacDonald Canoe Route. For information on this canoe route contact the Ministry of Natural Resources Parry Sound District Office at (705) 746 - 4201."), 3: (heading: "\(aFsh)", detail: "Whether from the dock or on the lake, Six Mile Lake provides ample fishing opportunities for the whole family."), 4: (heading: "\(aHik)", detail: "Three short, linear but interconnected hiking trails offer visitors the opportunity to take in the natural and cultural heritage of Six Mile Lake Provincial Park. \n\u{2022} The Living Edge Trail 1 km, easy \n\tCatch a glimpse of beaver lodges in wetland areas, walk the rocky outcrops of the Canadian Shield and keep your eyes open for the wide variety of species that live in the forest! \n\u{2022} The David Milne Trail 0.5 km, easy \n\tThis trail celebrates the influence of one of Canada’s foremost artists who lived on Six Mile Lake and used the scenic vistas and majestic landscape as inspiration for his paintings. These paintings would later be recognized for their impact on Canadian culture. View the signature rolling rocks of the Canadian Shield that inspired so many of his paintings and sketches. \n\u{2022} The Marsh Trail \n\tHikers will circle a wetland area which provides important habitat for a wide variety of plants and wildlife. Keep your eyes open for all kinds of species from dragonflies to moose!"), 5: (heading: "\(aNHE)", detail: "Programs are held daily from July through Labour Day. The Nature Centre is open daily June through September."), 6: (heading: "\(aSwm)", detail: "Three sand beaches and sheltered water provide the perfect place to unwind on a summer day. The beaches are located near park areas and are within walking distance of all campgrounds. \n\nThe day-use beach is equipped with a volleyball net.")],
               facilities: [0: (heading: "\(fBF)", detail: "Two designated barrier-free campsites (#411 and #413) are centrally located and close to park amenities. Barrier-free access is available to the park gate and store."), 1: (heading: "\(fBL)", detail: "A boat launch is centrally located within the park. The park also offers rental dock spaces on a first-come, first-served basis."), 2: (heading: "\(fCS)", detail: "The Six Mile Lake comfort station has two washrooms, eight showers and laundry facilities."), 3: (heading: "\(fDU)", detail: "The beach and park areas are available for day-use."), 4: (heading: "\(fFT)", detail: "Two flush toilets are located at the comfort station."), 5: (heading: "\(fL)", detail: "Laundry facilities are located at comfort station."), 6: (heading: "\(fPSt)", detail: "Fully equipped with groceries, snacks, camping accessories and souvenirs."), 7: (heading: "\(fPEA)", detail: "There is a pet exercise beach area available. Check the park map for location."), 8: (heading: "\(fPSh)", detail: "Available for rent by contacting the park at (705) 756-2746."), 9: (heading: "\(fR)", detail: "Canoes, kayaks and paddle boats are available for rent at the park store. \n\nThe park also offers rental dock spaces and participates in the personal floatation devices (PFDs) and Tackleshare loaner programs."), 10: (heading: "\(fVC)", detail: "Open daily from June through September")])
