//
//  Solace.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let solace = Park(name: "solace",
                  about: "\u{2022} Solace Provincial Park encompasses a chain of narrow, scenic lakes that point north and south, and lie between a series of forest-covered ridges.\n\u{2022} Canoeing opportunities are lake-to-lake with short rugged portages in-between.\n\u{2022} The park connects with Lady Evelyn-Smoothwater and Sturgeon River Provincial Parks and other waterways on Crown land, as part of the Temagami canoe route network.\n\u{2022} The landscape is dominated by Jack pine of the Boreal Forest and many lakes support both Lake and Brook Trout.",
                  general: "\u{2022} Phone: (705) 569-3205\n\u{2022} Size: 5943.00 ha\n\u{2022} Year established: 1989\n\u{2022} Park Classification: Waterway \n\u{2022} Address:\n\t24 Finlayson Park Road\n\tTemagami\n\tP0H 2H0",
                  camping: [0: (heading: "\(cBac)", detail: "Campsites and marked portages are all that are provided, and amenities are limited to box toilets and fire rings. Only experienced backcountry canoeists should consider travelling in this remote area. Maps for navigation are essential and will be helpful in locating campsites. \n\nPlease Note: Permits are required for all overnight backcountry camping.  For a list of best locations to obtain permits, please contact the park directly.")],
                  activities: [0: (heading: "\(aBrd)", detail: "Lady Evelyn-Smoothwater and the surrounding waterway parks including Solace, protect an area of rugged highland watersheds and contains forest that mixes Great Lakes-St. Lawrence and Boreal species of trees, creating many different habitats for birds. During the nesting season of spring and early summer, many species of warbler, thrush, flycatcher and woodpecker can be heard calling to defend territory. Eagles, osprey and many other birds of prey can be spotted hunting above the forests of the park."), 1: (heading: "\(aBtg)", detail: "Motorboat restrictions apply. Please refer to the Temagami Area Park Management Plan 2007 for zone specific management direction."), 2: (heading: "\(aCan)", detail: "Solace can only be reached by canoe or floatplane, as it is a remote and roadless backcountry park in the heart of the Temagami highlands. Many watersheds begin here and in nearby Lady Evelyn-Smoothwater Provincial Park. Solace lies between Lady Evelyn-Smoothwater and Sturgeon River Provincial Park. It can be canoed as part of a longer route which includes those parks, or Crown land routes like the Yorston River. Alternately, paddlers can canoe just the lakes within the park at a more leisurely pace. There are two short circle routes that lie completely within Solace and can even be done as day trips from a base camp."), 3: (heading: "\(aFsh)", detail: "The lakes in Solace Provincial Park support Lake trout and Brook trout."), 4: (heading: "\(aHnt)", detail: "Hunting restrictions apply. Please refer to the Temagami Area Park Management Plan 2007 for zone specific management direction."), 5: (heading: "\(aSwm)", detail: "The lakes and rivers of this park offer typical backcountry swimming opportunities with some shorelines and rocky headlands providing access to the water.")],
                  facilities: [0: (heading: "\(fR)", detail: "Canoes and camping equipment can be rented from outfitters near the various park access points")])
