//
//  Spanish.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let spanish = Park(name: "spanish river",
                   about: "\u{2022} The Spanish River and Biscotasi Lake are favourites for backcountry canoeing. Its rugged landscape, towering pines, variety of whitewater, a chance to include road or train access options and choice of routes make it a popular trip.\n\u{2022} The Spanish River offers paddling for canoeists of intermediate skill level, with Class I and II rapids, lots of swifts and moving water. Take the East Branch of the river for whitewater fun or take the train to Biscotasing to start your trip on the wilder, West Branch of the river.\n\u{2022} Stay on huge island-studded Biscotasi Lake for flatwater paddling and great fishing.\n\u{2022} No reservations necessary.\n\u{2022} Historic route of the Ojibwe, 18th century fur traders and turn of the century Forest Ranger Archie Belaney, known later as Grey Owl.",
                   general: "\u{2022} Phone: 705-865-2021\n\u{2022} Size: 35386.00 ha\n\u{2022} Year established: 2001\n\u{2022} Park Classification: Waterway \n\u{2022} Address:\n\tc/o Chutes Provincial Park P.O. Box 37, 660 Imperial Street North\n\tMassey\n\tP0P 1P0",
                   camping: [0: (heading: "\(cBac)", detail: "Interior camping only – 83 marked backcountry sites. All campsites are equipped with a fire pit and a box privy. There is a can and bottle ban in the park. All garbage is to be removed by the camper. Driftwood can be gathered for campfires. \n\nOvernight camping is permitted at the Duke Lake access prior to starting your trip. Interior camping fees and rules apply. \n\nThere is a self-serve registration box and permits located at the Duke Lake access. Permits for other access points can be obtained by calling Chutes Provincial Park (705-865-2021) or one of the following permit issuers:\n\n\tChutes Provincial Park – 705-865-2021 (year round) \n\tAgnew Lake Lodge –   705-869-2239 (mid April to October) \n\tBiscotasing General Store – 705-239-0830 (May to October) \n\tSpanish River Outfitters – 705-919-2607 (mid April to October) \n\tWindy Lake Provincial Park – 705-966-2315 (Victoria Day weekend in May – Labour Day in September)")],
                   activities: [0: (heading: "\(aBrd)", detail: "The park supports abundant bird life: osprey, Bald Eagles, Belted Kingfishers and Great Blue Herons are often seen while fishing. Many species of songbirds nest in the forests along the river, including Black and White Warblers, Yellow Warblers and Ovenbirds."), 1: (heading: "\(aBtg)", detail: "Motorboats are allowed on Biscotasi Lake and Agnew Lake."), 2: (heading: "\(aCan)", detail: "The Spanish River offers a number of paddling options: \n\nEast Branch: \n\tDuke Lake to Agnew Lake – 145 km (8-10 days) \n\tThe Forks to The Elbow – 58 km (3 days) \n\tThe Elbow to Agnew Lake – 50 km (2-3 days) \n\t*Sheahan to The Elbow – 40 km (2 days) \n\nWest Branch: \n\tBiscotasi Lake to Agnew Lake – 164 km (8-10 days) *Sinker Creek to Agnew Lake – 120 km (6-8 days) \n\nBiscotasi Lake to The Elbow – 114 km (5-7 days) \n\tBiscotasi Lake to Sheahan – 74 km (4 days) \n\t*VIA Rail access only. A scenic train ride is a unique way to start your trip. The train will drop off and pick up paddlers and all their gear at various points along the river. \n\nCanoeists and sea kayakers can paddle among the many islands that dot Biscotasi Lake and experience the vast country that was once home to Grey Owl, the famous conservationist. Two other large lakes are a very short portage from Biscotasi Lake; Ramsey Lake and Indian Lake have hundreds of kilometres of shoreline, bays and islands and when combined with Biscotasi it makes for a perfect kayaking and canoeing route for flatwater paddlers."), 3: (heading: "\(aFsh)", detail: "Many species of fish such as Walleye, Northern Pike, Lake and Brook Trout inhabit the many lakes and tributaries along the river."), 4: (heading: "\(aSwm)", detail: "Spanish River has no designated beaches but there are plenty of swimming opportunities.")],
                   facilities: [0: (heading: "\(fBL)", detail: "There is a public boat launch at the Duke Lake access. Boat launches are located at Biscotasing General Store and Agnew Lake Lodge (a launch fee applies at this location)."), 1: (heading: "\(fDU)", detail: "The park is open for day-use. Permits for day-use are not required.")])
