//
//  SturgeonBay.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let sturgeonbay = Park(name: "sturgeon bay",
                       about: "\u{2022} Excellent fishing on Sturgeon Bay, leading into Georgian Bay\n\u{2022} Situated among the 30,000 Islands - just off of Trans-Canada Highway 69\n\u{2022} Great shallow sandy beach\n\u{2022} Camping experience for everyone: RV and car camping\n\u{2022} Canoe rentals, ice and camping supplies available\n\u{2022} Docking facilities available for rent with motorboat rentals nearby",
                       general: "\u{2022} Phone: (705) 366-2521\n\u{2022} Size: 14.23 ha\n\u{2022} Year established: 1960\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t203 Hwy. 529\n\tPoint au Baril\n\tP0G 1K0",
                       camping: [0: (heading: "\(cCar)", detail: "Sturgeon Bay offers car camping on 81 campsites. \n\nMany campsites offer electrical hook-up.  Amenities such as water taps and toilets are nearby. Laundry facilities and showers are available on the cabin side of the park, a short distance away.  Swimming, boating, canoeing and a boat launch are all within walking distance from the campground."), 1: (heading: "\(cRof)", detail: "Please see website for the most up to date information on roofed accommodations.")],
                       activities: [0: (heading: "\(aBik)", detail: "There are no dedicated bicycling trails however campers enjoy cycling on the park roads."), 1: (heading: "\(aBrd)", detail: "Common bird sightings include the Common Loon, Caspian Tern, Black Tern, Great Blue Heron, Merlin, Spotted Sandpiper, American Woodcock, Mourning Dove, Whip-poor-will, and Pileated Woodpecker. Please visit the gatehouse for copies of the birding checklist. Bring your binoculars!"), 2: (heading: "\(aBtg)", detail: "Power boats are available for rent nearby."), 3: (heading: "\(aCan)", detail: "We have canoes available for rent. Take a scenic tour of Sturgeon Bay and area but note that weather and waves can change quickly on Georgian Bay."), 4: (heading: "\(aFsh)", detail: "There is excellent fishing on Sturgeon Bay and Georgian Bay."), 5: (heading: "\(aSwm)", detail: "There is a natural sand beach recommended for swimming, and it is marked with buoy lines. The beach has a gradual drop-off. Please note: there are no lifeguards posted at the beach, and pets are not permitted.")],
                       facilities: [0: (heading: "\(fBF)", detail: "There are two boat launches located within the park."), 1: (heading: "\(fCS)", detail: "Showers and laundry facilities are located near the cottages, a short distance away from the campground."), 2: (heading: "\(fDU)", detail: "Sturgeon Bay has a natural sand beach, with a buoyed swimming area. There is a shady area with picnic tables and a water tap. Please note: there are no lifeguards posted at the beaches and pets are not permitted."), 3: (heading: "\(fFT)", detail: "Flush toilets are found throughout the campgrounds and the day-use area."), 4: (heading: "\(fL)", detail: "Laundry facilities are available a short distance away, near the cabins."), 5: (heading: "\(fPSt)", detail: "The Sturgeon Bay park store offers merchandise, small souvenirs and many camper supplies including ice and groceries."), 6: (heading: "\(fR)", detail: "Canoes are available for rent at the park store.")])
