//
//  SturgeonRiver.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let sturgeonriver = Park(name: "sturgeon river",
                         about: "\u{2022} The Sturgeon River provides canoeists with plenty of whitewater, scenic falls and rapids, wildlife spotting and good fishing, all in a remote setting.\n\u{2022} Enjoy the river’s continually changing scenery, from long slender lakes to narrow river channels, rapids and shallows. The river begins in the Temagami highlands, with bedrock outcrops eventually turning to sandy shores over the course of a week-long paddle\n\u{2022} This scenic river was once used by loggers to float timber downstream to distant mills, and some evidence of the days of the “river drives” can still be found along the river’s shores.",
                         general: "\u{2022} Phone: (705) 569-3205\n\u{2022} Size: 7985.00 ha\n\u{2022} Year established: 1989\n\u{2022} Park Classification: Waterway \n\u{2022} Address:\n\t24 Finlayson Park Road\n\tTemagami\n\tP0H 2H0",
                         camping: [0: (heading: "\(cBac)", detail: "Backcountry campsites are rustic, with a box privy and fire pit the only amenities. They are often found near rapids and waterfalls. Please review Temagami Canoe Routes Planning Map and other trip planning resources to identify campsites and plan your trip. \n\nFinlayson Point Provincial Park is the main office for Sturgeon River and other Temagami area provincial parks. Information and trip planning assistance can be obtained by calling 705-569-3205. \n\nPlease Note: Permits are required for all overnight backcountry camping.  For a list of best locations to obtain permits, please contact the park directly.")],
                         activities: [0: (heading: "\(aBrd)", detail: "Lady Evelyn-Smoothwater and the surrounding waterway parks including Sturgeon River, protect an area of rugged highland watersheds and contain forest that mixes Great Lakes-St. Lawrence and Boreal species of trees, creating many different habitats for birds. During the nesting season of spring and early summer, many species of warbler, thrush, flycatcher and woodpecker can be heard calling to defend territory. Eagles, osprey and many other birds of prey can be spotted hunting above the forests of the park."), 1: (heading: "\(aBtg)", detail: "There are some boating opportunities in this park. Check the park management plan for restrictions."), 2: (heading: "\(aCan)", detail: "The Sturgeon River is a week-long whitewater canoe route that provides class I and II whitewater along much of its length. Portages are numerous, but often short – between 50 and 250 metres. Campsites are often found near rapids and waterfalls. Trips often begin at Paul Lake via floatplane or further north on the river where the Portelance timber access road crosses. Route options are varied, but the common route includes the length of the river, and then upstream on the Obabika River and on to Wawiagama Lake, ending the trip with another floatplane flight or down the Goulard Lumber Road (road options require a vehicle shuttle). \n\nAs with many of the Temagami canoe routes, many options are available by combining other routes. For longer trips, it is possible to combine the Sturgeon with other park and Crown land routes. \n\nFinlayson Point Provincial Park is the main office for Sturgeon River and other Temagami area provincial parks. Information and trip planning assistance can be obtained by calling 705-569-3205."), 3: (heading: "\(aFsh)", detail: "The Sturgeon River is a warm-water fishery, and Walleye and North Pike are the main species."), 4: (heading: "\(aHnt)", detail: "Hunting restrictions apply. Please refer to the Temagami Area Park Management Plan 2007 for zone specific management direction."), 5: (heading: "\(aSwm)", detail: "There are endless opportunities in the backcountry for swimming including both shallow and deeper water entries along rocky headlands.")],
                         facilities: [0: (heading: "\(fR)", detail: "Canoes and camping equipment can be rented from outfitters near the various park access points.")])
