//
//  Tidewater.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let tidewater = Park(name: "tidewater",
                     about: "\u{2022} Tidewater Provincial Park, a partnered park operated under agreement with the Moose Cree First Nation, is located in the northernmost part of Ontario near the salt waters of James Bay and Hudson Bay.\n\u{2022} This special park attracts visitors and campers looking for an unusual and exciting outdoor experience.\n\u{2022} The park consists of five islands in the Moose River estuary close to Moose Factory and Moosonee. From Moosonee, there are water taxis to take visitors to the park islands. Caution is advised as the winds, tides and river currents can challenge the most experienced canoeists.\n\u{2022} If you’re lucky, you may glimpse a seal or the milky white back of a beluga whale from the campgrounds.\n\u{2022} This park is also a destination for those who are canoeing the Missinaibi River or Abitibi River. To reach this park, visitors either fly to Moosonee or travel from Cochrane on the famous Polar Bear Express train service that runs daily in the summer months.",
                     general: "\u{2022} Phone: 705-272-7107\n\u{2022} Size: 979.78 ha\n\u{2022} Year established: 1970\n\u{2022} Park Classification: Natural Environment \n\u{2022} Address:\n\t2 – 4 Highway 11 South\n\tCochrane\n\tP0L 1C0",
                     camping: [0: (heading: "\(cBac)", detail: "ost of the 10 campsites in this backcountry Park are along the shore of the Moose River overlooking Moosonee. The operation of Tidewater Park is in partnership with the Moose Cree First Nation.  Please check their website for more information:  www.moosecree.com"), 1: (heading: "\(cGrp)", detail: "There is an area of the park designated for groups.")],
                     activities: [0: (heading: "\(aBrd)", detail: "The Moose River estuary is a haven for many species of birds, from warblers, to eagles, to herons, and many types of shorebirds, which take advantage of the tidal flats and pools created by the proximity to James Bay. At the mouth of the river, Shipsands Bird Sanctuary is a good spot for a guided trip."), 1: (heading: "\(aBtg)", detail: "Boats use the adjacent Moose River to access Moosonee and Moose Factory Islands. Motorboats are available to rent in Moosonee. Tides, winds and shifting shoals can make boating challenging. Hiring a guide is a good way to travel to the various sights and communities on the river."), 2: (heading: "\(aCan)", detail: "Tidewater is located at the end of the Missinaibi River and Abitibi River canoe routes, making it an obvious place to camp at the end of the trip before taking the train south. Caution is advised as the winds, tides and river currents can challenge the most experienced canoeists. Extra care is advised and the services of a local guide are recommended. Boat shuttles are available."), 3: (heading: "\(aFsh)", detail: "Anglers may catch Northern Pike, Walleye, and Whitefish in the Moose River off the shore of the Park."), 4: (heading: "\(aHik)", detail: "Riverside Trail is a 2 km interpretive trail rated easy within the Park on Charles Island.  Views of Moose Factory Island and Moosonee can be seen along the trail through the forest."), 5: (heading: "\(aSwm)", detail: "Tides and currents of the park islands make swimming dangerous. A swimming area is available at the town of Moosonee.")],
                     facilities: [0: (heading: "\(fBL)", detail: "A long dock is available to adjust to the tides of the Moose River. This allows boats to safely launch from the park."), 1: (heading: "\(fDU)", detail: "The Park contains one picnic shelter that can be used for Day Use or get-togethers.  It is adjacent to an open field which has traditionally been used for group camping."), 2: (heading: "\(fPSh)", detail: "A picnic shelter is available.")])
