//
//  Wakamibi.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let wabakimi = Park(name: "wabakimi",
                    about: "\u{2022} World-class wilderness canoeing, including over 2,000 kilometres of lake and river routes and some excellent whitewater\n\u{2022} Remote wilderness with opportunities for wildlife viewing as well as sport fishing and hunting\n\u{2022} Legendary fishing for walleye and northern pike; fly-in backcountry lodges and resorts\n\u{2022} The lands within and around Wabakimi are the traditional areas for several First Nation communities; the park has a long cultural history",
                    general: "\u{2022} Phone: (807) 473-3031\n\u{2022} Size: 892061.00 ha\n\u{2022} Year established: 1983\n\u{2022} Park Classification: Wilderness \n\u{2022} Address:\n\tc/o Ministry of Natural Resources\n\t435 James Street S., Suite #221d\n\tThunder Bay\n\tP7E 6S8",
                    camping: [0: (heading: "\(cBac)", detail: "There are over 500 backcountry campsites at Wabakimi. In the spirit of a wilderness park these sites are remote and primitive. Backcountry travel group size is limited to nine people. \n\nCampsites are available on a first-come, first-served basis. Reservations are not required. Permits are available through the park office or select tourism outfitters. Please contact the park office for further information at 807-473-3031.")],
                    activities: [0: (heading: "\(aBrd)", detail: "Wabakimi is a boreal birder’s paradise and offers opportunities to see species such as Boreal Chickadee, Red and White-winged Crossbill, Greater Yellowlegs, Spruce Grouse, Hawk Owl, Great Grey Owl and Pine Grosbeak.   Bald Eagles abound and Gray Jays will follow you throughout your trip!"), 1: (heading: "\(aBtg)", detail: "Motorboats are permitted in the expanded park area. Only tourist operators are allowed to use them in the original park area. Please check with park staff for more information on these boundaries."), 3: (heading: "\(aCan)", detail: "Wabakimi Provincial Park offers canoeing opportunities in a world-class setting.  Canoeists in the park should be experienced, but have the choice of selecting trips that are calm and relaxing, or offer more adventure. Park staff and local tourist outfitters are more than happy to discuss your trip plans with you and help you select the route that suits you best."), 4: (heading: "\(aFsh)", detail: "Wabakimi boasts some of the best fishing in Northwest Ontario, including opportunities for trophy fish. Species such as walleye, Northern Pike, perch, whitefish and Lake Trout are found throughout the park."), 5: (heading: "\(aHnt)", detail: "Hunting is permitted in the expanded park area for moose and is guided by tourist outfitters who can help you organize the trip of a lifetime.  Hunting in the park is subject to Ontario Hunting Regulations."), 6: (heading: "\(aSwm)", detail: "Surprises are around every corner in Wabakimi and many of our lakes boast beautiful beaches which are perfect for taking a relaxing swim after a long day paddling.")],
                    facilities: [0: (heading: "\(fBF)", detail: "Although Wabakimi is a wilderness park, some fly-in tourist outfitters can offer barrier-free access to this wilderness experience."), 1: (heading: "\(fR)", detail: "Boats can be rented through tourist outfitters within the park.")])
