//
//  Wakami.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let wakami = Park(name: "wakami lake",
                  about: "\u{2022} Great fishing and northern camping experience\n\u{2022} Diverse camping experience\n\u{2022} Boreal forest with remnant old growth White Pine\n\u{2022} Historic logging exhibit\n\u{2022} Boreal forest hiking trails\n\u{2022} Wakami Lake canoeing and kayaking\n\u{2022} Wildlife viewing",
                  general: "\u{2022} Phone: 705-233-2853 (mid-May to mid-Sept.) 705-864-3114 (Park Superintendent)\n\u{2022} Size: 12315.51 ha\n\u{2022} Year established: 1973\n\u{2022} Park Classification: Recreational\n\u{2022} Address:\n\t190 Cherry Street\n\tChapleau\n\tP0M 1K0",
                  camping: [0: (heading: "\(cBac)", detail: "There are 5 boat or canoe-in backcountry campsites along the perimeter of Wakami Lake which offer that next level of northern camping experience. Each site has a picnic table, firepit and interior box privy. Check with the Park Office for a map."), 1: (heading: "\(cCar)", detail: "Wakami Lake offers four campgrounds; Birch Hill, Pine Grove, Maple Ridge and Brown’s Bay encompassing 59 campsites many of which provide spectacular waterfront views. Amenities include water taps, vault privies, docks, boat trailer security hitches and fish cleaning stations, all conveniently situated nearby."), 2: (heading: "\(cGrp)", detail: "There is one large, private group campsite located right on the water where you can keep canoes, kayaks and boats moored right on shore at your site. Your group will have your own private washroom complete with a sink with running water. This site must be reserved by calling the Park Superintendent on January 1st at 1-705-864-3114 (leave name telephone number and desired dates).")],
                  activities: [0: (heading: "\(aBik)", detail: "Keep it green and bring your bicycle for getting around on our park roadways or perhaps a bicycle hike of the entire area is of interest to you."), 1: (heading: "\(aBrd)", detail: "Over 100 nesting species of birds have been recorded. The Three-toed Woodpecker is considered provincially significant. The Solitary Sandpiper, Brewer’s Blackbird and Pine Grosbeak are considered regionally significant. Many other forest songbirds, such as warblers, nest in the boreal forest and make Wakami their home."), 2: (heading: "\(aBtg)", detail: "Motorboats are permitted on Wakami Lake, however are not be permitted on Imakaw Lake. Motors on Efby Lake continue to be restricted to under 10 hp."), 3: (heading: "\(aCan)", detail: "Canoe or kayak on Wakami Lake, a scenic 15 km-long lake surrounded by hills of boreal forest.  Kayak rentals are available."), 4: (heading: "\(aFsh)", detail: "Fish species in Wakami Lake include Walleye, Northern Pike, Lake Whitefish, Yellow Perch and White Sucker. Imakaw Lake has been stocked Brook Trout."), 5: (heading: "\(aHik)", detail: "\u{2022} Beaver Meadow Discovery Trail – 2.4 km into the boreal forest (Easy) \n\tHere you can discover how the industrious beaver has altered the landscape while you take in various wildflowers, birds and wildlife. On the side trail you will find a Pond with an active beaver lodge, home to Wakami’s two resident beavers. \n\u{2022} Transitional Forest Trail – 2.5 km with optional 5 km loop through a transitional forest (Moderate) \n\tThis trail takes you through a forest with a split personality. Here the Red Pine, White Pine, Sugar Maple and Yellow Birch are near the northern limit of their range. They are the common species of the Great Lakes, but here in and around Wakami Lake, there is a transition into the boreal forest where trees such as Black Spruce, Balsam Fir and Jack Pine become the dominant species. \n\u{2022} Hidden Bog Trail – take a leisurely stroll into an ecologically fragile area. \n\tHere you can discover strange plants like the pitcher plant and sundew which are scattered across the forest floor leading to a quaking bog. A bog can be a tough place to survive, and some plants add insects to their diet to make ends meet. Please remain on the trail so as not to disturb this fragile community. \n\u{2022} Historical Logging Exhibit – 1 km self-guided trail. (Easy) Under Refurbishment Access limited \n\tHere you can discover the history of logging in the Wakami area from the 1920s to the 1940s, when horses were slowly being replaced by machines. This is demonstrated with restored logging equipment; various log buildings on display and a variety of interpretive panels along the route."), 6: (heading: "\(aSwm)", detail: "Spend a leisurely picnic day with family or friends while enjoying a swim or just admire the picturesque view from our day-use beach. Please note that no lifeguards are posted at the beach.")],
                  facilities: [0: (heading: "\(fBF)", detail: "Barrier-free access is available in Birch Hill Campground."), 1: (heading: "\(fBL)", detail: "The boat launch is conveniently located between Maple Ridge and Brown’s Bay Campgrounds."), 2: (heading: "\(fDU)", detail: "The day-use beach provides a safe swimming area and shady areas with picnic tables, water taps and vault privy. Please note that there are no lifeguards posted on the beach."), 3: (heading: "\(fPSt)", detail: "The gatehouse and store are found in one convenient location. The store provides you with rentals, souvenirs, a variety of park merchandise and some camper supplies. \n\nGroceries, gasoline and many camping supplies are available in the town of Sultan, 10 km east on Highway 667.  There are also complete services available in the Town of Chapleau, approximately 40 minutes west of the park."), 4: (heading: "\(fR)", detail: "\u{2022} Boat and Motors \n\tTwo 16’ Aluminum boats with 20 hp Yamaha or Mercury outboard is available for rent. We provide the necessary safety kit in addition to the required approved Personal Floatation Devices (PFDs). Federal Regulation now requires us to ask for either proof of Operator Competency or we are required to complete a “Dockside Rental Checklist”, which is valid for the duration of the rental period. To reserve the boat and motor please call 1-705-864-3137 from May to September and 1-705-864-3114, September to April. \n\u{2022} Kayaks \n\t12’ Old Town Vapour (recreational) polyethylene \n\t13’ Old Town Cayuga (light touring) polyethylene \n\u{2022} Canoes \n\nIf you are planning a return trip and wish to leave your trailer and/or boat behind for easy convenience, we provide a safe and secure area for storage. Fees and arrangements can be made at the parkstore."), 5: (heading: "\(fTS)", detail: "If you are planning a return trip and wish to leave your trailer and/or boat behind for easy convenience, we provide a safe and secure area for storage. Fees and arrangements can be made at the park store."), 6: (heading: "\(fVC)", detail: "The park Visitor Centre is located adjacent to the park office with limited open hours.")])
