//
//  Wheatley.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let wheatley = Park(name: "wheatley",
                    about: "\u{2022} Ontario’s “deep south” provincial park – at the same latitude as Northern California.\n\u{2022} Campgrounds are situated among a tangle of creeks in a beautifully wooded Carolinian forest setting with a number of creekside campsites.\n\u{2022} Trails wind through a southern style Carolinian forest.\n\u{2022} Many migratory birds pass through and Point Pelee National Park is only 20 minutes away.\n\u{2022} The day-use area features two kilometres of sandy beach\n\u{2022} Unique foot bridges over a creek system connects campgrounds to day- use areas\n\u{2022} Halloween is a special time as campers dress up and decorate their sites. Come and enjoy late fall’s warmth at this southern park!",
                    general: "\u{2022} Phone: (519) 825-4659\n\u{2022} Size: 241.20 ha\n\u{2022} Year established: 1971\n\u{2022} Park Classification: Recreational \n\u{2022} Address:\n\t21116 Klondyke Road, P.O. Box 640\n\tWheatley\n\tN0P 2P0",
                    camping: [0: (heading: "\(cCar)", detail: "Wheatley offers car camping in four campgrounds: Boosey Creek, Highlands, Middle Creek and Two Creeks. \n\nBoosey Creek Campground provides a semi-wilderness camping experience with non-electrical campsites located throughout a series of camping loops. This is a heavily treed area and some roadways are narrow; large trailers will have difficulty manoeuvring. This campground is ideally suited for tents and camper vans with the larger loops accommodating small trailers.  Some of the smaller loops only provide vault toilets but there is a comfort station with showers within an easy walking distance. Water taps are located throughout and a wooden foot bridge provides easy access to day-use and beach areas. \n\nHighlands Campground hosts 44 electrical and 31 non-electrical campsites in a more open, less wooded setting. Amenities such as water taps, a comfort station, laundry facilities and playground are close by. \n\nMiddle Creek Campground is completely electrical and provides a few creekside campsites. Access to the comfort station, vault toilet, water taps and playground is within walking distance. \n\nTwo Creeks Campground is almost completely surrounded by a creek and provides many creekside camping opportunities. Our second wooden foot bridge providing access to day-use and beach areas is accessed through this campground. Comfort station, vault toilets, water taps and playground are all within walking distance."), 1: (heading: "\(cGrp)", detail: "Wheatley Provincial Park has two group campsites available.  Each site varies in size and can accommodate from 9 to 50 people.  These sites are located in a heavily wooded area of the park and are serviced by vault toilets.  They are ideal for those who prefer a more rustic experience. \n\nRoad access is uneven and unpaved and therefore trailers are not recommended; tenting only. \n\nEach site is serviced by vault toilets and water taps with a comfort station and showers located nearby.  The beach is within a 1.5 km walk, bicycle ride or drive. \n\nTo reserve, please call 1-888-ONT-PARK (1-888-668-7275) or 1-519-826-5290 outside of North America."), 2: (heading: "\(cRad)", detail: "All of the camping loops in Boosey Creek are radio-free and allows the opportunity to experience a quieter more natural setting.")],
                    activities: [0: (heading: "\(aBik)", detail: "Wheatley does not have any dedicated bicycle trails but roads throughout the park are easily cycled. The park is an excellent stopping point during a cycle tour along the north shore of Lake Erie."), 1: (heading: "\(aBrd)", detail: "Wheatley Provincial Park is located on a major migratory bird route and therefore provides excellent bird watching opportunities. During spring and fall migrations you can view a variety of warblers, hawks, thrushes and flycatchers. Or watch herons and egrets wade in the shallows of creeks that wind their way through the park. \n\nTo enhance your birding experience, Point Pelee National Park and Rondeau Provincial Park and the ferry to Pelee Island is all within a short drive from the park. \n\nTake the day to participate in the Norm Chesterfield Bird Hike, held annually around Mother’s Day to commemorate this local birding legend!"), 2: (heading: "\(aCan)", detail: "Wheatley is the site of a secluded coastal estuary, where a tangle of creeks flows through a southern style Carolinian forest. Paddle two loops through Boosey Creek to Sugar Creek; approximately 3.2 km."), 3: (heading: "\(aFsh)", detail: "Boosey Creek and Sugar Creek provide great opportunities for fishing. Kids love to dip their lines and see what they can catch. The park participates in the Ontario Federation of Anglers and Hunters (OFAH) Tackleshare program where you can borrow a fully rigged rod and reel. What a great way to introduce them to fishing! \n\nLake Erie also provides great fishing opportunities; smelt, perch, pickerel, and rainbow trout are some of the main species found. You can venture out in your boat from the public boat launch or just fish off the pier at Wheatley Harbour; within minutes of the park. \n\nFor some fishing fun, Wheatley runs an annual kids fishing derby usually held the last weekend in August. You can call the park at (519) 825-4659 for more information."), 4: (heading: "\(aHik)", detail: "Two hiking trails are located in the park. One along the landlocked creek system and the other winds through a mature Carolinian forest of oak, hickory, Tulip, Sassafras, chestnut and Black Gum trees."), 5: (heading: "\(aSwm)", detail: "There is approximately 1.6 km of sandy beach along the stretch of our day-use area. There are no specific changing facilities although there is a comfort station and vault toilets. Swimming areas are not marked with buoys and you will find water to be deep in some areas. \n\nPlease note: there are no lifeguards posted at the beach and pets are not permitted. There is a pet swimming area at the north end of the beach.")],
                    facilities: [0: (heading: "\(fCS)", detail: "Comfort stations (complete with showers and flush toilets) are located in Boosey Creek, Highlands and Two Creeks Campgrounds. The Highlands and Two Creeks comfort stations are located in areas that are easily accessible to Middle Creek Campground campers."), 1: (heading: "\(fDU)", detail: "Scattered throughout the day-use area you will find fire pits for cooking and picnic tables; all on a first-come, first-served basis.  There are also water taps throughout for easy access to drinking water."), 2: (heading: "\(fFT)", detail: "Flush toilets are available at the comfort stations in three campgrounds as well as the day-use areas at the beach."), 3: (heading: "\(fPSt)", detail: "The park store is located inside the registration/park office at the entrance to the park. A variety of camping items, souvenirs, Ontario Parks merchandise, ice, firewood, pop, candy and more are available for your convenience. Stop by and take a look."), 4: (heading: "\(fPSh)", detail: "Wheatley’s day-use and beach areas house three picnic pavilions that are spread out along the Lake Erie shoreline. Each pavilion is equipped with electricity, group barbeques and picnic tables. Pavilion 2 is the closest to a comfort station and Pavilion 3 is located at the farthest end of the day-use area with easy access to the beach and bordered by Boosey Creek. Each of these pavilions may be reserved for a fee."), 5: (heading: "\(fR)", detail: "The Park participates in the OFAH Tackleshare program where you can borrow completely rigged fishing lines for a refundable deposit. \n\nPersonal Floatation Devices (PFDs) are also available with a $25 refundable deposit.")])
