//
//  Windy.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let windy = Park(name: "windy lake",
                 about: "\u{2022} Fantastic sandy beaches and great swimming/water sports scene\n\u{2022} Large day-use area with rental area for private us\n\u{2022} Large private campsites including several double sites for multi-family camping\n\u{2022} Two group camping areas including one waterfront group campsit\n\u{2022} Walk-in car camping site\n\u{2022} Four all-season yurt\n\u{2022} Winter cross-country skiing located northwest of Sudbury",
                 general: "\u{2022} Phone: 705-966-231\n\u{2022} Size: 118.45 h\n\u{2022} Year established: 195\n\u{2022} Park Classification: Recreational \n\u{2022} Address\n\tP.O. Box 560, c/o Windy Lake Provincial Par\n\tLevac\n\tP0M 2C0",
                 camping: [0: (heading: "\(cCar)", detail: "All 93 campsites, including 56 with electricity, are secluded, large and flat. They are close to flush toilets, showers, laundry facilities, playground and drinking water taps. \n\nThree campsites have space for double family camping."), 1: (heading: "\(cGrp)", detail: "Windy Lake offers two group camping experiences.  The first site is located at the westerly most portion of the waterfront and is aptly named The Lakeside Group Site.  This is our premium location which offers a secluded beach, swimming area, volleyball court, horseshoe pit, large fire pit, water tap and bathrooms.  It also comes with a large picnic shelter (for those rainy days) and a large charcoal burning BBQ.  The site will accommodate four to six small trailers and five to ten tents.  Camping is only permitted in the treed area. \n\nThe second group site is located near the day-use area and can accommodate four to six small trailers and five to ten tents."), 2: (heading: "\(cRad)", detail: "The seven walk-in campsites on the shores of Windy Lake are all designated radio-free."), 3: (heading: "\(cRof)", detail: "Please see website for the latest information regarding roofed accommodations."), 4: (heading: "\(cWak)", detail: "Windy Lake offers a unique camping experience for those looking for something just a bit different.  There are seven walk-in campsites available (just a short walk from your car) with five of the sites situated on the waterfront.  This is a great introductory experience to backcountry camping.  This area is radio-free.")],
                 activities: [0: (heading: "\(aBtg)", detail: "Windy Lake is a popular boating destination in the Sudbury Area. Windy Lake has a large easily accessible boat launch."), 1: (heading: "\(aCan)", detail: "Windy Lake is a popular boating destination in the Sudbury Area."), 2: (heading: "\(aFsh)", detail: "Windy Lake has excellent Lake Trout, Walleye, Northern Pike and Smallmouth Bass fishing."), 3: (heading: "\(aHik)", detail: "\u{2022} The Transition Hiking Trail 3 km, 1 hour, easy \n\tAs you walk along the trail it is hard to imagine that this was once the rim of a huge crater made by a large meteorite that impacted the earth nearly two billion years ago. Today, it is a vibrant forest that is home to many plants and animals. As you wander through the changing forest, keep your eyes open for the many birds that inhabit the area, including the Yellow Warbler, Ruffed Grouse and Pileated Woodpecker. At dusk listen for the soft haunting call of an owl. If you time your hike right you can enjoy a variety of beautiful wild flowers that grow on the forest floor including the Pink Lady’s-slipper, Twin Flower, Wild Rose and Star Flower."), 4: (heading: "\(aSwm)", detail: "Windy Lake is a recreational haven and one of the most popular recreational beach areas in the entire Sudbury region. The park’s sandy beaches total more than 1.5 km of Windy Lake shoreline. There is no better place to relax or picnic with your friends and family. A large buoyed swimming area provides the ideal place for kids to splash and play with the rolling green hills serving as the perfect backdrop for photos."), 5: (heading: "\(aWA)", detail: "When the snow falls there is no better place to be then right here at Windy Lake Provincial Park. The park offers some of the best cross-country skiing and snowshoeing in the region. Many winter enthusiasts come for the day, but with four trail-side yurts that are heated and available for winter use, winter camping is easy. Access to the yurts is via ski trails only which is about a 166 m (500 ft) walk. \n\nThe Onaping Falls Nordic Ski Club (link - http://www.onapingfallsnordics.com/ ) operates a 15 kilometre trail network offering professionally groomed trails for both classic and skate styles of skiing for beginners to advance levels. Skiers may purchase a season pass, weekend pass or just pay for the day. Passes are available for purchase at the Park Office, Windy Lake Motel or at the ski chalet during the weekends. \n\nThe ski chalet is open on weekends from 10:00 a.m. to 4:30 p.m. For more information on ski trails or conditions please call (705) 855-2094.")],
                 facilities: [0: (heading: "\(fBF)", detail: "Windy Lake has two barrier-free campsites."), 1: (heading: "\(fBL)", detail: "Windy Lake has a large cement boat launch, dock and large parking lot."), 2: (heading: "\(fCS)", detail: "Windy Lake has a large comfort station in the campground and two smaller comfort stations near the day-use area. \n\n The campground comfort station features flush toilets, hot showers, sinks, change tables and laundry facilities."), 3: (heading: "\(fDU)", detail: "Windy Lake is a great spot to relax on a sunny day; it has one of the most popular recreational beach areas in the Sudbury region.  Sailing, windsurfing, motorboating and waterskiing are favourite summertime activities with the large day-use area making it an ideal spot to spend the day relaxing, playing beach volleyball, swimming with the kids or picnicking with your family."), 4: (heading: "\(fFT)", detail: "The park offers flush toilets."), 5: (heading: "\(fL)", detail: "Laundry facilities are available at the comfort stations."), 6: (heading: "\(fPSt)", detail: "Ontario Parks merchandise is available in the gatehouse."), 7: (heading: "\(fPEA)", detail: "Pet owners near and far will love the Pet Recreation Area at Windy Lake Provincial Park. This large private beach front has been set aside specifically with you and your pet in mind. \n\nLocated along the shores of Windy Lake this beach front is the ideal spot to let your dog run, jump and swim. There is ample room for a picnic and many families spend the day recreating with their pets. \n\nThe Pet Recreation Area allows your pet to be off the leash but you are still required to keep constant care and control of your animal. And don’t forget to poop and scoop."), 8: (heading: "\(fPSh)", detail: "Windy Lake features a reservable day-use area that is ideal for family reunions and work functions. The site features a private beach, washrooms and a large picnic shelter."), 9: (heading: "\(fR)", detail: "Windy Lake has PFDs and Tackleshare fishing equipment.")])
