//
//  Woodland.swift
//  ParksOfOntario
//
//  Created by roux g. buciu on 2016-08-22.
//  Copyright © 2016 ACME Labs. All rights reserved.
//

import Foundation

let woodland = Park(name: "woodland caribou",
                    about: "\u{2022} This wilderness park is a paddler’s paradise offering almost 2,000 km of maintained canoe routes on a myriad of rivers and lakes.\n\u{2022} Enjoy solitude and commune with nature; Woodland Caribou sees fewer than 1,000 paddlers per season. This undisturbed boreal forest is home to one of the largest groups of woodland caribou south of Hudson Bay.\n\u{2022} Two major river systems – the Gammon and Bloodvein flow through the park; Bloodvein River is designated as a Canadian Heritage River\n\u{2022} Excellent fishing for walleye, Northern Pike and Lake Trout and areas with Smallmouth Bass and muskellunge\n\u{2022} This area is valued by local First Nations people who call this home and who honour the area with stories and teachings. Pictographs (rock paintings) are located throughout the park and must be treated with respect\n\u{2022} Woodland Caribou Provincial Park is a partner in the Pimachiowin Aki World Heritage Project. Five First Nations and the Ontario and Manitoba governments are seeking World Heritage Site status for a linked network of protected areas. For more information visit www.pimachiowinaki.org",
                    general: "\u{2022} Phone: (807) 727-1329\n\u{2022} Size: 470620.00 ha\n\u{2022} Year established: 1983\n\u{2022} Park Classification: Wilderness \n\u{2022} Address:\n\t227 Howey Street Box 5003\n\tRed Lake\n\tP0V 2M0",
                    camping: [0: (heading: "\(cBac)", detail: "Woodland Caribou has approximately 1,500 canoe-in campsites. These sites are remote and primitive. Fire rings may or may not be present.")],
                    activities: [0: (heading: "\(aBrd)", detail: "Woodland Caribou is home to the bird species of the boreal forest. Keen birders will be able to check off many species on their life list that are common to the region. Visitors can observe Great Gray Owls that reside in the park, birds of pray such as bald eagles and various species of hawks, waterfowl and numerous nesting songbirds. Many more species are observed during their spring and fall migrations."), 1: (heading: "\(aBtg)", detail: "Powerboats are associated with the remote lodges and outpost camp areas and are primarily found in and along the Gammon and Bloodvein river systems. The rest of the park is almost solely traveled by canoe or kayak."), 2: (heading: "\(aCan)", detail: "Up to 2,000 km of maintained canoe routes over a myriad of connected waterways provide the opportunity to immerse yourself in the most natural setting and to challenge your skills and senses. \n\nPlease contact the park if you need assistance planning your canoe adventure."), 3: (heading: "\(aFsh)", detail: "Woodland Caribou is renowned for its fishing. The most sought after species are walleye, Northern Pike and Lake Trout. Smallmouth Bass are found in some northern lakes of the park and muskellunge are found in one lake in the southwest. \n\nMany of the private outposts and lodges in the parks are dedicated to fishing."), 4: (heading: "\(aSwm)", detail: "Woodland Caribou’s many secluded beaches and plenty of deep drop-offs from bedrock shorelines offer great swimming opportunities.")],
                    facilities: [0: (heading: "\(fPSt)", detail: "A park store selling Woodland Caribou souvenirs is located at our office in Red Lake. Red Lake is a full service community and will be able to fill all your needs.")])
